(()=>{
const typeLabel=t=>({intro:'بطاقة/مقدمة',text:'نص أو نقاط',table:'جدول',chart:'قياس أثر',evidence:'شواهد',metrics:'مؤشرات',process:'خطوات',signatures:'اعتماد وتوقيعات'}[t]||t);
const escA=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let started=false;
function publicLink(book){const base=location.href.split('#')[0].split('?')[0].replace(/index\.html$/,'');return base+'achievement.html?code='+encodeURIComponent(book.access_code||'')}
async function aReq(path,method='GET',body=null,rep=false){return req(path,method,body,rep)}
async function loadBook(){
 const r=await aReq('/rest/v1/achievement_books?select=*&order=created_at.desc&limit=1');
 S.achievementBook=r.ok?(r.data||[])[0]||null:null;
 if(!S.achievementBook){S.achievementSections=[];return}
 const sr=await aReq('/rest/v1/achievement_book_sections?select=*&book_id=eq.'+S.achievementBook.id+'&order=sort_order.asc');
 S.achievementSections=sr.ok?(sr.data||[]):[];
 if(S.achievementSections.length){const ids=S.achievementSections.map(x=>x.id).join(',');const br=await aReq('/rest/v1/achievement_book_blocks?select=*&section_id=in.('+ids+')&order=sort_order.asc');S.achievementBlocks=br.ok?(br.data||[]):[]}else S.achievementBlocks=[];
}
function install(){
 const page=document.getElementById('page-achievement');if(!page||page.dataset.liveBook==='1')return;page.dataset.liveBook='1';
 page.innerHTML=`<div id="achievementWorkspace" class="achievement-workspace"><div class="achievement-empty">جارٍ تحميل ملف التحصيل الدراسي...</div></div>`;
}
function renderWorkspace(){
 install();const area=document.getElementById('achievementWorkspace');if(!area)return;
 const b=S.achievementBook;
 if(!b){area.innerHTML=`<div class="achievement-empty"><b>لا يوجد ملف تحصيل مرتبط بهذا الحساب.</b><br>أنشئ ملف التحصيل أولًا من قاعدة المنصة.</div><div id="gradebookLiveArea" class="gradebook-box"></div>`;renderGradebook();return}
 const sections=S.achievementSections||[],blocks=S.achievementBlocks||[],live=b.status==='live',link=publicLink(b);
 area.innerHTML=`<section class="achievement-hero"><div class="actions"><span class="badge" style="background:rgba(255,255,255,.14);color:#fff">الملف الحي</span><span class="badge ${live?'':'red'}">${live?'منشور':'مغلق'}</span></div><h2>${escA(b.title)}</h2><p>${escA(b.subtitle||'تحليل، خطة، متابعة، قياس أثر')}</p><div class="achievement-meta"><div><span>المدرسة</span><b>${escA(b.school_name)}</b></div><div><span>العام الدراسي</span><b>${escA(b.academic_year)}</b></div><div><span>رمز الملف</span><b class="achievement-code">${escA(b.access_code||'—')}</b></div><div><span>آخر تحديث</span><b>${new Date(b.updated_at).toLocaleString('ar-SA')}</b></div></div><div class="achievement-actions"><button class="btn gold" onclick="achievementPreview()">معاينة الملف كاملًا</button><button class="btn" onclick="achievementCopyLink()">نسخ الرابط</button><button class="btn" onclick="achievementQr()">QR</button><button class="btn" onclick="achievementEditBook()">بيانات الغلاف</button><button class="btn ${live?'danger':''}" onclick="achievementToggle()">${live?'إغلاق الملف':'نشر الملف'}</button></div></section><div class="section-title"><h3>أقسام الملف ومحتوياته</h3><span>أي تعديل يظهر في نفس الرابط فورًا</span></div><div class="achievement-section-grid">${sections.map((s,i)=>{const bs=blocks.filter(x=>x.section_id===s.id);return `<article class="achievement-section-card"><div class="achievement-section-head"><div><h3>${escA(s.title)}</h3><p>${escA(s.description||'')}</p></div><span class="achievement-order">${String(i+1).padStart(2,'0')}</span></div><div class="achievement-blocks">${bs.map(x=>`<div class="achievement-block"><div><b>${escA(x.title||typeLabel(x.block_type))}</b><small>${escA(typeLabel(x.block_type))}${x.is_visible?'':' · مخفي'}</small></div><div class="actions"><button class="btn soft" onclick="achievementEditBlock('${x.id}')">تعديل</button><button class="btn" onclick="achievementToggleBlock('${x.id}',${!x.is_visible})">${x.is_visible?'إخفاء':'إظهار'}</button></div></div>`).join('')||'<div class="achievement-empty">لا توجد أجزاء في هذا القسم.</div>'}</div><div class="achievement-toolbar"><button class="btn soft" onclick="achievementEditSection('${s.id}')">تعديل القسم</button><button class="btn" onclick="achievementToggleSection('${s.id}',${!s.is_visible})">${s.is_visible?'إخفاء القسم':'إظهار القسم'}</button></div></article>`}).join('')}</div><div class="gradebook-box" id="gradebookLiveArea"></div>`;
 renderGradebook();
}
async function refresh(){await loadBook();renderWorkspace()}
window.achievementPreview=()=>{const b=S.achievementBook;if(!b)return;window.open(publicLink(b),'_blank','noopener')};
window.achievementCopyLink=()=>{const b=S.achievementBook;if(!b)return;const l=publicLink(b);navigator.clipboard?.writeText(l).then(()=>toast('تم نسخ رابط ملف التحصيل')).catch(()=>prompt('انسخ الرابط',l))};
window.achievementQr=()=>{const b=S.achievementBook;if(!b)return;const l=publicLink(b),src='https://api.qrserver.com/v1/create-qr-code/?size=320x320&margin=14&data='+encodeURIComponent(l);modal('QR ملف التحصيل',`<div style="text-align:center"><img src="${src}" width="320" height="320" style="max-width:100%;height:auto;border-radius:18px"><h3>${escA(b.title)}</h3><div class="achievement-code">${escA(b.access_code)}</div><p style="color:var(--muted)">هذا الرمز يفتح النسخة الحية الكاملة، وأي تعديل لاحق يظهر من نفس الرابط.</p><button class="btn primary" onclick="achievementCopyLink()">نسخ الرابط</button></div>`)};
window.achievementToggle=async()=>{const b=S.achievementBook;if(!b)return;const next=b.status==='live'?'draft':'live';if(!confirm(next==='live'?'نشر الملف وإتاحته لكل من يملك الرابط؟':'إغلاق الملف العام؟'))return;const r=await aReq('/rest/v1/achievement_books?id=eq.'+b.id,'PATCH',{status:next,updated_at:new Date().toISOString()},true);if(!r.ok)return toast(r.msg||'تعذر تحديث حالة الملف',true);await refresh();toast(next==='live'?'تم نشر ملف التحصيل':'تم إغلاق ملف التحصيل')};
window.achievementEditBook=()=>{const b=S.achievementBook;if(!b)return;modal('بيانات ملف التحصيل',`<form id="achievementBookForm" class="formgrid"><div class="field full"><label>عنوان الملف</label><input name="title" value="${escA(b.title)}" required></div><div class="field"><label>اسم المدرسة</label><input name="school_name" value="${escA(b.school_name)}" required></div><div class="field"><label>العام الدراسي</label><input name="academic_year" value="${escA(b.academic_year)}" required></div><div class="field full"><label>العبارة تحت العنوان</label><input name="subtitle" value="${escA(b.subtitle||'')}"></div><div class="field"><label>رمز المشاركة</label><input name="access_code" value="${escA(b.access_code||'')}" maxlength="20" required></div><button class="btn primary full">حفظ البيانات</button></form>`,()=>{document.getElementById('achievementBookForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));f.access_code=String(f.access_code).trim().toUpperCase().replace(/[^A-Z0-9-]/g,'');f.updated_at=new Date().toISOString();const r=await aReq('/rest/v1/achievement_books?id=eq.'+b.id,'PATCH',f,true);if(!r.ok)return toast(r.msg||'تعذر حفظ البيانات',true);closeModal();await refresh();toast('تم تحديث بيانات الملف')}})};
window.achievementEditSection=id=>{const s=(S.achievementSections||[]).find(x=>x.id===id);if(!s)return;modal('تعديل القسم',`<form id="achievementSectionForm"><div class="field"><label>عنوان القسم</label><input name="title" value="${escA(s.title)}" required></div><div class="field"><label>الوصف المختصر</label><textarea name="description">${escA(s.description||'')}</textarea></div><button class="btn primary" style="width:100%">حفظ</button></form>`,()=>{document.getElementById('achievementSectionForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));f.updated_at=new Date().toISOString();const r=await aReq('/rest/v1/achievement_book_sections?id=eq.'+id,'PATCH',f,true);if(!r.ok)return toast(r.msg||'تعذر حفظ القسم',true);closeModal();await refresh();toast('تم تحديث القسم')}})};
window.achievementToggleSection=async(id,v)=>{const r=await aReq('/rest/v1/achievement_book_sections?id=eq.'+id,'PATCH',{is_visible:v,updated_at:new Date().toISOString()},true);if(!r.ok)return toast(r.msg||'تعذر تحديث القسم',true);await refresh()};
window.achievementToggleBlock=async(id,v)=>{const r=await aReq('/rest/v1/achievement_book_blocks?id=eq.'+id,'PATCH',{is_visible:v,updated_at:new Date().toISOString()},true);if(!r.ok)return toast(r.msg||'تعذر تحديث الجزء',true);await refresh()};
function lines(v){return (v||[]).map(x=>Array.isArray(x)?x.join(' | '):String(x)).join('\n')}
function fieldsLines(v){return (v||[]).map(x=>(x.label||'')+' | '+(x.value||'')).join('\n')}
function metricsLines(v){return (v||[]).map(x=>(x.label||'')+' | '+(x.value||'')+' | '+(x.unit||'')).join('\n')}
function stepsLines(v){return (v||[]).map(x=>(x.title||'')+' | '+(x.text||'')).join('\n')}
function splitRows(t){return String(t||'').split(/\n/).map(x=>x.trim()).filter(Boolean).map(x=>x.split('|').map(y=>y.trim()))}
window.achievementEditBlock=id=>{const b=(S.achievementBlocks||[]).find(x=>x.id===id);if(!b)return;const c=b.content||{};let editor='';if(b.block_type==='intro'||b.block_type==='signatures'){editor=`${b.block_type==='intro'?`<div class="field"><label>النص التعريفي</label><textarea name="body">${escA(c.body||'')}</textarea></div>`:''}<div class="field"><label>الحقول — كل سطر: العنوان | القيمة</label><textarea class="achievement-lines" name="fields">${escA(fieldsLines(c.fields))}</textarea></div>`}else if(b.block_type==='metrics'){editor=`<div class="field"><label>المؤشرات — كل سطر: العنوان | القيمة | الوحدة</label><textarea class="achievement-lines" name="metrics">${escA(metricsLines(c.metrics))}</textarea></div>`}else if(b.block_type==='process'){editor=`<div class="field"><label>الخطوات — كل سطر: عنوان المرحلة | الشرح</label><textarea class="achievement-lines" name="steps">${escA(stepsLines(c.steps))}</textarea></div>`}else if(['table','chart','evidence'].includes(b.block_type)){editor=`<div class="field"><label>عناوين الأعمدة — افصل بينها بـ |</label><input name="headers" value="${escA((c.headers||[]).join(' | '))}"></div><div class="field"><label>صفوف الجدول — كل صف في سطر، وافصل الخانات بـ |</label><textarea class="achievement-lines" name="rows">${escA(lines(c.rows))}</textarea></div><div class="field"><label>ملاحظة أسفل الجدول</label><textarea name="note">${escA(c.note||'')}</textarea></div>`}else{editor=`<div class="field"><label>النقاط — كل نقطة في سطر مستقل</label><textarea class="achievement-lines" name="items">${escA((c.items||[]).join('\n'))}</textarea></div>`}
 modal('تعديل: '+escA(b.title||typeLabel(b.block_type)),`<div class="achievement-editor-help">اكتب البيانات بشكل طبيعي. علامة <b>|</b> تفصل بين خانات الصف الواحد في الجداول فقط.</div><form id="achievementBlockForm"><div class="field"><label>عنوان الجزء</label><input name="title" value="${escA(b.title||'')}"></div>${editor}<button class="btn primary" style="width:100%">حفظ التعديلات</button></form>`,()=>{document.getElementById('achievementBlockForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),next={...c},title=fd.get('title');if(fd.has('body'))next.body=fd.get('body');if(fd.has('fields'))next.fields=splitRows(fd.get('fields')).map(r=>({label:r[0]||'',value:r.slice(1).join(' | ')}));if(fd.has('metrics'))next.metrics=splitRows(fd.get('metrics')).map(r=>({label:r[0]||'',value:r[1]||'',unit:r.slice(2).join(' | ')}));if(fd.has('steps'))next.steps=splitRows(fd.get('steps')).map(r=>({title:r[0]||'',text:r.slice(1).join(' | ')}));if(fd.has('headers'))next.headers=String(fd.get('headers')||'').split('|').map(x=>x.trim()).filter(Boolean);if(fd.has('rows'))next.rows=splitRows(fd.get('rows'));if(fd.has('note'))next.note=fd.get('note');if(fd.has('items'))next.items=String(fd.get('items')||'').split(/\n/).map(x=>x.trim()).filter(Boolean);const r=await aReq('/rest/v1/achievement_book_blocks?id=eq.'+id,'PATCH',{title,content:next,updated_at:new Date().toISOString()},true);if(!r.ok)return toast(r.msg||'تعذر حفظ المحتوى',true);closeModal();await refresh();toast('تم تحديث محتوى الملف')}})};
async function renderGradebook(){const box=document.getElementById('gradebookLiveArea');if(!box)return;const items=S.gradeItems||[];box.innerHTML=`<div class="head"><div><h2 style="font-size:19px">سجل الدرجات</h2><p>بنود التحصيل المرتبطة بفصولك، مع إدخال درجات جماعي.</p></div><button class="btn primary" onclick="openGradeItemModal()">+ بند درجات</button></div>${items.length?items.map(g=>`<div class="grade-item-row"><div><h4>${escA(g.title)}</h4><p>${escA(g.classes?.name||'')} · ${escA(g.category||'')} · من ${escA(g.max_score)}</p></div><div class="actions"><button class="btn soft" onclick="achievementOpenScores('${g.id}')">إدخال الدرجات</button><button class="btn red" onclick="deleteRow('grade_items','${g.id}',loadGradeItems)">حذف</button></div></div>`).join(''):'<div class="achievement-empty">لا توجد بنود درجات بعد.</div>'}`}
window.achievementOpenScores=async itemId=>{const item=(S.gradeItems||[]).find(x=>x.id===itemId);if(!item)return;const st=await aReq('/rest/v1/students?select=id,full_name,student_number&class_id=eq.'+item.class_id+'&is_active=eq.true&order=full_name.asc'),sc=await aReq('/rest/v1/grade_scores?select=*&grade_item_id=eq.'+itemId);if(!st.ok)return toast('تعذر تحميل طلاب الفصل',true);const map=Object.fromEntries((sc.data||[]).map(x=>[x.student_id,x]));modal('درجات: '+escA(item.title),`<form id="bulkScoresForm"><div class="achievement-editor-help">الدرجة العظمى: <b>${escA(item.max_score)}</b>. اترك الخانة فارغة إذا لم تُرصد الدرجة بعد.</div><div class="table-wrap"><table class="table scores-sheet"><thead><tr><th>الطالب</th><th>الرقم</th><th>الدرجة</th><th>ملاحظة</th></tr></thead><tbody>${(st.data||[]).map(s=>`<tr><td>${escA(s.full_name)}</td><td>${escA(s.student_number||'—')}</td><td><input class="score-input" type="number" step="0.01" min="0" max="${escA(item.max_score)}" name="score_${s.id}" value="${escA(map[s.id]?.score??'')}"></td><td><input name="note_${s.id}" value="${escA(map[s.id]?.note||'')}"></td></tr>`).join('')}</tbody></table></div><button class="btn primary" style="width:100%;margin-top:12px">حفظ جميع الدرجات</button></form>`,()=>{document.getElementById('bulkScoresForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),rows=[];for(const s of(st.data||[])){const raw=fd.get('score_'+s.id),note=fd.get('note_'+s.id);if(raw!==''&&raw!==null)rows.push({grade_item_id:itemId,student_id:s.id,score:Number(raw),note:note||null})}for(const row of rows){const r=await aReq('/rest/v1/grade_scores?on_conflict=grade_item_id,student_id','POST',row,true);if(!r.ok){const up=await aReq('/rest/v1/grade_scores?grade_item_id=eq.'+itemId+'&student_id=eq.'+row.student_id,'PATCH',{score:row.score,note:row.note},true);if(!up.ok)return toast(up.msg||'تعذر حفظ إحدى الدرجات',true)}}closeModal();toast('تم حفظ درجات الطلاب')}})};
async function boot(){if(started)return;started=true;try{install();await loadBook();renderWorkspace()}catch(e){console.error(e);const a=document.getElementById('achievementWorkspace');if(a)a.innerHTML='<div class="achievement-empty">تعذر تحميل ملف التحصيل الآن.</div>'}}
const oldRender=window.renderGradeItems||renderGradeItems;try{renderGradeItems=function(){oldRender?.();if(document.getElementById('achievementWorkspace'))renderGradebook()}}catch{}
const timer=setInterval(()=>{try{if(typeof S!=='undefined'&&S.token&&S.user){clearInterval(timer);boot()}}catch{}},250);
})();
