const SB_URL='https://udznpifopbnrcgxtpzza.supabase.co';
const SB_KEY='sb_publishable_UIuOZaeLk3oz25yf1kd-PA_OF8vEu8N';
const EDGE=SB_URL+'/functions/v1/achievement-public';
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let data=null,pages=[],page=0,currentCode='';
function pct(v){return Number.isFinite(+v)?Math.round(+v)+'٪':'—'}
function err(msg){$('entryError').textContent=msg;$('entryError').classList.remove('hidden')}
function cleanCode(v){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9-]/g,'').slice(0,24)}
async function openBook(c){const code=cleanCode(c);if(code.length<4)return err('اكتب رمزًا صحيحًا.');$('entryError').classList.add('hidden');const btn=$('codeForm').querySelector('button');btn.disabled=true;btn.textContent='جارٍ الفتح...';try{const r=await fetch(EDGE,{method:'POST',headers:{apikey:SB_KEY,'Content-Type':'application/json'},body:JSON.stringify({code})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'تعذر فتح الملف');data=d;currentCode=code;history.replaceState(null,'','?code='+encodeURIComponent(code));buildPages();showViewer()}catch(e){err(e.message||'تعذر فتح الملف')}finally{btn.disabled=false;btn.textContent='فتح الملف'}}
function buildPages(){pages=[{type:'cover',title:'الغلاف'},{type:'summary',title:'لوحة التحصيل'}];for(const s of data.sections||[])pages.push({type:'section',title:s.title,section:s});if((data.meetings||[]).length)pages.push({type:'meetings',title:'اجتماعات اللجنة'});if((data.evidence||[]).length)pages.push({type:'evidence',title:'الشواهد'});if((data.students||[]).length)pages.push({type:'students',title:'الطلاب'});page=0}
function showViewer(){$('entry').classList.add('hidden');$('viewer').classList.remove('hidden');$('topTitle').textContent=data.book?.title||'ملف التحصيل الدراسي';$('topSchool').textContent=(data.book?.school_name||'')+' · '+(data.book?.academic_year||'');renderIndex();renderPage()}
function renderIndex(){$('index').innerHTML=`<div class="index-head"><span>فهرس تفاعلي</span><b>${esc(data.book?.title||'ملف التحصيل')}</b></div>`+pages.map((p,i)=>`<button class="${i===page?'active':''}" onclick="go(${i})"><i>${String(i+1).padStart(2,'0')}</i><span>${esc(p.title)}</span></button>`).join('')}
function go(i){page=Math.max(0,Math.min(pages.length-1,i));renderIndex();renderPage();window.scrollTo({top:0,behavior:'smooth'})}
function head(title,sub=''){return `<div class="paper-head"><div><span>المملكة العربية السعودية · وزارة التعليم</span><h1>${esc(title)}</h1>${sub?`<p style="font-size:10px;color:#728286;line-height:1.8;margin:5px 0 0">${esc(sub)}</p>`:''}</div><div class="school"><b>${esc(data.book?.school_name||'')}</b><small>${esc(data.book?.academic_year||'')}</small></div></div>`}
function footer(title){return `<footer class="footer"><span>${esc(title)}</span><b>${page+1} / ${pages.length}</b></footer>`}
function renderBlock(b){const c=b.content||{};if(b.block_type==='table'){const h=Array.isArray(c.headers)?c.headers:[],rows=Array.isArray(c.rows)?c.rows:[];return `<section class="block"><h3>${esc(b.title||'')}</h3>${c.note?`<p>${esc(c.note)}</p>`:''}<div class="table-wrap"><table class="table"><thead><tr>${h.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${(Array.isArray(r)?r:[]).map(x=>`<td>${esc(x||'—')}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${Math.max(1,h.length)}">لا توجد بيانات مسجلة.</td></tr>`}</tbody></table></div></section>`}if(b.block_type==='signatures'){const f=c.fields||[];return `<section class="block"><h3>${esc(b.title||'اعتماد')}</h3><div class="cards">${f.map(x=>`<div class="card"><span>${esc(x.label||'')}</span><b>${esc(x.value||'________________')}</b></div>`).join('')}</div></section>`}if(Array.isArray(c.items))return `<section class="block"><h3>${esc(b.title||'')}</h3><ul>${c.items.map(x=>`<li>${esc(typeof x==='string'?x:x?.text||'')}</li>`).join('')}</ul></section>`;const text=c.text||c.body||c.description||c.note||'';return `<section class="block"><h3>${esc(b.title||'')}</h3>${text?`<p>${esc(text)}</p>`:'<p>لا توجد بيانات مدخلة بعد.</p>'}</section>`}
function cover(){return `<div class="cover"><div><div class="cover-mark">م</div><h1>${esc(data.book?.title||'ملف التحصيل الدراسي')}</h1><p>${esc(data.book?.subtitle||'تحليل · متابعة · تحسين · قياس أثر')}</p><div class="cover-line"></div><strong>${esc(data.book?.school_name||'')}</strong><small>العام الدراسي ${esc(data.book?.academic_year||'')}</small><small style="margin-top:20px">نسخة مشاهدة منظمة · آخر تحديث ${new Date(data.book?.updated_at||Date.now()).toLocaleDateString('ar-SA')}</small></div></div>${footer('الغلاف')}`}
function summary(){const ss=data.summaries||[];return `${head('لوحة التحصيل','ملخص حي للمواد والنتائج المسجلة')}<div class="metrics">${ss.slice(0,4).map(s=>`<div class="metric"><span>${esc(s.subject_name||s.subject_key)}</span><b>${pct(s.average)}</b><small>${esc(s.grade_level||'')} · ${s.exam_count||0} قياس</small></div>`).join('')||'<div class="empty">لا توجد نتائج تحليلية منشورة بعد.</div>'}</div><section class="block"><h3>الفجوات الأبرز</h3><div class="cards">${ss.filter(s=>(s.weak_skills||[]).length).map(s=>`<div class="card"><span>${esc(s.subject_name||s.subject_key)}</span><b>${esc(s.weak_skills[0]?.name||'')}</b><small>${(s.weak_skills||[]).slice(0,4).map(x=>`${esc(x.name)} ${pct(x.avg)}`).join(' · ')}</small></div>`).join('')||'<p>لا توجد فجوات منشورة في النسخة الحالية.</p>'}</div></section>${footer('لوحة التحصيل')}`}
function sectionPage(s){return `${head(s.title,s.description||'')}${(s.blocks||[]).map(renderBlock).join('')||'<div class="empty">لا يوجد محتوى منشور في هذا القسم بعد.</div>'}${footer(s.title)}`}
function meetings(){return `${head('اجتماعات لجنة التحصيل الدراسي','المحاضر والقرارات المنشورة ضمن ملف المشاهدة')}${data.meetings.map(m=>`<section class="meeting"><h3>الاجتماع ${m.meeting_no??'—'} · ${esc(m.topic||'متابعة التحصيل الدراسي')}</h3><div class="meta"><span class="pill">${m.meeting_date?new Date(m.meeting_date).toLocaleDateString('ar-SA'):'بدون تاريخ'}</span><span>${esc(m.target_group||'')}</span><span>${esc(m.venue||'')}</span></div>${m.discussion?`<h4>المناقشة</h4><p style="font-size:10px;line-height:1.9">${esc(m.discussion)}</p>`:''}${(m.decisions||[]).length?`<h4>القرارات والتوصيات</h4><ul>${m.decisions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${(m.follow_up||[]).length?`<h4>المتابعة</h4><ul>${m.follow_up.map(x=>`<li>${esc(typeof x==='string'?x:JSON.stringify(x))}</li>`).join('')}</ul>`:''}</section>`).join('')}${footer('اجتماعات اللجنة')}`}
function evidence(){return `${head('الشواهد والتوثيق','ملفات وأوراق العمل والتقارير التي سمح المعلم بعرضها')}<div class="evidence">${data.evidence.map(e=>`<a href="${esc(e.url||'#')}" target="_blank" rel="noopener"><b>${esc(e.title)}</b><small>${esc(e.evidence_type||'ملف')} · ${esc(e.original_file_name||'')}</small>${e.note?`<small>${esc(e.note)}</small>`:''}</a>`).join('')||'<div class="empty">لا توجد شواهد منشورة.</div>'}</div>${footer('الشواهد')}`}
function students(){return `${head('ملخص الطلاب','تظهر هذه الصفحة فقط عندما يسمح صاحب الملف بعرض تفاصيل الطلاب')}<div class="table-wrap"><table class="table"><thead><tr><th>الطالب</th><th>الرقم</th><th>المتوسط</th></tr></thead><tbody>${data.students.map(s=>`<tr><td>${esc(s.full_name)}</td><td>${esc(s.student_number||'—')}</td><td>${pct(s.average)}</td></tr>`).join('')}</tbody></table></div>${footer('الطلاب')}`}
function renderPage(){const p=pages[page];let html=p.type==='cover'?cover():p.type==='summary'?summary():p.type==='section'?sectionPage(p.section):p.type==='meetings'?meetings():p.type==='evidence'?evidence():students();$('paper').innerHTML=html;$('pageNo').textContent=`${page+1} من ${pages.length}`;$('prevBtn').disabled=page===0;$('nextBtn').disabled=page===pages.length-1}
function changeCode(){data=null;pages=[];$('viewer').classList.add('hidden');$('entry').classList.remove('hidden');$('codeInput').value='';$('codeInput').focus();history.replaceState(null,'',location.pathname)}
$('prevBtn').onclick=()=>go(page-1);$('nextBtn').onclick=()=>go(page+1);$('codeForm').onsubmit=e=>{e.preventDefault();openBook($('codeInput').value)};window.go=go;window.changeCode=changeCode;
const q=new URLSearchParams(location.search).get('code');if(q){$('codeInput').value=q;openBook(q)}