(()=>{
const A={book:null,sections:[],blocks:[],profiles:[],meetings:[],evidence:[],objectives:[],assessments:[],attempts:[],objectiveResults:[],imported:[],view:'cover',grade:'الثالث المتوسط',subject:'arabic',profile:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const subj={arabic:'اللغة العربية',english:'اللغة الإنجليزية',math:'الرياضيات',science:'العلوم'};
const grades=['الأول المتوسط','الثاني المتوسط','الثالث المتوسط'];
const stageLabels=['البداية','أتدرب','أتقدم','أطبق','أتقن','أتحدى نفسي'];
const pct=(n,d=0)=>Number.isFinite(+n)?(+n).toFixed(d)+'٪':'—';
async function ar(path,method='GET',body=null,rep=false){return req(path,method,body,rep)}
async function list(table,q=''){const r=await ar('/rest/v1/'+table+'?select=*'+q);return r.ok?(r.data||[]):[]}
function currentProfile(){return A.profiles.find(x=>x.grade_level===A.grade&&x.subject_key===A.subject)||null}
function levelFor(v,p=currentProfile()){v=+v;if(!Number.isFinite(v))return 'none';const hi=+(p?.high_threshold??80),mid=+(p?.medium_threshold??60);return v>=hi?'high':v>=mid?'medium':'low'}
function levelLabel(l){return l==='high'?'مرتفع':l==='medium'?'متوسط':l==='low'?'متدني':'غير مقاس'}
function allStudentIds(){return new Set((S.allStudents||S.students||[]).map(x=>x.id))}
function profileResults(p){return A.imported.filter(x=>x.subject_profile_id===p?.id)}
function studentRows(p){const rows=profileResults(p),m=new Map();for(const r of rows){const k=r.student_id||('name:'+r.student_name);if(!m.has(k))m.set(k,{id:r.student_id,name:r.student_name,number:r.student_number,items:[]});m.get(k).items.push(r)}
 for(const st of (S.allStudents||[])){const cls=(S.classes||[]).find(c=>c.id===st.class_id);if(cls?.grade===p?.grade_level&&!m.has(st.id))m.set(st.id,{id:st.id,name:st.full_name,number:st.student_number,items:[]})}
 return [...m.values()].map(s=>{const vals=s.items.map(x=>+x.percent).filter(Number.isFinite);const avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null;const sorted=[...s.items].sort((a,b)=>new Date(a.assessment_date||a.created_at)-new Date(b.assessment_date||b.created_at));const first=sorted.find(x=>Number.isFinite(+x.percent)),last=[...sorted].reverse().find(x=>Number.isFinite(+x.percent));const trend=(first&&last&&first!==last)?(+last.percent-(+first.percent)):0;const weak=[...new Map(s.items.filter(x=>levelFor(x.percent,p)==='low'&&(x.skill_name||x.objective_title)).map(x=>[(x.skill_name||x.objective_title),x])).values()];return {...s,avg,trend,weak,last:last||null,level:levelFor(avg,p)}})}
async function loadAll(){
 const br=await ar('/rest/v1/achievement_books?select=*&order=created_at.desc&limit=1');A.book=br.ok?(br.data||[])[0]||null:null;if(!A.book)return;
 const bid=A.book.id;
 const [ss,pp,mm,ee,oo,aa,ii]=await Promise.all([
  list('achievement_book_sections','&book_id=eq.'+bid+'&order=sort_order.asc'),
  list('achievement_subject_profiles','&book_id=eq.'+bid+'&order=grade_level.asc,subject_key.asc'),
  list('achievement_meetings','&book_id=eq.'+bid+'&order=meeting_date.desc.nullslast,created_at.desc'),
  list('achievement_evidence','&book_id=eq.'+bid+'&order=created_at.desc'),
  list('achievement_curriculum_objectives','&book_id=eq.'+bid+'&order=sort_order.asc'),
  list('achievement_assessments','&book_id=eq.'+bid+'&order=created_at.desc'),
  list('achievement_imported_results','&book_id=eq.'+bid+'&order=assessment_date.asc.nullslast,created_at.asc')
 ]);A.sections=ss;A.profiles=pp;A.meetings=mm;A.evidence=ee;A.objectives=oo;A.assessments=aa;A.imported=ii;
 if(ss.length){const ids=ss.map(x=>x.id).join(',');A.blocks=await list('achievement_book_blocks','&section_id=in.('+ids+')&order=sort_order.asc')}
 A.profile=currentProfile();
}
function nav(){return `<aside class="ach-index"><div class="ach-index-head"><small>الفهرس التفاعلي</small><h3>${esc(A.book?.title||'ملف التحصيل الدراسي')}</h3></div>
<div class="ach-index-group"><div class="ach-index-title">الملف الرسمي</div><button data-ach-view="cover">الغلاف</button><button data-ach-view="official">الأقسام الرسمية</button><button data-ach-view="meetings">اجتماعات اللجنة</button><button data-ach-view="pdf">الطباعة والتصدير</button></div>
<div class="ach-index-group"><div class="ach-index-title">التحصيل حسب الصف والمادة</div>${grades.map(g=>`<button data-ach-grade="${esc(g)}">${esc(g)}</button>`).join('')}</div>
<div class="ach-index-group"><div class="ach-index-title">داخل المادة</div><button data-ach-view="subject">لوحة المادة</button><button data-ach-view="results">النتائج والمستويات</button><button data-ach-view="objectives">الأهداف والمهارات</button><button data-ach-view="tests">الاختبارات والتدريب</button><button data-ach-view="students">ملفات الطلاب</button><button data-ach-view="evidence">الشواهد</button></div></aside>`}
function head(title,desc,mark='ت'){return `<div class="ach-paper-head"><div><h2>${esc(title)}</h2><p>${esc(desc||'')}</p></div><div class="ach-paper-mark">${esc(mark)}</div></div>`}
function cover(){return `<div class="ach-page"><div class="ach-cover"><div><div class="seal">ت</div><h1>${esc(A.book.title)}</h1><h2>${esc(A.book.school_name)}</h2><div class="rule"></div><p>كتاب تفاعلي للتحصيل الدراسي والتحليل والاختبارات وقياس الأثر والشواهد<br>جميع الصفحات قابلة للتحديث داخل المنصة ثم تصديرها في ملف PDF رسمي.</p><span class="year">${esc(A.book.academic_year)}</span></div></div></div>`}
function renderBlock(b){const c=b.content||{};if(['table','chart','evidence'].includes(b.block_type)){return `<div class="ach-official-block"><div class="top"><div><h4>${esc(b.title||'')}</h4><small>${esc(b.block_type)}</small></div><button class="ach-btn" onclick="achievementEditBlock('${b.id}')">تعديل الورقة</button></div>${(c.headers||[]).length?`<div class="ach-table-wrap" style="margin-top:12px"><table class="ach-table"><thead><tr>${c.headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${(c.rows||[]).map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:`<div class="ach-empty" style="margin-top:12px">الجدول جاهز للتعبئة.</div>`}</div>`}
 if(b.block_type==='metrics')return `<div class="ach-official-block"><div class="top"><h4>${esc(b.title)}</h4><button class="ach-btn" onclick="achievementEditBlock('${b.id}')">تعديل الورقة</button></div><div class="ach-metrics" style="margin-top:12px">${(c.metrics||[]).map(x=>`<div class="ach-metric"><span>${esc(x.label)}</span><b>${esc(x.value||'—')}</b><small>${esc(x.unit||'')}</small></div>`).join('')}</div></div>`;
 if(b.block_type==='process')return `<div class="ach-official-block"><div class="top"><h4>${esc(b.title)}</h4><button class="ach-btn" onclick="achievementEditBlock('${b.id}')">تعديل الورقة</button></div><div class="ach-grid-3" style="margin-top:12px">${(c.steps||[]).map(x=>`<div class="ach-field-box"><span>${esc(x.title)}</span><b>${esc(x.text)}</b></div>`).join('')}</div></div>`;
 const items=c.items||[];return `<div class="ach-official-block"><div class="top"><h4>${esc(b.title||'')}</h4><button class="ach-btn" onclick="achievementEditBlock('${b.id}')">تعديل الورقة</button></div>${c.body?`<p style="line-height:1.95;color:#455a64">${esc(c.body)}</p>`:''}${items.length?`<ul style="line-height:2;color:#455a64">${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${(c.fields||[]).length?`<div class="ach-grid-3" style="margin-top:12px">${c.fields.map(x=>`<div class="ach-field-box"><span>${esc(x.label)}</span><b>${esc(x.value||'—')}</b></div>`).join('')}</div>`:''}</div>`}
function official(){return `<div class="ach-page">${head('الأقسام الرسمية لملف التحصيل','المحتوى التنظيمي والتوثيقي محفوظ داخل الكتاب، ويمكن تعديل كل ورقة قبل الطباعة.','و')}<div class="ach-section">${A.sections.filter(x=>x.is_visible).map(s=>`<div class="ach-section"><h3>${esc(s.title)}</h3><div class="ach-section-note">${esc(s.description||'')}</div>${A.blocks.filter(b=>b.section_id===s.id&&b.is_visible).map(renderBlock).join('')}</div>`).join('')}</div></div>`}
function selectGrade(){return `<div class="ach-page">${head(A.grade,'اختر المادة لعرض جميع طلاب الصف وتحليل نتائجهم واختباراتهم وشواهدهم.','ص')}<div class="ach-section"><div class="ach-subjects">${Object.entries(subj).map(([k,n])=>{const p=A.profiles.find(x=>x.grade_level===A.grade&&x.subject_key===k),r=studentRows(p),cnt={high:r.filter(x=>x.level==='high').length,medium:r.filter(x=>x.level==='medium').length,low:r.filter(x=>x.level==='low').length};return `<div class="ach-subject-card" data-ach-subject="${k}"><h4>${esc(n)}</h4><p>جميع طلاب ${esc(A.grade)} في هذه المادة.</p><div class="stats"><span class="ach-chip high">مرتفع ${cnt.high}</span><span class="ach-chip medium">متوسط ${cnt.medium}</span><span class="ach-chip low">متدني ${cnt.low}</span></div></div>`}).join('')}</div></div></div>`}
function subjectPage(){const p=currentProfile(),r=studentRows(p),valid=r.filter(x=>x.avg!=null),avg=valid.length?valid.reduce((s,x)=>s+x.avg,0)/valid.length:null;return `<div class="ach-page">${head(`${A.grade} — ${subj[A.subject]}`,'لوحة عامة للمادة خلال العام الدراسي، وتُحدّث تلقائيًا مع إضافة النتائج.','م')}<div class="ach-section"><div class="ach-metrics"><div class="ach-metric"><span>الطلاب</span><b>${r.length}</b><small>في السجل الحالي</small></div><div class="ach-metric"><span>متوسط المادة</span><b>${pct(avg)}</b><small>من النتائج المسجلة</small></div><div class="ach-metric"><span>المتدنون</span><b>${r.filter(x=>x.level==='low').length}</b><small>يحتاجون تدخلًا</small></div><div class="ach-metric"><span>المتحسنون</span><b>${r.filter(x=>x.trend>0).length}</b><small>مقارنة بأول قياس</small></div></div></div>
<div class="ach-section"><h3>توزيع مستويات الطلاب</h3><div class="ach-grid-3"><div class="ach-level high"><h4>مرتفع</h4><strong>${r.filter(x=>x.level==='high').length}</strong><small>${p?.high_threshold??80}٪ فأكثر</small></div><div class="ach-level medium"><h4>متوسط</h4><strong>${r.filter(x=>x.level==='medium').length}</strong><small>من ${p?.medium_threshold??60}٪ إلى أقل من ${p?.high_threshold??80}٪</small></div><div class="ach-level low"><h4>متدني</h4><strong>${r.filter(x=>x.level==='low').length}</strong><small>أقل من ${p?.medium_threshold??60}٪</small></div></div></div>
<div class="ach-section"><div class="ach-toolbar-row"><div><h3>إجراءات المادة</h3><div class="ach-section-note">النتائج والشواهد والاختبارات كلها ترتبط بهذه المادة والصف.</div></div><div class="ach-actions"><button class="ach-btn primary" data-ach-view="results">إدخال/استيراد النتائج</button><button class="ach-btn" data-ach-view="tests">الاختبارات</button><button class="ach-btn" data-ach-view="evidence">رفع شاهد</button></div></div></div></div>`}
function resultsPage(){const p=currentProfile(),r=studentRows(p);return `<div class="ach-page">${head('النتائج ومستويات الطلاب',`${A.grade} — ${subj[A.subject]} | التصنيف آلي حسب متوسط النتائج المسجلة.`,'ن')}<div class="ach-toolbar-row"><div class="ach-actions"><button class="ach-btn primary" onclick="achOpenImport()">استيراد Excel</button><button class="ach-btn" onclick="achAddResult()">إضافة نتيجة يدويًا</button><button class="ach-btn" onclick="achThresholds()">حدود التصنيف</button></div><span class="ach-context">مرتفع ≥ ${p?.high_threshold??80}٪ · متوسط ≥ ${p?.medium_threshold??60}٪ · متدني أقل من ذلك</span></div>
<div class="ach-grid-3"><div class="ach-level high"><h4>مرتفع</h4><strong>${r.filter(x=>x.level==='high').length}</strong></div><div class="ach-level medium"><h4>متوسط</h4><strong>${r.filter(x=>x.level==='medium').length}</strong></div><div class="ach-level low"><h4>متدني</h4><strong>${r.filter(x=>x.level==='low').length}</strong></div></div>
<div class="ach-section"><h3>جميع الطلاب</h3><div class="ach-table-wrap"><table class="ach-table"><thead><tr><th>الطالب</th><th>المتوسط</th><th>المستوى</th><th>الاتجاه</th><th>المهارات المتدنية</th><th>آخر قياس</th></tr></thead><tbody>${r.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${pct(x.avg)}</td><td><span class="ach-chip ${x.level}">${levelLabel(x.level)}</span></td><td><span class="ach-trend ${x.trend>0?'up':x.trend<0?'down':'flat'}">${x.trend>0?'↑ +':x.trend<0?'↓ ':'→ '}${Math.abs(x.trend).toFixed(0)}٪</span></td><td>${x.weak.length?x.weak.map(w=>`<span class="ach-chip low">${esc(w.skill_name||w.objective_title)} ${pct(w.percent)}</span>`).join(' '):'—'}</td><td>${x.last?esc(x.last.assessment_label)+' · '+pct(x.last.percent):'—'}</td></tr>`).join('')||'<tr><td colspan="6">لا توجد نتائج بعد. استورد ملف Excel لتبدأ.</td></tr>'}</tbody></table></div></div>
<div class="ach-section"><div class="ach-pdf-note"><b>عند الطباعة:</b> قائمة المتدنين تُظهر اسم الطالب والدرجة والمهارة/الهدف المتدني فيه ونسبة الإتقان، لتكون جاهزة للخطة العلاجية والقياس البعدي.</div></div></div>`}
function objectivesPage(){const p=currentProfile(),os=A.objectives.filter(x=>x.subject_profile_id===p?.id);return `<div class="ach-page">${head('خريطة المنهج والأهداف','كل اختبار وتدريب يجب أن يرتبط بالدرس والهدف الرئيس والمهارة التي يقيسها.','ه')}<div class="ach-toolbar-row"><div class="ach-context"><b>${A.grade} — ${subj[A.subject]}</b></div><button class="ach-btn primary" onclick="achAddObjective()">+ هدف/مهارة</button></div><div class="ach-table-wrap"><table class="ach-table"><thead><tr><th>الفصل</th><th>الوحدة</th><th>الدرس</th><th>الهدف الرئيس</th><th>المهارة</th></tr></thead><tbody>${os.map(x=>`<tr><td>${esc(x.term||'—')}</td><td>${esc(x.unit_name||'—')}</td><td>${esc(x.lesson_name||'—')}</td><td><b>${esc(x.objective_title)}</b></td><td>${esc(x.skill_name||'—')}</td></tr>`).join('')||'<tr><td colspan="5">لم تُضف خريطة المنهج لهذه المادة بعد.</td></tr>'}</tbody></table></div></div>`}
function testsPage(){const p=currentProfile(),aa=A.assessments.filter(x=>x.subject_profile_id===p?.id);return `<div class="ach-page">${head('الاختبارات والتدريب المتدرج','التدريب يتدرج من الصفر إلى الاحتراف، وأخطاء التدريب لا تدخل في درجة التحصيل النهائية.','خ')}<div class="ach-section"><h3>مسار الطالب من الصفر إلى الاحتراف</h3><div class="ach-training-path">${stageLabels.map((x,i)=>`<div class="ach-stage-step ${i===0?'active':''}"><b>${esc(x)}</b><small>${['تأسيس مبسط','تلميحات وتوجيه','حل مستقل','تطبيق جديد','اختبار إتقان','إثراء وتحدٍ'][i]}</small></div>`).join('')}</div></div>
<div class="ach-section"><div class="ach-toolbar-row"><div><h3>اختبارات المادة</h3><div class="ach-section-note">تشخيصي للسنة السابقة، وتحصلّي للحالية، وعلاجي أو إثرائي حسب مستوى الطالب.</div></div><button class="ach-btn primary" onclick="achAddAssessment()">+ إنشاء اختبار</button></div>${aa.length?`<div class="ach-table-wrap"><table class="ach-table"><thead><tr><th>الاختبار</th><th>النوع</th><th>المستوى</th><th>المصدر</th><th>الحالة</th><th>الكود</th></tr></thead><tbody>${aa.map(x=>`<tr><td><b>${esc(x.title)}</b></td><td>${esc(x.assessment_type)}</td><td>${esc(x.level_target)}</td><td>${x.source_year==='previous'?'السنة السابقة':'السنة الحالية'}</td><td>${esc(x.status)}</td><td>${esc(x.access_code||'—')}</td></tr>`).join('')}</tbody></table></div>`:`<div class="ach-empty"><b>الهيكل جاهز.</b>أنشئ أول اختبار واربطه بدروس المنهج وأهدافه.</div>`}</div></div>`}
function studentsPage(){const p=currentProfile(),r=studentRows(p);return `<div class="ach-page">${head('ملفات الطلاب الفردية','لكل طالب صفحة مستقلة تجمع درجاته وتطوره والمهارات المتدنية والإجراءات العلاجية.','ط')}<div class="ach-table-wrap"><table class="ach-table"><thead><tr><th>الطالب</th><th>المستوى</th><th>المتوسط</th><th>التغير</th><th>أبرز المهارات المتدنية</th></tr></thead><tbody>${r.map(x=>`<tr style="cursor:pointer" onclick="achStudent('${esc(x.id||'')}','${esc(x.name).replace(/'/g,"\\'")}')"><td><b>${esc(x.name)}</b></td><td><span class="ach-chip ${x.level}">${levelLabel(x.level)}</span></td><td>${pct(x.avg)}</td><td>${x.trend>0?'+':''}${x.trend.toFixed(0)}٪</td><td>${x.weak.slice(0,3).map(w=>esc(w.skill_name||w.objective_title)).join('، ')||'—'}</td></tr>`).join('')||'<tr><td colspan="5">لا توجد بيانات طلاب لهذه المادة بعد.</td></tr>'}</tbody></table></div></div>`}
function evidencePage(){const p=currentProfile(),ee=A.evidence.filter(x=>x.subject_profile_id===p?.id);return `<div class="ach-page">${head('شواهد المادة','الشاهد يظهر واضحًا داخل المادة ويمكن تحديد ظهوره في الكتاب وPDF أو إبقائه خاصًا للمعلم.','ش')}<div class="ach-toolbar-row"><div class="ach-context"><b>${A.grade} — ${subj[A.subject]}</b></div><button class="ach-btn primary" onclick="achUploadEvidence()">+ رفع شاهد</button></div><div class="ach-evidence-grid">${ee.map(x=>`<div class="ach-evidence"><div class="ach-evidence-preview">${(x.mime_type||'').includes('image')?'▧':(x.mime_type||'').includes('pdf')?'PDF':'▤'}</div><div class="ach-evidence-body"><h4>${esc(x.title)}</h4><p>${esc(x.evidence_type||'شاهد')} · ${new Date(x.created_at).toLocaleDateString('ar-SA')}</p><div class="actions"><span class="ach-chip">${x.visibility==='teacher'?'خاص':'يظهر في الكتاب'}</span><span class="ach-chip">${x.include_in_pdf?'ضمن PDF':'خارج PDF'}</span></div></div></div>`).join('')||'<div class="ach-empty" style="grid-column:1/-1"><b>لا توجد شواهد بعد.</b>ارفع أول شاهد لهذه المادة وسيظهر هنا بوضوح.</div>`}</div></div>`}
function meetingsPage(){return `<div class="ach-page">${head('اجتماعات لجنة التحصيل','كل اجتماع ورقة مستقلة قابلة للتعديل، ويمكن تضمينها أو استبعادها من PDF النهائي.','ج')}<div class="ach-toolbar-row"><div class="ach-context">عدد الاجتماعات: <b>${A.meetings.length}</b></div><button class="ach-btn primary" onclick="achNewMeeting()">+ اجتماع جديد</button></div>${A.meetings.map(m=>`<div class="ach-meeting" style="margin-bottom:14px"><div class="ach-meeting-header"><div class="ach-field-box"><span>رقم الاجتماع</span><b>${esc(m.meeting_no||'—')}</b></div><div class="ach-field-box"><span>التاريخ</span><b>${esc(m.meeting_date||'—')}</b></div><div class="ach-field-box"><span>الفئة المستهدفة</span><b>${esc(m.target_group||'—')}</b></div><div class="ach-field-box"><span>المكان</span><b>${esc(m.venue||'—')}</b></div></div><div class="ach-meeting-area"><h4>${esc(m.topic||'موضوع الاجتماع')}</h4><p>${esc(m.discussion||'لم يكتب محضر المناقشة بعد.')}</p></div><div class="ach-actions" style="margin-top:14px"><button class="ach-btn" onclick="achEditMeeting('${m.id}')">تعديل الورقة</button><span class="ach-chip">${m.include_in_pdf?'ضمن PDF':'مستبعد من PDF'}</span></div></div>`).join('')||'<div class="ach-empty"><b>ورق الاجتماعات جاهز.</b>أنشئ أول اجتماع وسيظهر كصفحة رسمية قابلة للتعديل.</div>`}</div>`}
function pdfPage(){return `<div class="ach-page">${head('الطباعة والتصدير PDF','النسخة المطبوعة تخفي أدوات المنصة وتظهر الكتاب كملف رسمي منظم.','PDF')}<div class="ach-section"><div class="ach-pdf-note">سيتم تضمين الغلاف، الأقسام الرسمية، الاجتماعات المحددة للطباعة، الصفوف والمواد، نتائج الطلاب، المهارات المتدنية، الاختبارات، الشواهد المختارة، والتوصيات. بعض الجداول يمكن إخراجها أفقيًا عند تطوير محرك PDF النهائي.</div></div><div class="ach-section"><div class="ach-actions"><button class="ach-btn primary" onclick="achPrintBook()">طباعة / حفظ PDF</button><button class="ach-btn" onclick="achievementPreview()">فتح النسخة المشتركة</button></div></div></div>`}
function page(){if(A.view==='cover')return cover();if(A.view==='official')return official();if(A.view==='grade')return selectGrade();if(A.view==='subject')return subjectPage();if(A.view==='results')return resultsPage();if(A.view==='objectives')return objectivesPage();if(A.view==='tests')return testsPage();if(A.view==='students')return studentsPage();if(A.view==='evidence')return evidencePage();if(A.view==='meetings')return meetingsPage();if(A.view==='pdf')return pdfPage();return cover()}
function bind(){document.querySelectorAll('[data-ach-view]').forEach(b=>b.onclick=()=>{A.view=b.dataset.achView;render()});document.querySelectorAll('[data-ach-grade]').forEach(b=>b.onclick=()=>{A.grade=b.dataset.achGrade;A.view='grade';A.profile=currentProfile();render()});document.querySelectorAll('[data-ach-subject]').forEach(b=>b.onclick=()=>{A.subject=b.dataset.achSubject;A.profile=currentProfile();A.view='subject';render()});}
function render(){const root=document.getElementById('achievementWorkspace');if(!root)return;root.innerHTML=`<div class="ach-shell">${nav()}<main class="ach-stage"><div class="ach-topbar"><div class="ach-context"><b>${esc(A.book?.school_name||'')}</b> · ${esc(A.book?.academic_year||'')} · ${esc(A.grade)} · ${esc(subj[A.subject])}</div><div class="actions"><button class="ach-btn" onclick="achievementPreview()">معاينة المشاركة</button><button class="ach-btn gold" onclick="achPrintBook()">PDF</button></div></div><div class="ach-book">${page()}</div></main></div>`;bind();}
window.achPrintBook=()=>window.print();
window.achThresholds=()=>{const p=currentProfile();if(!p)return;modal('حدود تصنيف الطلاب',`<form id="achThr"><div class="field"><label>بداية المستوى المرتفع</label><input name="high" type="number" min="1" max="100" value="${p.high_threshold}"></div><div class="field"><label>بداية المستوى المتوسط</label><input name="mid" type="number" min="0" max="99" value="${p.medium_threshold}"></div><button class="btn primary" style="width:100%">حفظ</button></form>`,()=>{document.getElementById('achThr').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),high=+f.get('high'),mid=+f.get('mid');if(high<=mid)return toast('يجب أن يكون حد المرتفع أعلى من المتوسط',true);const r=await ar('/rest/v1/achievement_subject_profiles?id=eq.'+p.id,'PATCH',{high_threshold:high,medium_threshold:mid,updated_at:new Date().toISOString()},true);if(!r.ok)return toast('تعذر الحفظ',true);closeModal();await bootV2();toast('تم تحديث التصنيف')}})};
function studentOptions(){const p=currentProfile();return (S.allStudents||[]).filter(st=>(S.classes||[]).find(c=>c.id===st.class_id)?.grade===p?.grade_level).map(st=>`<option value="${st.id}" data-num="${esc(st.student_number||'')}">${esc(st.full_name)}</option>`).join('')}
window.achAddResult=()=>{const p=currentProfile();modal('إضافة نتيجة',`<form id="achResult" class="formgrid"><div class="field full"><label>الطالب</label><select name="student_id" required><option value="">اختر</option>${studentOptions()}</select></div><div class="field"><label>اسم الاختبار</label><input name="assessment_label" required></div><div class="field"><label>التاريخ</label><input name="assessment_date" type="date"></div><div class="field"><label>الدرجة</label><input name="score" type="number" step=".01"></div><div class="field"><label>الدرجة الكبرى</label><input name="max_score" type="number" step=".01"></div><div class="field"><label>المهارة</label><input name="skill_name"></div><div class="field"><label>الهدف</label><input name="objective_title"></div><button class="btn primary full">حفظ النتيجة</button></form>`,()=>{document.getElementById('achResult').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),st=(S.allStudents||[]).find(x=>x.id===f.student_id),sc=+f.score,mx=+f.max_score;const body={book_id:A.book.id,subject_profile_id:p.id,student_id:f.student_id,student_name:st?.full_name||'',student_number:st?.student_number||null,assessment_label:f.assessment_label,assessment_date:f.assessment_date||null,score:Number.isFinite(sc)?sc:null,max_score:Number.isFinite(mx)?mx:null,percent:Number.isFinite(sc)&&Number.isFinite(mx)&&mx>0?Math.round(sc/mx*10000)/100:null,skill_name:f.skill_name||null,objective_title:f.objective_title||null};const r=await ar('/rest/v1/achievement_imported_results','POST',body,true);if(!r.ok)return toast('تعذر حفظ النتيجة',true);closeModal();await bootV2();A.view='results';render();toast('تم حفظ النتيجة')}})};
async function ensureXlsx(){if(window.XLSX)return true;return new Promise(res=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=()=>res(true);s.onerror=()=>res(false);document.head.appendChild(s)})}
window.achOpenImport=()=>{modal('استيراد درجات من Excel',`<div class="ach-pdf-note" style="margin-bottom:12px">يمكن أن يحتوي الملف على أعمدة: اسم الطالب، رقم الطالب، الاختبار، الدرجة، الدرجة الكبرى، التاريخ، المهارة، الهدف. سيُحسب التقدير تلقائيًا من الدرجة.</div><form id="achImport"><div class="field"><label>ملف Excel</label><input name="file" type="file" accept=".xlsx,.xls,.csv" required></div><div class="field"><label>اسم الاختبار الافتراضي (إذا لم يوجد عمود)</label><input name="label" value="اختبار مستورد"></div><button class="btn primary" style="width:100%">قراءة واستيراد</button></form>`,()=>{document.getElementById('achImport').onsubmit=async e=>{e.preventDefault();const ok=await ensureXlsx();if(!ok)return toast('تعذر تحميل قارئ Excel',true);const fd=new FormData(e.target),file=fd.get('file'),buf=await file.arrayBuffer(),wb=XLSX.read(buf),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''});if(!rows.length)return toast('الملف لا يحتوي بيانات',true);const norm=o=>Object.fromEntries(Object.entries(o).map(([k,v])=>[String(k).trim().replace(/\s+/g,' '),v]));const all=S.allStudents||[],p=currentProfile(),payload=[];for(const raw of rows){const o=norm(raw),name=String(o['اسم الطالب']||o['الطالب']||o['الاسم']||'').trim();if(!name)continue;const num=String(o['رقم الطالب']||o['الرقم']||'').trim(),st=all.find(x=>(num&&String(x.student_number||'')===num)||x.full_name.trim()===name),score=+(o['الدرجة']||o['درجة']||o['score']),max=+(o['الدرجة الكبرى']||o['من']||o['max']||100),per=Number.isFinite(score)&&Number.isFinite(max)&&max>0?Math.round(score/max*10000)/100:null;payload.push({book_id:A.book.id,subject_profile_id:p.id,student_id:st?.id||null,student_name:name,student_number:num||st?.student_number||null,source_file_name:file.name,assessment_label:String(o['الاختبار']||o['اسم الاختبار']||fd.get('label')),assessment_date:o['التاريخ']||null,score:Number.isFinite(score)?score:null,max_score:Number.isFinite(max)?max:null,percent:per,skill_name:String(o['المهارة']||'').trim()||null,objective_title:String(o['الهدف']||'').trim()||null});}if(!payload.length)return toast('لم أجد أسماء طلاب قابلة للاستيراد',true);const r=await ar('/rest/v1/achievement_imported_results','POST',payload,true);if(!r.ok)return toast('تعذر استيراد البيانات',true);closeModal();await bootV2();A.view='results';render();toast('تم استيراد '+payload.length+' نتيجة')}})};
window.achAddObjective=()=>{const p=currentProfile();modal('إضافة هدف أو مهارة',`<form id="achObj" class="formgrid"><div class="field"><label>الفصل الدراسي</label><input name="term"></div><div class="field"><label>الوحدة</label><input name="unit_name"></div><div class="field"><label>الدرس</label><input name="lesson_name"></div><div class="field"><label>المهارة</label><input name="skill_name"></div><div class="field full"><label>الهدف الرئيس</label><input name="objective_title" required></div><button class="btn primary full">حفظ</button></form>`,()=>{document.getElementById('achObj').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));Object.assign(f,{book_id:A.book.id,subject_profile_id:p.id});const r=await ar('/rest/v1/achievement_curriculum_objectives','POST',f,true);if(!r.ok)return toast('تعذر الحفظ',true);closeModal();await bootV2();A.view='objectives';render();toast('تمت إضافة الهدف')}})};
window.achAddAssessment=()=>{const p=currentProfile();modal('إنشاء اختبار تحصيلي',`<form id="achAss" class="formgrid"><div class="field full"><label>اسم الاختبار</label><input name="title" required></div><div class="field"><label>النوع</label><select name="assessment_type"><option value="diagnostic">تشخيصي</option><option value="formative">تحصيلي خلال السنة</option><option value="mastery">إتقان</option><option value="remedial">علاجي</option><option value="enrichment">إثرائي</option></select></div><div class="field"><label>المستوى المستهدف</label><select name="level_target"><option value="adaptive">تكيفي حسب الطالب</option><option value="low">متدني</option><option value="medium">متوسط</option><option value="high">مرتفع</option><option value="all">الجميع</option></select></div><div class="field"><label>مصدر الدروس</label><select name="source_year"><option value="previous">السنة السابقة</option><option value="current">السنة الحالية</option></select></div><div class="field"><label>المدة بالدقائق</label><input name="duration_min" type="number" value="20"></div><button class="btn primary full">إنشاء</button></form>`,()=>{document.getElementById('achAss').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));f.duration_min=+f.duration_min;Object.assign(f,{book_id:A.book.id,subject_profile_id:p.id,access_code:rand(6)});const r=await ar('/rest/v1/achievement_assessments','POST',f,true);if(!r.ok)return toast('تعذر إنشاء الاختبار',true);closeModal();await bootV2();A.view='tests';render();toast('تم إنشاء الاختبار. إضافة الأسئلة وربط الأهداف هي الخطوة التالية')}})};
window.achNewMeeting=()=>achMeetingForm(null);window.achEditMeeting=id=>achMeetingForm(A.meetings.find(x=>x.id===id));
function achMeetingForm(m){m=m||{};modal(m.id?'تعديل ورقة الاجتماع':'اجتماع جديد',`<form id="achMeet" class="formgrid"><div class="field"><label>رقم الاجتماع</label><input name="meeting_no" type="number" value="${esc(m.meeting_no||'')}"></div><div class="field"><label>التاريخ</label><input name="meeting_date" type="date" value="${esc(m.meeting_date||'')}"></div><div class="field"><label>الفئة المستهدفة</label><input name="target_group" value="${esc(m.target_group||'')}"></div><div class="field"><label>المكان</label><input name="venue" value="${esc(m.venue||'')}"></div><div class="field full"><label>موضوع الاجتماع</label><input name="topic" value="${esc(m.topic||'')}"></div><div class="field full"><label>ما تم خلال الاجتماع / المناقشة</label><textarea name="discussion" style="min-height:180px">${esc(m.discussion||'')}</textarea></div><div class="field"><label><input name="include_in_pdf" type="checkbox" ${m.include_in_pdf!==false?'checked':''}> تضمين في PDF</label></div><button class="btn primary full">حفظ ورقة الاجتماع</button></form>`,()=>{document.getElementById('achMeet').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),f=Object.fromEntries(fd);f.meeting_no=f.meeting_no?+f.meeting_no:null;f.meeting_date=f.meeting_date||null;f.include_in_pdf=fd.has('include_in_pdf');f.book_id=A.book.id;const r=await ar('/rest/v1/achievement_meetings'+(m.id?'?id=eq.'+m.id:''),m.id?'PATCH':'POST',f,true);if(!r.ok)return toast('تعذر حفظ الاجتماع',true);closeModal();await bootV2();A.view='meetings';render();toast('تم حفظ ورقة الاجتماع')}})}
window.achUploadEvidence=()=>{const p=currentProfile();modal('رفع شاهد للمادة',`<form id="achEv" class="formgrid"><div class="field full"><label>عنوان الشاهد</label><input name="title" required></div><div class="field"><label>نوع الشاهد</label><select name="evidence_type"><option>تحليل نتائج</option><option>اختبار تشخيصي</option><option>خطة علاجية</option><option>قياس بعدي</option><option>ورقة عمل</option><option>نشاط</option><option>تكريم</option><option>أخرى</option></select></div><div class="field"><label>الظهور</label><select name="visibility"><option value="book">يظهر في الكتاب</option><option value="teacher">خاص للمعلم</option></select></div><div class="field full"><label>الملف</label><input name="file" type="file" required accept=".pdf,.xlsx,.xls,.doc,.docx,.ppt,.pptx,.jpg,.jpeg,.png,.webp"></div><div class="field"><label><input name="include_in_pdf" type="checkbox" checked> تضمين في PDF</label></div><button class="btn primary full">رفع الشاهد</button></form>`,()=>{document.getElementById('achEv').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),file=fd.get('file'),safe=file.name.replace(/[^\w.\-\u0600-\u06FF]/g,'_'),path=S.user.id+'/achievement/'+p.id+'/'+Date.now()+'-'+safe;const up=await fetch(SB_URL+'/storage/v1/object/teacher-files/'+encodeURI(path),{method:'POST',headers:{apikey:SB_KEY,Authorization:'Bearer '+S.token,'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:file});if(!up.ok)return toast('تعذر رفع الملف',true);const body={book_id:A.book.id,subject_profile_id:p.id,title:String(fd.get('title')),evidence_type:String(fd.get('evidence_type')),storage_path:path,original_file_name:file.name,mime_type:file.type||null,file_size:file.size,visibility:String(fd.get('visibility')),include_in_pdf:fd.has('include_in_pdf')};const r=await ar('/rest/v1/achievement_evidence','POST',body,true);if(!r.ok)return toast('رُفع الملف لكن تعذر حفظ بيانات الشاهد',true);closeModal();await bootV2();A.view='evidence';render();toast('تم رفع الشاهد')}})};
window.achStudent=(id,name)=>{const p=currentProfile(),r=studentRows(p).find(x=>(id&&x.id===id)||x.name===name);if(!r)return;modal('ملف الطالب: '+esc(r.name),`<div class="ach-metrics"><div class="ach-metric"><span>المتوسط</span><b>${pct(r.avg)}</b></div><div class="ach-metric"><span>المستوى</span><b>${levelLabel(r.level)}</b></div><div class="ach-metric"><span>التغير</span><b>${r.trend>0?'+':''}${r.trend.toFixed(0)}٪</b></div><div class="ach-metric"><span>عدد القياسات</span><b>${r.items.length}</b></div></div><div class="ach-section"><h3>المهارات/الأهداف المتدنية</h3>${r.weak.length?r.weak.map(w=>`<div class="ach-field-box" style="margin-bottom:7px"><span>${esc(w.skill_name||w.objective_title)}</span><b>${pct(w.percent)} · ${esc(w.assessment_label)}</b></div>`).join(''):'<div class="ach-empty">لا توجد مهارات متدنية مسجلة.</div>'}</div><div class="ach-section"><h3>سجل القياسات</h3><div class="ach-table-wrap"><table class="ach-table"><thead><tr><th>الاختبار</th><th>النتيجة</th><th>المهارة</th></tr></thead><tbody>${r.items.map(x=>`<tr><td>${esc(x.assessment_label)}</td><td>${pct(x.percent)}</td><td>${esc(x.skill_name||x.objective_title||'—')}</td></tr>`).join('')}</tbody></table></div></div>`)};
async function bootV2(){await loadAll();A.profile=currentProfile();render()}
function install(){const page=document.getElementById('page-achievement');if(!page)return false;page.dataset.liveBook='2';page.innerHTML='<div id="achievementWorkspace"><div class="ach-empty">جارٍ تجهيز كتاب التحصيل الدراسي...</div></div>';return true}
async function start(){if(!install())return;try{await bootV2()}catch(e){console.error(e);document.getElementById('achievementWorkspace').innerHTML='<div class="ach-empty"><b>تعذر تحميل كتاب التحصيل.</b>أعد فتح القسم أو تسجيل الدخول من جديد.</div>'}}
let tries=0;const t=setInterval(()=>{tries++;try{if(typeof S!=='undefined'&&S.token&&S.user){clearInterval(t);start()}else if(tries>80)clearInterval(t)}catch{}},250);
})();
