(()=>{
const $=id=>document.getElementById(id);const form=$('builder');
const esc=s=>String(s??'').trim();
const uid=()=>crypto.getRandomValues(new Uint32Array(4)).reduce((s,n)=>s+n.toString(36),'').slice(0,28);
function rosterNames(){return [...new Set($('roster').value.split(/\r?\n/).map(esc).filter(x=>x.length>=2&&x.length<=120))].slice(0,120)}
function sections(){return [...document.querySelectorAll('.section-row[data-subject]')].filter(r=>r.querySelector('.enabled').checked).map(r=>({subject:r.dataset.subject,question_count:Number(r.querySelector('.count').value),duration_minutes:Number(r.querySelector('.minutes').value),calculator:r.dataset.subject==='math'&&!!r.querySelector('.calculator input')?.checked}))}
function config(){const identity=document.querySelector('[name=identity]:checked').value;return{id:uid(),version:1,grade_key:'middle_3',test_type:document.querySelector('[name=testType]:checked').value,title:`محاكاة نافس — ${esc($('className').value)}`,class_name:esc($('className').value),school_name:esc($('schoolName').value),teacher_name:esc($('teacherName').value),principal_name:esc($('principalName').value),identity_mode:identity,roster:identity==='list'?rosterNames():[],sections:sections(),show_result:$('showResult').checked,show_answers:$('showAnswers').checked,shuffle_questions:$('shuffleQuestions').checked,shuffle_options:$('shuffleOptions').checked,allow_copy:$('allowCopy').checked,attempts:Number($('attempts').value),closes_at:$('closesAt').value?new Date($('closesAt').value).toISOString():null,break_minutes:Number($('breakMinutes').value)||0}}
function encode(value){const bytes=new TextEncoder().encode(JSON.stringify(value));let raw='';bytes.forEach(x=>raw+=String.fromCharCode(x));return btoa(raw).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')}
function validate(c){if(!c.class_name)return'اكتب اسم الفصل.';if(!c.sections.length)return'فعّل قسمًا واحدًا على الأقل.';if(c.test_type==='single'&&c.sections.length!==1)return'اختبار المجال الواحد يحتاج إلى قسم واحد فقط.';if(c.sections.some(s=>!Number.isInteger(s.question_count)||s.question_count<5||s.question_count>40))return'عدد الأسئلة في كل قسم يجب أن يكون بين 5 و40.';if(c.sections.some(s=>!Number.isInteger(s.duration_minutes)||s.duration_minutes<5||s.duration_minutes>120))return'زمن كل قسم يجب أن يكون بين 5 و120 دقيقة.';if(c.identity_mode==='list'&&!c.roster.length)return'أضف أسماء الطلاب عند اختيار الهوية من القائمة.';if(c.closes_at&&new Date(c.closes_at).getTime()<=Date.now())return'وقت إغلاق الاختبار يجب أن يكون في المستقبل.';return''}
function saveDraft(){try{const fields={className:$('className').value,schoolName:$('schoolName').value,teacherName:$('teacherName').value,principalName:$('principalName').value,roster:$('roster').value};localStorage.setItem('nafes_builder_draft',JSON.stringify(fields))}catch(_){}}
function restore(){try{const d=JSON.parse(localStorage.getItem('nafes_builder_draft')||'{}');for(const [k,v] of Object.entries(d))if($(k)&&typeof v==='string')$(k).value=v}catch(_){}}
document.querySelectorAll('[name=identity]').forEach(x=>x.addEventListener('change',()=>{$('rosterBox').classList.toggle('hidden',document.querySelector('[name=identity]:checked').value!=='list')}));
document.querySelectorAll('[name=testType]').forEach(x=>x.addEventListener('change',()=>{if(x.checked&&x.value==='single'){const rows=[...document.querySelectorAll('.section-row[data-subject]')];rows.forEach((r,i)=>r.querySelector('.enabled').checked=i===0)}}));
form.addEventListener('input',saveDraft);
form.addEventListener('submit',e=>{e.preventDefault();const c=config(),error=validate(c);$('formError').textContent=error;if(error)return;const link=new URL('simulation.html',location.href);link.searchParams.set('c',encode(c));$('createdLink').value=link.href;$('openLink').href=link.href;$('createdSummary').textContent=`${c.sections.length} ${c.sections.length===1?'قسم':'أقسام'} · ${c.sections.reduce((n,s)=>n+s.question_count,0)} سؤالًا · ${c.class_name}`;$('created').classList.remove('hidden');$('qr').innerHTML='';if(window.QRCode)new QRCode($('qr'),{text:link.href,width:180,height:180,colorDark:'#17324d',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});$('created').scrollIntoView({behavior:'smooth',block:'start'})});
$('copyLink').onclick=async()=>{await navigator.clipboard.writeText($('createdLink').value);$('copyLink').textContent='تم النسخ';setTimeout(()=>$('copyLink').textContent='نسخ الرابط',1400)};
$('rosterImage').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;$('ocrState').textContent='جارٍ قراءة الأسماء من الصورة...';try{if(!window.Tesseract){await new Promise((ok,bad)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=bad;document.head.appendChild(s)})}const result=await window.Tesseract.recognize(file,'ara+eng');const lines=String(result.data.text||'').split(/\r?\n/).map(x=>x.replace(/^\s*[\d٠-٩]+[.)،-]?\s*/,'').trim()).filter(x=>x.length>=5&&/[\u0600-\u06ff]/.test(x));$('roster').value=[...new Set(lines)].join('\n');$('ocrState').textContent=`تمت قراءة ${lines.length} سطرًا. راجع الأسماء وعدّلها قبل إنشاء الاختبار.`;saveDraft()}catch(_){$('ocrState').textContent='تعذرت القراءة الآلية. يمكنك لصق الأسماء يدويًا في المربع.'}});
restore();
})();
