(()=>{
'use strict';const $=id=>document.getElementById(id),form=$('builder'),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),ar=x=>new Intl.NumberFormat('ar-SA').format(x),names={reading:'القراءة',math:'الرياضيات',science:'العلوم'};
let catalog=null,draft=null,configAtPreview=null,busy=false,initialized=false;
const toggleMap={showResult:'show_result',showAnswers:'show_answers',showIndicatorResult:'show_indicator_result',showCorrectCount:'show_correct_count',shuffleQuestions:'shuffle_questions',shuffleOptions:'shuffle_options',allowCopy:'allow_copy',disableRightClick:'disable_right_click',disablePrint:'disable_print',disableShortcuts:'disable_shortcuts',allowBack:'allow_back',onePerPage:'one_per_page',lockSession:'lock_session',logVisibility:'log_visibility',watermark:'watermark'};
const rows=()=>[...document.querySelectorAll('.section-row[data-subject]')],kind=()=>document.querySelector('[name=testType]:checked').value;
function rosterNames(){return [...new Set($('roster').value.split(/\r?\n/).map(x=>x.trim()).filter(x=>x.length>=2&&x.length<=120))].slice(0,1000);}
function saveDraft(){try{localStorage.setItem('nafes_builder_draft',JSON.stringify(Object.fromEntries(['className','schoolName','teacherName','principalName','roster'].map(k=>[k,$(k).value]))));}catch(_){}}
function restore(){try{for(const[k,v]of Object.entries(JSON.parse(localStorage.getItem('nafes_builder_draft')||'{}')))if($(k)&&typeof v==='string')$(k).value=v;}catch(_){}}
function selectPanels(){if(!catalog)return;const selected=new Map([...document.querySelectorAll('.indicator-option')].map(x=>[x.querySelector('.indicator-check').value,{checked:x.querySelector('.indicator-check').checked,count:x.querySelector('.indicator-count').value}]));const models=new Map([...document.querySelectorAll('[data-select-subject]')].map(x=>[x.dataset.selectSubject,x.querySelector('.model-picker')?.value]));const custom=kind()==='custom';$('customMode').classList.toggle('hidden',!custom);$('selectionPanels').innerHTML=rows().filter(r=>r.querySelector('.enabled').checked).map(row=>{const subject=row.dataset.subject;return `<section class="selection-panel" data-select-subject="${subject}"><h3>${names[subject]}</h3>${custom?`<p class="selection-summary">اختر المؤشرات التي تريد قياسها فقط.</p><input class="indicator-search" type="search" placeholder="بحث في مؤشرات ${names[subject]}" aria-label="بحث في المؤشرات"><div class="indicator-options">${catalog.indicators.filter(i=>i.subject===subject).map((i,n)=>`<label class="indicator-option"><input type="checkbox" class="indicator-check" value="${esc(i.key)}"><span>${ar(n+1)}) ${esc(i.text)}<small>المتاح: ${ar(i.available)} سؤالًا</small></span><input class="indicator-count" type="number" min="1" max="30" value="5" aria-label="عدد أسئلة المؤشر ${ar(n+1)}"></label>`).join('')}</div>`:`<label>نموذج المحاكاة<select class="model-picker">${catalog.forms.filter(f=>f.subject===subject).map(f=>`<option value="${f.model_no}" ${!f.ready?'disabled':''}>المحاكاة ${ar(f.model_no)} ${f.ready?'— جاهزة':'— قيد إعداد البنك'}</option>`).join('')}</select></label>`}</section>`;}).join('');document.querySelectorAll('.indicator-option').forEach(x=>{const old=selected.get(x.querySelector('.indicator-check').value);if(old){x.querySelector('.indicator-check').checked=old.checked;x.querySelector('.indicator-count').value=old.count;}});document.querySelectorAll('[data-select-subject]').forEach(x=>{if(models.get(x.dataset.selectSubject)&&x.querySelector('.model-picker'))x.querySelector('.model-picker').value=models.get(x.dataset.selectSubject);});toggleCounts();}
function toggleCounts(){document.querySelectorAll('.indicator-count').forEach(x=>x.hidden=$('countMode').value!=='per_indicator');rows().forEach(r=>{r.querySelector('.count').min=kind()==='custom'?'1':'5';r.querySelector('.count').max=kind()==='custom'?'60':'40';r.querySelector('.count').disabled=kind()==='custom'&&$('countMode').value==='per_indicator';});}
function config(){const type=kind(),settings=Object.fromEntries(Object.entries(toggleMap).map(([id,key])=>[key,$(id).checked]));settings.attempts=Number($('attempts').value);settings.opens_at=$('opensAt').value?new Date($('opensAt').value).toISOString():null;settings.closes_at=$('closesAt').value?new Date($('closesAt').value).toISOString():null;settings.break_minutes=Number($('breakMinutes').value);
 const sections=rows().filter(r=>r.querySelector('.enabled').checked).map(r=>{const subject=r.dataset.subject,panel=document.querySelector(`[data-select-subject="${subject}"]`);return {subject,question_count:Number(r.querySelector('.count').value),duration_minutes:Number(r.querySelector('.minutes').value),calculator:!!r.querySelector('.calculator input')?.checked,model_no:Number(panel?.querySelector('.model-picker')?.value||1),indicators:type==='custom'?[...panel.querySelectorAll('.indicator-check:checked')].map(x=>({key:x.value,count:Number(x.closest('label').querySelector('.indicator-count').value)})):[],fixed_model:type==='custom'&&$('fixedModel').value?Number($('fixedModel').value):undefined};});
 if(type==='single'&&sections.length!==1)throw new Error('فعّل مادة واحدة في اختبار المجال الواحد.');if(!sections.length)throw new Error('فعّل مادة واحدة على الأقل.');if(type==='custom'&&sections.some(s=>!s.indicators.length))throw new Error('اختر مؤشرًا واحدًا على الأقل في كل مادة مفعلة.');
 if(settings.closes_at&&new Date(settings.closes_at)<=new Date())throw new Error('حدد وقت نهاية مستقبليًا.');
 return {kind:type==='custom'?'multi_indicator':'simulation',grade_key:'middle_3',title:$('testTitle').value.trim(),class_name:$('className').value.trim(),school_name:$('schoolName').value.trim(),teacher_name:$('teacherName').value.trim(),principal_name:$('principalName').value.trim(),identity_mode:document.querySelector('[name=identity]:checked').value,roster:rosterNames(),sections,count_mode:$('countMode').value,settings};}
function showPreview(d){draft=d;configAtPreview=d.config;$('previewPanel').classList.remove('hidden');$('previewMeta').textContent=`${d.config.title} · ${ar(d.sections.reduce((n,s)=>n+s.questions.length,0))} سؤالًا`;$('previewQuestions').innerHTML=d.sections.map(s=>`<details open><summary>${names[s.subject]} · ${ar(s.questions.length)} سؤالًا</summary>${s.questions.map((q,n)=>`<article>${q.context?`<div class="context">${esc(q.context)}</div>`:''}${window.NafesMedia.render(q)}<p class="stem">${ar(n+1)}) ${esc(q.question)}</p><ol type="A">${q.options.map(o=>`<li>${esc(o)}</li>`).join('')}</ol><p class="key">الإجابة: ${['أ','ب','ج','د'][q.correctIndex]}) ${esc(q.options[q.correctIndex])}<br>${esc(q.explanation)}</p><p>${esc(q.indicator_text)}</p><button class="replace-question" data-replace="${esc(q.id)}" type="button">تبديل هذا السؤال</button></article>`).join('')}</details>`).join('');$('publish').disabled=false;}
async function makePreview(regenerate=false){if(busy)return;busy=true;$('formError').textContent='';$('previewError').textContent='';document.querySelector('.create-button').disabled=true;try{const c=regenerate&&configAtPreview?configAtPreview:config();const d=await NafesTeacher.api('teacher_preview',{config:c,regenerate});showPreview(d);$('previewPanel').scrollIntoView({behavior:'smooth'});}catch(e){$('formError').textContent=e.message;$('previewError').textContent=e.message;}finally{busy=false;document.querySelector('.create-button').disabled=false;}}
form.onsubmit=e=>{e.preventDefault();makePreview();};$('regenerate').onclick=()=>makePreview(true);
$('previewQuestions').onclick=async e=>{const b=e.target.closest('[data-replace]');if(!b||busy)return;busy=true;b.disabled=true;try{showPreview(await NafesTeacher.api('teacher_replace',{draft_id:draft.draft_id,question_id:b.dataset.replace}));$('previewError').textContent='تم تبديل السؤال من المؤشر نفسه.';}catch(e){$('previewError').textContent=e.message;}finally{busy=false;b.disabled=false;}};
$('publish').onclick=async()=>{if(!draft||busy)return;busy=true;$('publish').disabled=true;$('previewError').textContent='';try{const d=await NafesTeacher.api('teacher_publish',{draft_id:draft.draft_id});$('createdLink').value=d.url;$('openLink').href=d.url;$('analysisLink').href='analysis.html?test='+encodeURIComponent(d.id);$('createdSummary').textContent=d.title;$('created').classList.remove('hidden');draft=null;await NafesQR.render($('qr'),d.url);$('created').scrollIntoView({behavior:'smooth'});}catch(e){$('previewError').textContent=e.message;if(draft)$('publish').disabled=false;}finally{busy=false;}};
$('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText($('createdLink').value);$('copyLink').textContent='تم النسخ';}catch(_){$('createdLink').select();document.execCommand('copy');$('copyLink').textContent='تم تحديد الرابط للنسخ';}};
for(const [id,method]of [['downloadQr','download'],['printQr','print']])$(id).onclick=()=>{try{NafesQR[method]($('qr'),method==='print'?$('createdSummary').textContent:'nafes-qr.png');}catch(e){$('previewError').textContent=e.message;}};
document.querySelectorAll('[name=identity]').forEach(x=>x.onchange=()=>{$('rosterBox').classList.toggle('hidden',document.querySelector('[name=identity]:checked').value!=='list');});
document.querySelectorAll('[name=testType]').forEach(x=>x.onchange=()=>{if(x.checked&&x.value==='single')rows().forEach((r,i)=>r.querySelector('.enabled').checked=i===0);selectPanels();});
rows().forEach(r=>r.querySelector('.enabled').onchange=selectPanels);$('countMode').onchange=toggleCounts;
$('selectionPanels').oninput=e=>{if(e.target.matches('.indicator-search')){const q=e.target.value.trim();e.target.closest('.selection-panel').querySelectorAll('.indicator-option').forEach(x=>x.hidden=!x.textContent.includes(q));}const p=e.target.closest('.selection-panel');if(p?.querySelector('.selection-summary'))p.querySelector('.selection-summary').textContent=`تم اختيار ${ar(p.querySelectorAll('.indicator-check:checked').length)} مؤشرًا`;};
$('allowBack').onchange=()=>{if(!$('allowBack').checked)$('onePerPage').checked=true;};form.addEventListener('input',saveDraft);
async function load(){if(!NafesTeacher.getKey()){NafesTeacher.requireKey();$('catalogState').textContent='ادخل بمفتاح المعلم لتكوين الاختبارات وإدارة النتائج.';return;}$('catalogState').textContent='جارٍ تحميل المؤشرات ونماذج المحاكاة…';try{catalog=await NafesTeacher.api('teacher_catalog');$('catalogState').textContent=`${ar(catalog.indicators.length)} مؤشرًا · ${ar(catalog.forms.filter(f=>f.ready).length)} محاكاة جاهزة من أصل ١٨٠`;
 if(!initialized){const p=new URLSearchParams(location.search);if(p.has('s')&&p.has('o')&&p.has('i')){document.querySelector('[name=testType][value=custom]').checked=true;rows().forEach(r=>{r.querySelector('.enabled').checked=r.dataset.subject===p.get('s');r.querySelector('.count').value=15;});$('fixedModel').value=p.get('m')||'';}selectPanels();if(p.has('s')){const key=`${p.get('s')}:${p.get('o')}:i${Number(p.get('i'))}`;const input=[...document.querySelectorAll('.indicator-check')].find(x=>x.value===key);if(input)input.checked=true;const entry=catalog.indicators.find(i=>i.key===key);if(entry)$('testTitle').value=`اختبار ${names[entry.subject]} — المؤشر ${p.get('i')}`;}initialized=true;}}catch(e){$('catalogState').textContent=e.message;}}
addEventListener('nafes:auth-changed',e=>{if(e.detail.authenticated)load();});
$('rosterImage').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;$('ocrState').textContent='جارٍ قراءة الأسماء من الصورة...';try{if(!window.Tesseract){await new Promise((ok,bad)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=ok;s.onerror=bad;document.head.appendChild(s)})}const result=await window.Tesseract.recognize(file,'ara+eng');const lines=String(result.data.text||'').split(/\r?\n/).map(x=>x.replace(/^\s*[\d٠-٩]+[.)،-]?\s*/,'').trim()).filter(x=>x.length>=5&&/[\u0600-\u06ff]/.test(x));$('roster').value=[...new Set(lines)].join('\n');$('ocrState').textContent=`تمت قراءة ${lines.length} سطرًا. راجع الأسماء وعدّلها قبل إنشاء الاختبار.`;saveDraft()}catch(_){$('ocrState').textContent='تعذرت القراءة الآلية. يمكنك لصق الأسماء يدويًا في المربع.'}});restore();load();
})();
