(()=>{
const EDGE='https://udznpifopbnrcgxtpzza.supabase.co/functions/v1/nafes-exam';
const qs=new URLSearchParams(location.search);const P={subject:qs.get('s')||'',outcome:qs.get('o')||'',indicator:Number(qs.get('i')||0),model:Number(qs.get('m')||0)};
const SUBJECTS=[window.NAFES_READING,window.NAFES_MATH,window.NAFES_SCIENCE].filter(Boolean);const subj=SUBJECTS.find(s=>s.key===P.subject),out=subj?.outcomes?.find(o=>o.code===P.outcome),indicatorText=out?.indicators?.[P.indicator-1]||'';
const $=id=>document.getElementById(id);const letters=['أ','ب','ج','د'];let attempt=null,questions=[],answers={},current=0,timerId=null,saving=false,finishing=false;
const code=()=>`N3-${({reading:'R',math:'M',science:'S'}[P.subject]||'X')}-${String(P.outcome).replace(/[^0-9A-Za-z]/g,'')}-I${String(P.indicator).padStart(2,'0')}-M${String(P.model).padStart(2,'0')}`;
$('modelCode').textContent=code();$('examTitle').textContent=subj?`${subj.title} · اختبار ${String(P.model).padStart(2,'0')}`:'اختبار نافس';$('indicatorText').textContent=indicatorText||'تعذر تحديد المؤشر من الرابط.';
async function call(body){const r=await fetch(EDGE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...P,...body})});const d=await r.json().catch(()=>({error:'تعذر قراءة استجابة الخادم'}));if(!r.ok)throw new Error(d.error||'تعذر تنفيذ الطلب');return d}
function readiness(type,text){$('readiness').className='readiness '+type;$('readiness').textContent=text}
async function init(){if(!subj||!out||!indicatorText||P.model<1||P.model>30){readiness('bad','رابط الاختبار غير صحيح.');return}try{const p=await call({action:'preview'});if(!p.ready){readiness('bad',`هذا الاختبار لم يُفتح للطلاب بعد. بنك المؤشر يحتوي ${p.approved||0} سؤالًا معتمدًا، ويحتاج إلى ${p.required||24} سؤالًا على الأقل لضمان نماذج مختلفة.`);return}readiness('good',`الاختبار جاهز · ${p.settings.question_count||9} أسئلة · ${p.settings.duration_minutes||20} دقيقة · يحصل كل طالب على نموذج مختلف من بنك المؤشر.`);$('startForm').classList.remove('hidden');const saved=JSON.parse(localStorage.getItem('nafes_student')||'{}');$('studentName').value=saved.name||'';$('studentNo').value=saved.no||''}catch(e){readiness('bad',e.message||'تعذر الاتصال بمحرك الاختبار.')}}
$('startForm').addEventListener('submit',async e=>{e.preventDefault();const name=$('studentName').value.trim(),no=$('studentNo').value.trim();if(!name||!no)return;localStorage.setItem('nafes_student',JSON.stringify({name,no}));const btn=e.submitter;btn.disabled=true;btn.textContent='جارٍ تجهيز نموذجك...';try{const d=await call({action:'start',student_name:name,student_no:no});attempt=d.attempt_id;questions=d.questions||[];answers=d.answers||{};if(d.submitted){showResult(d.percent,d.score,questions.length,'تم تسليم هذه المحاولة سابقًا.');return}if(d.expired){showResult(d.percent||0,d.score||0,questions.length,'انتهى وقت هذه المحاولة.');return}$('intro').classList.add('hidden');$('examArea').classList.remove('hidden');current=0;render();startTimer(d.expires_at)}catch(err){readiness('bad',err.message);btn.disabled=false;btn.textContent='ابدأ الاختبار'}});
function render(){if(!questions.length)return;const q=questions[current];$('questionMeta').textContent=`السؤال ${current+1} من ${questions.length}`;$('questionTitle').textContent=out?.title||'مؤشر نافس';$('progress').innerHTML=questions.map((x,i)=>`<button type="button" data-i="${i}" class="${i===current?'current ':''}${answers[x.id]!==undefined?'done':''}">${i+1}</button>`).join('');$('progress').querySelectorAll('button').forEach(b=>b.onclick=()=>{current=Number(b.dataset.i);render()});$('questionCard').innerHTML=`${q.context?`<div class="context">${escapeHtml(q.context)}</div>`:''}<div class="stem">${escapeHtml(q.question)}</div><div class="choices">${q.options.map((x,i)=>`<label class="choice ${Number(answers[q.id])===i?'selected':''}"><input type="radio" name="q" value="${i}" ${Number(answers[q.id])===i?'checked':''}><span class="letter">${letters[i]}</span><span class="text">${escapeHtml(x)}</span></label>`).join('')}</div>`;$('questionCard').querySelectorAll('input').forEach(inp=>inp.onchange=()=>{answers[q.id]=Number(inp.value);render();saveSoon()});$('prevBtn').disabled=current===0;$('nextBtn').disabled=current===questions.length-1;$('prevBtn').onclick=()=>{if(current>0){current--;render()}};$('nextBtn').onclick=()=>{if(current<questions.length-1){current++;render()}};$('reviewBtn').onclick=showReview}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
let saveTimer=null;function saveSoon(){clearTimeout(saveTimer);saveTimer=setTimeout(saveAnswers,500)}async function saveAnswers(){if(!attempt||saving||finishing)return;saving=true;saveState('يتم حفظ إجاباتك...');try{await call({action:'save',attempt_id:attempt,student_name:$('studentName').value.trim(),student_no:$('studentNo').value.trim(),answers});saveState('تم الحفظ')}catch(_){saveState('تعذر الحفظ — سيعاد تلقائيًا')}finally{saving=false}}
function saveState(t){let x=$('saveState');if(!x){x=document.createElement('div');x.id='saveState';x.className='save-state';document.body.appendChild(x)}x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1200)}
function showReview(){const done=questions.filter(q=>answers[q.id]!==undefined).length;$('questionCard').innerHTML=`<div class="review-panel"><b>مراجعة قبل التسليم</b><p>أجبت عن ${done} من ${questions.length} أسئلة.</p><div class="review-grid">${questions.map((q,i)=>`<button type="button" class="${answers[q.id]!==undefined?'done':''}" data-i="${i}">السؤال ${i+1} · ${answers[q.id]!==undefined?'تمت الإجابة':'بدون إجابة'}</button>`).join('')}</div><div class="submit-row"><button type="button" id="backToQ">العودة للأسئلة</button><button type="button" class="submit" id="submitExam">تسليم الاختبار</button></div></div>`;$('questionCard').querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{current=Number(b.dataset.i);render()});$('backToQ').onclick=render;$('submitExam').onclick=()=>finish(false)}
async function finish(auto){if(finishing)return;if(!auto&&!confirm('هل تريد تسليم الاختبار نهائيًا؟'))return;finishing=true;clearInterval(timerId);try{const d=await call({action:'finish',attempt_id:attempt,student_name:$('studentName').value.trim(),student_no:$('studentNo').value.trim(),answers});showResult(d.percent,d.score,d.total,auto?'انتهى الوقت وتم تسليم الإجابات المحفوظة تلقائيًا.':'تم تسليم الاختبار بنجاح.')}catch(e){finishing=false;alert(e.message);if(!auto)startTimer(new Date(Date.now()+60000).toISOString())}}
function showResult(percent,score,total,msg){$('intro').classList.add('hidden');$('examArea').classList.add('hidden');$('result').classList.remove('hidden');$('result').innerHTML=`<span class="kicker">النتيجة</span><div class="result-score"><b>${Math.round(Number(percent||0))}%</b></div><h2>${score??0} من ${total||questions.length}</h2><p>${escapeHtml(msg||'تم حفظ نتيجتك.')}</p><p>الاختبار يقيس مؤشرًا واحدًا حتى تكون نتيجة المهارة واضحة ومباشرة.</p>`}
function startTimer(expiresAt){clearInterval(timerId);const end=new Date(expiresAt).getTime();const tick=()=>{const ms=end-Date.now();if(ms<=0){$('timer').textContent='00:00';clearInterval(timerId);finish(true);return}const sec=Math.floor(ms/1000),m=Math.floor(sec/60),s=sec%60;$('timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('timer').className='timer'+(sec<=60?' danger':sec<=300?' warn':'')};tick();timerId=setInterval(tick,1000)}
window.addEventListener('beforeunload',()=>{if(attempt&&!finishing){try{navigator.sendBeacon?.(EDGE,new Blob([JSON.stringify({...P,action:'save',attempt_id:attempt,student_name:$('studentName').value.trim(),student_no:$('studentNo').value.trim(),answers})],{type:'application/json'}))}catch(_){}}});
init();
})();