(()=>{
'use strict';
const AUTH_EDGE='https://udznpifopbnrcgxtpzza.supabase.co/functions/v1/lugati-auth';
const DATA_EDGE='https://udznpifopbnrcgxtpzza.supabase.co/functions/v1/lugati-moallimi-read';
const CONTENT_EDGE='https://udznpifopbnrcgxtpzza.supabase.co/functions/v1/lugati-content';
const SESSION_KEY='lugati_session_v1';
const SUBJECTS={reading:'القراءة',math:'الرياضيات',science:'العلوم',arabic:'لغتي'};
const MODULES={
  lesson:{title:'الدروس التفاعلية',eyebrow:'التعلّم',icon:'▣',description:'أنشئ درسًا فعليًا، حدّد المادة والفصل، ثم انشره ليظهر للطلاب.'},
  strategy:{title:'الاستراتيجيات التعليمية',eyebrow:'التدريس',icon:'◈',description:'احفظ استراتيجية الدرس وخطوات تنفيذها حتى تكون جاهزة للاستخدام والمتابعة.'},
  game:{title:'الألعاب التعليمية',eyebrow:'التعلم باللعب',icon:'✺',description:'أنشئ نشاطًا أو تحديًا تعليميًا، وانشر التعليمات للطلاب ليتمكنوا من تنفيذ النشاط.'},
  worksheet:{title:'أوراق العمل',eyebrow:'التدريب',icon:'▤',description:'أنشئ ورقة عمل علاجية أو تعزيزية أو إثرائية وانشرها للفصل المستهدف.'},
  assignment:{title:'الواجبات',eyebrow:'التكليف',icon:'✓',description:'أنشئ واجبًا بموعد تسليم، ويتلقى الطالب التكليف ويرسل إجابته داخل المنصة.'},
  assessment:{title:'التقويم',eyebrow:'القياس',icon:'◎',description:'أنشئ نشاطًا تقويميًا تشخيصيًا أو تكوينيًا أو ختاميًا، ويتلقى الطالب المهمة ويسلّم استجابته.'}
};
let role='',profile={},currentKind='',currentItems=[];
const $=id=>document.getElementById(id);
function token(){for(const s of [sessionStorage,localStorage]){try{const t=s.getItem(SESSION_KEY);if(t)return t}catch(_){}}return''}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function subjectLabel(k){return SUBJECTS[k]||'غير محدد'}
function arNum(v,d=0){if(v===null||v===undefined||Number.isNaN(Number(v)))return'—';return Number(v).toLocaleString('ar-SA',{minimumFractionDigits:d,maximumFractionDigits:d})}
function pct(v){return v===null||v===undefined?'—':`${arNum(v,1)}٪`}
function fmtDate(v){if(!v)return'—';try{return new Intl.DateTimeFormat('ar-SA',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch(_){return'—'}}
async function post(url,body){const t=token();if(!t)throw new Error('جلسة الدخول غير موجودة.');const c=new AbortController(),timer=setTimeout(()=>c.abort(),20000);try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`},body:JSON.stringify(body),cache:'no-store',signal:c.signal});const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw new Error(d.error||'تعذر إتمام العملية.');return d}finally{clearTimeout(timer)}}
function toast(text){const el=$('toast');if(!el)return;el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3000)}
function scrollToId(id){const el=$(id);if(el){el.scrollIntoView({behavior:'smooth',block:'start'});document.body.classList.remove('sidebar-open')}}
function openModal(html){$('modalBody').innerHTML=html;$('contentModal').hidden=false;document.body.style.overflow='hidden'}
function closeModal(){$('contentModal').hidden=true;$('modalBody').innerHTML='';document.body.style.overflow=''}
function statusLabel(item){if(role==='student'&&item.progress)return'<span class="module-tag done">تم التسليم</span>';if(item.published)return'<span class="module-tag published">منشور</span>';return'<span class="module-tag draft">مسودة</span>'}
function modulePreview(item){const text=item?.body?.text||item?.body?.instructions||'';return text?escapeHtml(text):'لا يوجد وصف إضافي.'}
async function openModule(kind){
  if(!MODULES[kind])return;currentKind=kind;const cfg=MODULES[kind];$('workspace').hidden=false;$('moduleEyebrow').textContent=cfg.eyebrow;$('moduleTitle').textContent=cfg.title;$('moduleDescription').textContent=cfg.description;$('moduleSubjectFilter').value='';
  if($('addContentBtn'))$('addContentBtn').hidden=role!=='teacher';$('moduleContent').innerHTML='<div class="module-empty">جارٍ تحميل القسم...</div>';scrollToId('workspace');
  try{const d=await post(CONTENT_EDGE,{action:'list',kind});currentItems=d.items||[];renderModuleItems()}catch(err){$('moduleContent').innerHTML=`<div class="module-empty"><b>تعذر تحميل القسم</b>${escapeHtml(err.message)}</div>`}
}
function renderModuleItems(){const filter=$('moduleSubjectFilter').value;const items=currentItems.filter(x=>!filter||x.subject_key===filter);if(!items.length){$('moduleContent').innerHTML=`<div class="module-empty"><b>لا توجد عناصر في هذا القسم حتى الآن</b>${role==='teacher'?'اضغط «إضافة جديد» لإنشاء أول عنصر فعلي.':'عندما ينشر المعلم محتوى مخصصًا لك سيظهر هنا.'}</div>`;return}
  $('moduleContent').innerHTML=items.map(item=>`<article class="module-item" data-content-id="${escapeHtml(item.id)}"><div class="module-item-head"><span class="module-item-icon">${MODULES[item.kind]?.icon||'•'}</span><div><h3>${escapeHtml(item.title)}</h3><div class="module-item-meta">${statusLabel(item)}${item.subject_key?`<span class="module-tag">${subjectLabel(item.subject_key)}</span>`:''}${item.class_name?`<span class="module-tag">الفصل ${escapeHtml(item.class_name)}</span>`:''}${item.due_at?`<span class="module-tag">التسليم ${fmtDate(item.due_at)}</span>`:''}</div></div></div><div class="module-preview">${modulePreview(item)}</div><div class="module-item-actions"><button class="module-btn primary" data-open-content="${escapeHtml(item.id)}">فتح</button>${role==='teacher'?`<button class="module-btn" data-edit-content="${escapeHtml(item.id)}">تعديل</button><button class="module-btn danger" data-delete-content="${escapeHtml(item.id)}">حذف</button>`:''}</div></article>`).join('');
  document.querySelectorAll('[data-open-content]').forEach(b=>b.onclick=()=>showContent(b.dataset.openContent));document.querySelectorAll('[data-edit-content]').forEach(b=>b.onclick=()=>editContent(b.dataset.editContent));document.querySelectorAll('[data-delete-content]').forEach(b=>b.onclick=()=>deleteContent(b.dataset.deleteContent));
}
function subjectOptions(selected=''){return`<option value="">عام</option>${Object.entries(SUBJECTS).map(([k,v])=>`<option value="${k}" ${selected===k?'selected':''}>${v}</option>`).join('')}`}
function showEditor(item=null){const cfg=MODULES[currentKind]||MODULES.lesson;const due=item?.due_at?new Date(item.due_at).toISOString().slice(0,16):'';openModal(`<div class="modal-heading"><small>${cfg.eyebrow}</small><h2 id="modalTitle">${item?'تعديل':'إضافة'} ${cfg.title}</h2><p>يحفظ هذا المحتوى في قاعدة «لغتي» المستقلة، ولا يعدّل بيانات منصة معلّمي.</p></div><form id="moduleEditor" class="module-form"><label>العنوان<input id="contentTitle" required minlength="2" value="${escapeHtml(item?.title||'')}"></label><label>المادة<select id="contentSubject">${subjectOptions(item?.subject_key||'')}</select></label><label>الصف<input id="contentGrade" placeholder="مثال: ثالث متوسط" value="${escapeHtml(item?.grade||'')}"></label><label>الفصل<input id="contentClass" placeholder="اتركه فارغًا لجميع الفصول" value="${escapeHtml(item?.class_name||'')}"></label><label class="full">المحتوى<textarea id="contentText" placeholder="اكتب شرح الدرس أو النشاط أو ورقة العمل...">${escapeHtml(item?.body?.text||'')}</textarea></label><label class="full">تعليمات التنفيذ<textarea id="contentInstructions" placeholder="تعليمات واضحة للطالب...">${escapeHtml(item?.body?.instructions||'')}</textarea></label><label>موعد التسليم<input id="contentDue" type="datetime-local" value="${due}"></label><label class="publish-row"><input id="contentPublished" type="checkbox" ${item?.published?'checked':''}><span>نشر للطلاب مباشرة</span></label><div class="form-actions"><button class="save-btn" type="submit">حفظ</button><button class="cancel-btn" type="button" data-close-modal>إلغاء</button></div></form>`);$('moduleEditor').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('.save-btn');btn.disabled=true;btn.textContent='جارٍ الحفظ...';try{const payload={action:item?'update':'create',id:item?.id,kind:currentKind,title:$('contentTitle').value,subject_key:$('contentSubject').value,grade:$('contentGrade').value,class_name:$('contentClass').value,body:{text:$('contentText').value,instructions:$('contentInstructions').value},due_at:$('contentDue').value,published:$('contentPublished').checked};await post(CONTENT_EDGE,payload);closeModal();toast('تم الحفظ بنجاح.');await openModule(currentKind)}catch(err){toast(err.message||'تعذر الحفظ.');btn.disabled=false;btn.textContent='حفظ'}};wireModalClose()}
function editContent(id){const item=currentItems.find(x=>String(x.id)===String(id));if(item)showEditor(item)}
async function deleteContent(id){const item=currentItems.find(x=>String(x.id)===String(id));if(!item)return;if(!confirm(`حذف «${item.title}»؟`))return;try{await post(CONTENT_EDGE,{action:'delete',id});toast('تم الحذف.');await openModule(currentKind)}catch(err){toast(err.message||'تعذر الحذف.') }}
function showContent(id){const item=currentItems.find(x=>String(x.id)===String(id));if(!item)return;const cfg=MODULES[item.kind]||MODULES.lesson;const responseNeeded=['worksheet','assignment','assessment'].includes(item.kind);const studentArea=role==='student'?`<div class="student-response"><h3>${responseNeeded?'إجابتك / تسليمك':'إتمام النشاط'}</h3>${responseNeeded?`<textarea id="studentResponse" placeholder="اكتب إجابتك أو ملاحظتك هنا...">${escapeHtml(item.progress?.response?.text||'')}</textarea>`:''}<button id="submitContentBtn">${item.progress?'تحديث التسليم':responseNeeded?'تسليم':'تم الإنجاز'}</button></div>`:'';openModal(`<div class="modal-heading"><small>${cfg.title}</small><h2 id="modalTitle">${escapeHtml(item.title)}</h2><p>${item.subject_key?subjectLabel(item.subject_key):'عام'}${item.class_name?` · الفصل ${escapeHtml(item.class_name)}`:''}${item.due_at?` · موعد التسليم ${fmtDate(item.due_at)}`:''}</p></div><div class="detail-meta">${statusLabel(item)}${item.grade?`<span class="module-tag">${escapeHtml(item.grade)}</span>`:''}</div><div class="detail-body">${escapeHtml(item.body?.text||'لا يوجد محتوى نصي.').replace(/\n/g,'<br>')}</div>${item.body?.instructions?`<div class="detail-instructions"><b>تعليمات التنفيذ</b><br>${escapeHtml(item.body.instructions).replace(/\n/g,'<br>')}</div>`:''}${studentArea}`);if(role==='student'&&$('submitContentBtn'))$('submitContentBtn').onclick=async()=>{const btn=$('submitContentBtn');btn.disabled=true;btn.textContent='جارٍ الحفظ...';try{await post(CONTENT_EDGE,{action:'submit',content_id:item.id,response_text:responseNeeded?($('studentResponse')?.value||''):'',status:'submitted'});toast('تم تسجيل إنجازك.');closeModal();await openModule(currentKind)}catch(err){toast(err.message||'تعذر التسليم.');btn.disabled=false;btn.textContent='إعادة المحاولة'}};wireModalClose()}
function wireModalClose(){document.querySelectorAll('[data-close-modal]').forEach(el=>el.onclick=closeModal)}
async function showPlanRoute(route){scrollToId('support');const title={remedial:'الطلاب والنتائج في المسار العلاجي',strengthen:'الطلاب والنتائج في مسار التعزيز',enrich:'الطلاب والنتائج في المسار الإثرائي'}[route];$('supportPanelTitle').textContent=title;$('supportContent').innerHTML='<div class="empty-state">جارٍ تحميل النتائج...</div>';try{const d=await post(DATA_EDGE,{action:'grades',limit:1000});const latest=new Map();for(const r of d.rows||[]){if(!r.student_id||!r.subject_key)continue;const key=`${r.student_id}::${r.subject_key}`;if(!latest.has(key))latest.set(key,r)}let rows=[...latest.values()];rows=rows.filter(r=>route==='remedial'?Number(r.percent)<70:route==='strengthen'?Number(r.percent)>=70&&Number(r.percent)<90:Number(r.percent)>=90);rows.sort((a,b)=>route==='enrich'?Number(b.percent)-Number(a.percent):Number(a.percent)-Number(b.percent));renderStudentRows(rows.slice(0,100),title)}catch(err){$('supportContent').innerHTML=`<div class="empty-state">${escapeHtml(err.message)}</div>`}}
function renderStudentRows(rows,title){if(!rows.length){$('supportContent').innerHTML='<div class="empty-state good">لا توجد نتائج ضمن هذا المسار حاليًا.</div>';return}$('supportPanelTitle').textContent=title;$('supportContent').innerHTML=`<div class="table-wrap"><table><thead><tr><th>الطالب</th><th>الفصل</th><th>المادة</th><th>النسبة</th><th>عرض الملف</th></tr></thead><tbody>${rows.map(r=>`<tr class="clickable-row" data-profile-student="${escapeHtml(r.student_id)}" data-profile-name="${escapeHtml(r.student_name||'طالب')}"><td><b>${escapeHtml(r.student_name||'غير مسجل')}</b></td><td>${escapeHtml(r.class_name||'—')}</td><td>${subjectLabel(r.subject_key)}</td><td><b>${pct(r.percent)}</b></td><td>فتح</td></tr>`).join('')}</tbody></table></div>`;document.querySelectorAll('[data-profile-student]').forEach(row=>row.onclick=()=>openStudentProfile(row.dataset.profileStudent,row.dataset.profileName))}
async function showStudentFiles(){scrollToId('support');$('supportPanelTitle').textContent='ملفات الطلاب';$('supportContent').innerHTML='<div class="empty-state">جارٍ تحميل ملفات الطلاب...</div>';try{const d=await post(DATA_EDGE,{action:'grades',limit:1000});const byStudent=new Map();for(const r of d.rows||[]){if(!r.student_id)continue;if(!byStudent.has(r.student_id))byStudent.set(r.student_id,{student_id:r.student_id,student_name:r.student_name,class_name:r.class_name,latest:new Map()});const s=byStudent.get(r.student_id);if(r.subject_key&&!s.latest.has(r.subject_key))s.latest.set(r.subject_key,r)}const rows=[...byStudent.values()].sort((a,b)=>String(a.student_name||'').localeCompare(String(b.student_name||''),'ar'));$('supportContent').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>الطالب</th><th>الفصل</th><th>القراءة</th><th>الرياضيات</th><th>العلوم</th><th>الملف</th></tr></thead><tbody>${rows.map(s=>`<tr class="clickable-row" data-profile-student="${escapeHtml(s.student_id)}" data-profile-name="${escapeHtml(s.student_name||'طالب')}"><td><b>${escapeHtml(s.student_name||'غير مسجل')}</b></td><td>${escapeHtml(s.class_name||'—')}</td><td>${pct(s.latest.get('reading')?.percent)}</td><td>${pct(s.latest.get('math')?.percent)}</td><td>${pct(s.latest.get('science')?.percent)}</td><td>فتح</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">لا توجد نتائج طلاب متاحة حاليًا.</div>';document.querySelectorAll('[data-profile-student]').forEach(row=>row.onclick=()=>openStudentProfile(row.dataset.profileStudent,row.dataset.profileName))}catch(err){$('supportContent').innerHTML=`<div class="empty-state">${escapeHtml(err.message)}</div>`}}
async function openStudentProfile(studentId,name){openModal('<div class="modal-heading"><small>ملف الطالب</small><h2 id="modalTitle">جارٍ تحميل الملف...</h2></div>');try{const d=await post(DATA_EDGE,{action:'grades',student_id:studentId,limit:1000});const rows=d.rows||[],latest=new Map();for(const r of rows)if(r.subject_key&&!latest.has(r.subject_key))latest.set(r.subject_key,r);const avg=[...latest.values()].length?[...latest.values()].reduce((a,r)=>a+Number(r.percent||0),0)/latest.size:null;const student=rows[0]||{};$('modalBody').innerHTML=`<div class="modal-heading"><small>ملف الطالب الفعلي</small><h2 id="modalTitle">${escapeHtml(name||student.student_name||'طالب')}</h2><p>${escapeHtml(student.class_name?`الفصل ${student.class_name}`:'')}</p></div><div class="student-profile-summary"><div class="student-profile-stat"><b>${pct(avg)}</b><span>متوسط أحدث المواد</span></div><div class="student-profile-stat"><b>${arNum(rows.length)}</b><span>نتائج مسجلة</span></div><div class="student-profile-stat"><b>${arNum([...latest.values()].filter(r=>Number(r.percent)<70).length)}</b><span>مواد تحتاج دعمًا</span></div></div><div class="table-wrap"><table><thead><tr><th>المادة</th><th>الدرجة</th><th>النسبة</th><th>التاريخ</th></tr></thead><tbody>${rows.slice(0,30).map(r=>`<tr><td>${subjectLabel(r.subject_key)}</td><td>${arNum(r.score)} / ${arNum(r.total)}</td><td><b>${pct(r.percent)}</b></td><td>${fmtDate(r.submitted_at)}</td></tr>`).join('')}</tbody></table></div>`;wireModalClose()}catch(err){$('modalBody').innerHTML=`<div class="modal-heading"><h2 id="modalTitle">تعذر تحميل ملف الطالب</h2><p>${escapeHtml(err.message)}</p></div>`}}
async function printSummaryReport(){toast('جارٍ تجهيز التقرير...');try{const [s,g]=await Promise.all([post(DATA_EDGE,{action:'summary'}),post(DATA_EDGE,{action:'grades',limit:1000})]);const win=window.open('','_blank');if(!win){toast('اسمح بالنوافذ المنبثقة لطباعة التقرير.');return}const subs=s.subjects||{};const support=(s.needing_support||[]);win.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>تقرير منصة لغتي</title><style>body{font-family:Tahoma,Arial,sans-serif;margin:32px;color:#18342e}h1{font-size:22px}h2{font-size:16px;margin-top:26px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border:1px solid #ccd9d5;padding:8px;text-align:right}th{background:#eef6f3}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.card{border:1px solid #ccd9d5;border-radius:10px;padding:12px}.card b{font-size:20px;color:#087f68}@media print{button{display:none}}</style></head><body><h1>منصة لغتي التفاعلية — التقرير العام</h1><p>تاريخ الطباعة: ${new Date().toLocaleString('ar-SA')}</p><div class="cards">${['reading','math','science'].map(k=>`<div class="card"><strong>${subjectLabel(k)}</strong><br><b>${pct(subs[k]?.average_percent)}</b><br>طلاب في أحدث قياس: ${arNum(subs[k]?.latest_students)}</div>`).join('')}</div><h2>الطلاب الأكثر حاجة إلى دعم</h2><table><thead><tr><th>الطالب</th><th>الفصل</th><th>المادة</th><th>النسبة</th></tr></thead><tbody>${support.map(r=>`<tr><td>${escapeHtml(r.student_name||'')}</td><td>${escapeHtml(r.class_name||'')}</td><td>${subjectLabel(r.subject_key)}</td><td>${pct(r.percent)}</td></tr>`).join('')}</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>`);win.document.close()}catch(err){toast(err.message||'تعذر تجهيز التقرير.')}}
async function downloadCsv(){toast('جارٍ تجهيز ملف النتائج...');try{const d=await post(DATA_EDGE,{action:'grades',limit:1000});const rows=d.rows||[];const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;const csv='\ufeff'+[['الطالب','الفصل','المادة','الدرجة','الإجمالي','النسبة','التاريخ'],...rows.map(r=>[r.student_name||'',r.class_name||'',subjectLabel(r.subject_key),r.score,r.total,r.percent,r.submitted_at||''])].map(row=>row.map(q).join(',')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`lugati-results-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);toast('تم تجهيز ملف النتائج.')}catch(err){toast(err.message||'تعذر التصدير.')}}
async function init(){wireModalClose();try{const d=await post(AUTH_EDGE,{action:'verify'});role=d.role;profile=d.profile||{}}catch(_){return}document.querySelectorAll('[data-module]').forEach(btn=>btn.addEventListener('click',()=>openModule(btn.dataset.module)));$('addContentBtn')?.addEventListener('click',()=>showEditor());$('moduleSubjectFilter')?.addEventListener('change',renderModuleItems);document.querySelectorAll('[data-action="student-files"]').forEach(btn=>btn.addEventListener('click',showStudentFiles));document.querySelectorAll('[data-action="reports"]').forEach(btn=>btn.addEventListener('click',()=>scrollToId('reports')));document.querySelectorAll('[data-plan-route]').forEach(card=>card.addEventListener('click',()=>showPlanRoute(card.dataset.planRoute)));$('printSummaryReport')?.addEventListener('click',printSummaryReport);$('downloadResultsCsv')?.addEventListener('click',downloadCsv);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('contentModal').hidden)closeModal()});}
init();
})();