(()=>{
const NAFES_SUBJECTS=['arabic','math','science'];
const NAFES_FRAMEWORK={
 arabic:{title:'القراءة — لغتي الخالدة',icon:'ق',soft:'#e4f1ee',color:'#0f514c',goals:[
  {domain:'اكتساب المفردات وتوظيف الدلالات اللفظية',outcome:'استنتاج دلالات المفردات وتصنيفها وتوظيفها في سياقات جديدة.',indicators:['يستنتج معاني المفردات من الترادف والتضاد والسياق والتعريف والتفسير.','يصنف المفردات وفق دلالاتها والعلاقات بينها.','يستنتج المصطلحات الجديدة الواردة في النص.','يوظف المفردات في سياقات ومواقف جديدة.']},
  {domain:'الفهم القرائي وتحليل النص',outcome:'فهم النص وتحليل أفكاره ومعلوماته والعلاقات بين أجزائه.',indicators:['يستخرج الأفكار الرئيسة والفرعية.','يستنتج الأفكار الضمنية والمعلومات غير المباشرة.','يفسر المعلومات ويحللها ويستدل عليها من النص.','يربط بين الأفكار والعلاقات الواردة في النص ويقارن بينها.']},
  {domain:'التقويم والنقد وإبداء الرأي',outcome:'تقويم النص ونقده وبناء الرأي المدعوم بالأدلة.',indicators:['يقوّم النص وينقد أفكاره وأدلته.','يبدي رأيه في وجهة نظر الكاتب مع التعليل.','يقترح البدائل والحلول المناسبة استنادًا إلى معطيات النص.','يستخدم أساليب الإقناع والتحليل في مناقشة الأفكار.','يلخص النص ويوظف معطياته في مواقف حياتية جديدة.']}
 ]},
 math:{title:'الرياضيات',icon:'∑',soft:'#f6eddf',color:'#986a25',goals:[
  {domain:'الأعداد والعمليات عليها',outcome:'فهم الأعداد والعلاقات العددية وتوظيف العمليات في حل المشكلات.',indicators:['يصف الأعداد الصحيحة والنسبية ويمثلها ويقارن بينها ويرتبها.','يجري العمليات على الأعداد النسبية والجذور ويستخدم قوانين الأسس وترتيب العمليات.','يحسب النسب والنسب المئوية ويستخدمها في مواقف حياتية.','يحل مسائل رياضية متعددة الخطوات تتضمن الأعداد والعمليات ويفسر الحل.']},
  {domain:'الجبر والعلاقات والأنماط',outcome:'تمثيل العلاقات الجبرية وكتابة المعادلات والمتباينات والدوال وتحليلها.',indicators:['يكتب معادلات خطية ويحلها جبريًا وبيانيًا ويفسر المقطعين السيني والصادي.','يحل المعادلات التربيعية بطرائق مناسبة ويحدد عدد الجذور.','يكتب نظام معادلتين خطيتين بمتغيرين ويحلّه جبريًا وبيانيًا.','يحل المتباينات الخطية والمركبة ومتباينات القيمة المطلقة ويمثل الحل.','يميز الدوال الخطية والتربيعية ويقرأ خصائصها من القاعدة أو التمثيل البياني.']},
  {domain:'الهندسة والقياس',outcome:'توظيف خصائص الأشكال والتحويلات والقياس في حل المشكلات.',indicators:['يطبق الانعكاس والانسحاب والدوران والتمدد في المستوى الإحداثي.','يصف التمدد ويحدد مركزه ومعامل القياس ويمثل الصورة الناتجة.','يستخدم صيغ المساحات السطحية والحجوم للأشكال ثلاثية الأبعاد والمجسمات المركبة.','يميز العلاقات بين وحدات القياس ويجري التحويلات بينها ويحل مسائل تطبيقية.']},
  {domain:'الإحصاء والاحتمالات',outcome:'جمع البيانات وتمثيلها وتحليلها واستخدام الاحتمال في التنبؤ واتخاذ القرار.',indicators:['يصف الدراسة المسحية ويجمع البيانات وينظمها ويميز أنواع العينات.','يختار التمثيل البياني الأنسب لبيانات معطاة ويبرر اختياره.','يقرأ التمثيلات البيانية المختلفة ويفسرها ويستخدمها في التنبؤ واتخاذ القرارات.','يحسب مقاييس النزعة المركزية والتشتت ويستخدمها في وصف البيانات ومقارنتها.','يحسب الاحتمالات البسيطة ويستخدمها في تفسير مواقف احتمالية.']}
 ]},
 science:{title:'العلوم',icon:'ع',soft:'#edf1e6',color:'#667b33',goals:[
  {domain:'علوم الأرض والفضاء',outcome:'تفسير الظواهر الأرضية والكونية بالاعتماد على البيانات والأدلة.',indicators:['ينظم ويحلل البيانات والمعلومات المتعلقة بالكون والمجرات والمسافات والحركة لتقديم شواهد وأدلة.','يفسر مكونات النظام الأرضي والعلاقات المتبادلة بينها.','يستخدم الأدلة والنماذج لتفسير التغيرات والعمليات التي تحدث على سطح الأرض وفي باطنها.']},
  {domain:'علوم الحياة',outcome:'فهم بناء الكائنات الحية ووظائفها وعلاقاتها واستمرار الحياة.',indicators:['يحدد أعضاء الأجهزة الأساسية في جسم الإنسان ووظائفها ويشرح تكاملها.','يربط بين تركيب الخلية ووظائفها ومستويات التنظيم في المخلوقات الحية.','يفسر انتقال الصفات الوراثية ويستخدم النماذج في تمثيلها.','يحلل العلاقات بين المخلوقات الحية والعوامل البيئية في الأنظمة البيئية.']},
  {domain:'العلوم الفيزيائية',outcome:'تفسير خصائص المادة والتغيرات والطاقة والقوى باستخدام المفاهيم العلمية.',indicators:['يميز خصائص المادة والتغيرات الفيزيائية والكيميائية ويستدل على حدوثها.','يفسر التفاعلات الكيميائية باستخدام الأدلة والمعادلات أو النماذج المناسبة.','يحلل العلاقة بين القوة والحركة ويطبقها في مواقف حياتية.','يفسر تحولات الطاقة وانتقالها ويقارن بين صورها وتطبيقاتها.','يستخدم مفاهيم الكهرباء والمغناطيسية في تفسير الظواهر والتطبيقات.']},
  {domain:'الاستقصاء والممارسات العلمية',outcome:'استخدام مهارات الاستقصاء وتحليل الأدلة للوصول إلى تفسيرات علمية.',indicators:['يحدد سؤالًا قابلًا للاختبار ويختار المتغيرات والأدوات والإجراءات المناسبة.','يقرأ الجداول والرسوم والبيانات التجريبية ويستنتج الأنماط والعلاقات.','يقارن بين الأدلة ويقيّم قوتها ويدعم الاستنتاج العلمي بالمبررات.','يطبق المعرفة العلمية في حل مشكلة أو تفسير موقف جديد.']}
 ]}
};
let nafesSubject='arabic';
const isNafesAssessment=a=>String(a?.title||'').includes('نافس');
const profileFor=(subject)=>state.profiles.find(p=>p.subject_key===subject&&p.grade_level==='الثالث المتوسط');
const nafesTestsFor=(subject)=>{const p=profileFor(subject);return p?state.assessments.filter(a=>a.subject_profile_id===p.id&&isNafesAssessment(a)):[]};
const nafesResultsFor=(subject)=>{const p=profileFor(subject);return p?state.results.filter(r=>r.subject_profile_id===p.id&&String(r.assessment_label||'').includes('نافس')):[]};
function countIndicators(subject){return NAFES_FRAMEWORK[subject].goals.reduce((n,g)=>n+g.indicators.length,0)}

const baseRenderSection=renderSection;
renderSection=function(n){if(n==='nafes')return renderNafes();return baseRenderSection(n)};

renderSubjects=function(){
 const area=$('subjectsArea');if(state.subjectDetail){renderSubjectDetail();return}
 const cards=Object.entries(SUBJECTS).map(([k,s])=>{const ps=state.profiles.filter(p=>p.subject_key===k),tests=state.assessments.filter(a=>ps.some(p=>p.id===a.subject_profile_id)&&!isNafesAssessment(a)),tasks=state.assignments.filter(a=>(a.subject_key||'arabic')===k);return `<button class="subject-card" style="--subject-soft:${s.soft};--subject-color:${s.color}" onclick="openSubject('${k}')"><span class="subject-icon">${s.icon}</span><h3>${s.name}</h3><p>${k==='english'?'تدريب تأسيسي وتدرج حتى الإتقان، مع اختبارات مرتبطة بدروس المرحلة.':'اختبارات وتدريب مرتبط بالدروس والمهارات المنهجية، وتظهر النتائج مباشرة في ملف الطالب.'}</p><div class="mini"><span>${tests.length} اختبار</span><span>${tasks.length} واجب/مشروع</span><span>${k==='english'?'مسار تأسيسي':'مسار منهجي'}</span></div></button>`}).join('');
 area.innerHTML=`<div class="subject-grid">${cards}</div><div class="soft-card" style="margin-top:14px"><b>ملاحظة:</b> تم فصل نافس عن المواد. اختبارات نافس وأهدافه ومؤشراته أصبحت في قسم نافس المستقل.</div>`
};

renderSubjectDetail=function(){
 const area=$('subjectsArea'),s=SUBJECTS[state.subject],p=currentProfile(),tests=state.assessments.filter(a=>a.subject_profile_id===p?.id&&!isNafesAssessment(a)),tasks=state.assignments.filter(a=>(a.subject_key||'arabic')===state.subject&&state.classes.find(c=>c.id===a.class_id)?.grade===state.grade),res=p?state.results.filter(r=>r.subject_profile_id===p.id&&!String(r.assessment_label||'').includes('نافس')):[],students=[...new Set(res.map(r=>r.student_id).filter(Boolean))],avg=res.length?res.reduce((n,r)=>n+(+r.percent||0),0)/res.length:null;
 area.innerHTML=`<div class="subject-back"><button class="btn" onclick="closeSubject()">→ رجوع للمواد</button></div>${gradeTabs('subjectGrade')}<div class="page-head"><div><h2>${s.name} — ${state.grade}</h2><p>${state.subject==='english'?'تدريب تدريجي من التأسيس إلى الإتقان ثم اختبارات الدروس.':'اختبارات مرتبطة بالدروس والمهارات المنهجية، وكل نتيجة ترتبط بالطالب مباشرة.'}</p></div><div class="actions"><button class="btn" onclick="openAssessmentModal()">+ اختبار جديد</button></div></div><div class="metrics"><div class="metric"><span>اختبارات المادة</span><b>${tests.length}</b><small>بدون نافس</small></div><div class="metric"><span>الطلاب المقاسون</span><b>${students.length}</b><small>ظهرت لهم نتائج</small></div><div class="metric"><span>متوسط المادة</span><b>${pct(avg)}</b><small>من القياسات المسجلة</small></div><div class="metric"><span>الواجبات والمشاريع</span><b>${tasks.length}</b><small>مرتبطة بالمادة</small></div></div><div class="card"><h3 style="margin-top:0">مسار الطالب</h3><div class="level-path">${['البداية|تأسيس','أتدرب|توجيه','أتقدم|مستقل','أطبق|سياق جديد','أتقن|قياس إتقان','أتحدى نفسي|إثراء'].map(x=>{const[a,b]=x.split('|');return `<div class="level-step"><b>${a}</b><small>${b}</small></div>`}).join('')}</div></div><div class="card" style="margin-top:12px"><div class="page-head" style="margin-bottom:10px"><div><h2 style="font-size:18px">اختبارات المادة</h2><p>هذه المساحة للاختبارات المنهجية والتأسيسية. اختبارات نافس موجودة في قسم نافس المستقل.</p></div></div><div class="test-list">${tests.map(t=>`<div class="test-row"><div><h4>${esc(t.title)}</h4><p>${assessmentType(t.assessment_type)} · ${t.level_target==='adaptive'?'يتكيف مع مستوى الطالب':t.level_target} · ${t.status==='open'?'مفتوح':'غير مفتوح'}</p></div><div class="actions">${t.access_code?`<span class="test-code">${esc(t.access_code)}</span>`:''}${t.status==='open'?`<button class="btn" onclick="shareTest('${t.id}')">كود / QR</button>`:`<button class="btn primary" onclick="openTest('${t.id}')">فتح للطلاب</button>`}</div></div>`).join('')||'<div class="empty"><b>لا توجد اختبارات منهجية لهذه المادة والمرحلة بعد.</b>أنشئ اختبارًا مرتبطًا بدروس المرحلة.</div>'}</div></div>`
};

window.setNafesSubject=function(k){nafesSubject=k;renderNafes()};
function renderNafes(){
 const area=$('nafesArea');if(!area)return;
 const fw=NAFES_FRAMEWORK[nafesSubject],tests=nafesTestsFor(nafesSubject),results=nafesResultsFor(nafesSubject),students=[...new Set(results.map(r=>r.student_id).filter(Boolean))],avg=results.length?results.reduce((n,r)=>n+(+r.percent||0),0)/results.length:null;
 const cards=NAFES_SUBJECTS.map(k=>{const f=NAFES_FRAMEWORK[k];return `<button class="nafes-subject ${nafesSubject===k?'active':''}" style="--nafes-soft:${f.soft};--nafes-color:${f.color}" onclick="setNafesSubject('${k}')"><span class="icon">${f.icon}</span><h4>${f.title}</h4><p>أهداف نافس ونواتج التعلم والمؤشرات والاختبارات المرتبطة بها.</p><span class="count">${countIndicators(k)} مؤشر</span></button>`}).join('');
 const goals=fw.goals.map((g,i)=>`<section class="nafes-goal"><div class="nafes-goal-head"><div class="nafes-goal-no">${i+1}</div><div><small>${esc(g.domain)}</small><strong>${esc(g.outcome)}</strong></div></div><div class="nafes-indicators"><div class="nafes-indicators-title">المؤشرات</div>${g.indicators.map((x,j)=>`<div class="nafes-indicator"><b>${j+1}</b><span>${esc(x)}</span></div>`).join('')}</div></section>`).join('');
 area.innerHTML=`<section class="nafes-hero"><span class="kicker">الاختبارات الوطنية نافس</span><h3>أهداف نافس ومؤشراته في المواد الثلاث</h3><p>قسم مستقل عن المواد يركز على القراءة والرياضيات والعلوم للصف الثالث المتوسط، ويربط التدريب والاختبار والنتيجة مباشرة بملف الطالب والتحصيل.</p><div class="nafes-flow"><span>الهدف</span><span>المؤشر</span><span>التدريب</span><span>اختبار مختلف لكل طالب</span><span>تحليل النتيجة</span><span>تحديث ملف الطالب</span></div></section><div class="nafes-subjects">${cards}</div><div class="metrics"><div class="metric"><span>المؤشرات</span><b>${countIndicators(nafesSubject)}</b><small>${fw.title}</small></div><div class="metric"><span>اختبارات نافس</span><b>${tests.length}</b><small>مفتوحة أو محفوظة</small></div><div class="metric"><span>طلاب تم قياسهم</span><b>${students.length}</b><small>نتائج نافس المسجلة</small></div><div class="metric"><span>متوسط القياس</span><b>${pct(avg)}</b><small>من نتائج نافس</small></div></div><div class="nafes-headline"><div><h3>${fw.title}</h3><p>نواتج التعلم المستهدفة وتحت كل هدف تظهر المؤشرات التي يجب أن يقيسها التدريب والاختبار.</p></div><div class="actions">${nafesSubject==='arabic'&&typeof buildArabicReadyTest==='function'?'<button class="btn primary" onclick="buildArabicReadyTest();setTimeout(()=>{switchSection(\'nafes\');setNafesSubject(\'arabic\')},500)">إنشاء اختبار جاهز من البنك</button>':''}</div></div><div class="nafes-goals">${goals}</div><section class="nafes-tests"><div class="nafes-headline"><div><h3>اختبارات نافس — ${fw.title}</h3><p>الاختبار يرسل ككود أو QR، وكل طالب يحصل على نموذج مختلف من الأسئلة المتاحة للاختبار.</p></div></div><div class="test-list">${tests.map(t=>`<div class="test-row"><div><h4>${esc(t.title)}</h4><p>${assessmentType(t.assessment_type)} · ${t.status==='open'?'مفتوح للطلاب':'غير مفتوح'} · ${t.level_target==='adaptive'?'يتكيف مع مستوى الطالب':t.level_target}</p></div><div class="actions">${t.access_code?`<span class="test-code">${esc(t.access_code)}</span>`:''}${t.status==='open'?`<button class="btn" onclick="shareTest('${t.id}')">كود / QR</button>`:`<button class="btn primary" onclick="openTest('${t.id}');setTimeout(()=>{switchSection('nafes');setNafesSubject('${nafesSubject}')},400)">فتح للطلاب</button>`}</div></div>`).join('')||'<div class="empty"><b>لا يوجد بنك اختبار نافس جاهز لهذه المادة حاليًا.</b>المؤشرات ظاهرة ومثبتة في هذا القسم، ويُبنى بنك الأسئلة عليها دون خلطه باختبارات المادة العادية.</div>'}</div><div class="nafes-note">نافس في المرحلة المتوسطة يستهدف الصف الثالث المتوسط. لذلك يعرض هذا القسم مؤشرات المواد الثلاث المستهدفة ويترك اختبارات الدروس العادية داخل قسم المواد.</div></section>`;
}
})();