const SB_URL='https://udznpifopbnrcgxtpzza.supabase.co';
const SB_KEY='sb_publishable_UIuOZaeLk3oz25yf1kd-PA_OF8vEu8N';
const EDGE=SB_URL+'/functions/v1/nafes-indicator-student';
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let session=null,answers={},index=0,timerId=null,saveTimer=null,finishing=false;
async function call(body){const r=await fetch(EDGE,{method:'POST',headers:{apikey:SB_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||'تعذر إكمال العملية');e.data=d;throw e}return d}
function showError(msg){$('startError').textContent=msg;$('startError').classList.remove('hidden')}
async function preview(code){try{const d=await call({action:'preview',code});$('preview').innerHTML=`<b>${esc(d.title)}</b><span>${esc(d.indicator_text)} · ${d.question_count} أسئلة · ${d.duration_minutes} دقيقة</span>`;$('preview').classList.remove('hidden')}catch{$('preview').classList.add('hidden')}}
$('code').addEventListener('change',e=>preview(e.target.value));
$('startForm').onsubmit=async e=>{e.preventDefault();$('startError').classList.add('hidden');const btn=$('startBtn');btn.disabled=true;btn.textContent='جارٍ تجهيز نموذجك...';const fd=new FormData(e.target);try{session=await call({action:'start',code:fd.get('code'),student_name:fd.get('student_name'),student_number:fd.get('student_number')});answers=session.answers||{};index=0;startExam()}catch(err){showError(err.message);if(err.data?.need_student_number){$('studentNumber').focus()}}finally{btn.disabled=false;btn.textContent='بدء الاختبار'}};
function startExam(){$('start').classList.add('hidden');$('exam').classList.remove('hidden');$('examTitle').textContent=session.title;$('examStudent').textContent=session.student_name+(session.resumed?' · استكمال نفس المحاولة':' · نموذج خاص بك');renderNums();renderQuestion();startTimer()}
function renderNums(){$('qnums').innerHTML=session.questions.map((q,i)=>`<button class="${i===index?'active':''} ${answers[q.id]!=null?'done':''}" onclick="goQ(${i})">${i+1}</button>`).join('')}
function goQ(i){index=Math.max(0,Math.min(session.questions.length-1,i));renderNums();renderQuestion()}window.goQ=goQ;
function renderQuestion(){const q=session.questions[index],selected=answers[q.id];const letters=['أ','ب','ج','د','هـ','و'];$('questionCard').innerHTML=`<div class="qmeta"><span>السؤال ${index+1} من ${session.questions.length}</span><span>${q.difficulty?esc(q.difficulty):''}${q.bloom_level?' · '+esc(q.bloom_level):''}</span></div>${q.passage?`<div class="passage">${esc(q.passage)}</div>`:''}<div class="qtext">${esc(q.text)}</div><div class="options">${q.options.map((o,i)=>`<button class="option ${selected===i?'selected':''}" onclick="choose('${q.id}',${i})"><i>${letters[i]||i+1}</i><span>${esc(o)}</span></button>`).join('')}</div><div class="qactions"><button class="btn" ${index===0?'disabled':''} onclick="goQ(${index-1})">→ السابق</button>${index<session.questions.length-1?`<button class="btn" onclick="goQ(${index+1})">التالي ←</button>`:`<button class="btn finish" onclick="finishExam()">تسليم الاختبار</button>`}</div>`}
function choose(id,i){answers[id]=i;renderNums();renderQuestion();queueSave()}window.choose=choose;
function queueSave(){$('saveState').textContent='جارٍ الحفظ...';clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{await call({action:'save',attempt_token:session.attempt_token,answers});$('saveState').textContent='تم حفظ إجاباتك'}catch{$('saveState').textContent='تعذر الحفظ — سيعاد تلقائيًا'}},350)}
function startTimer(){clearInterval(timerId);const tick=()=>{const left=Math.max(0,Date.parse(session.expires_at)-Date.now()),m=Math.floor(left/60000),s=Math.floor(left%60000/1000);$('timerText').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');$('timer').classList.toggle('danger',left<=120000);if(left<=0){clearInterval(timerId);finishExam(true)}};tick();timerId=setInterval(tick,1000)}
async function finishExam(auto=false){if(finishing)return;if(!auto&&!confirm('هل تريد تسليم الاختبار الآن؟'))return;finishing=true;clearInterval(timerId);try{const d=await call({action:'finish',attempt_token:session.attempt_token,answers});showResult(d)}catch(err){finishing=false;alert(err.message||'تعذر تسليم الاختبار') }}window.finishExam=finishExam;
function showResult(d){$('exam').classList.add('hidden');$('result').classList.remove('hidden');$('scorePct').textContent=Math.round(d.percentage)+'٪';$('scoreRing').style.setProperty('--p',Math.max(0,Math.min(100,d.percentage))+'%');$('resultText').textContent=`${session.student_name} — ${d.score} من ${d.total}. ${d.indicator_text||''}`;if(d.answers_revealed){$('reviewNote').textContent='تم إظهار مراجعة الإجابات حسب إعداد المعلم.';$('reviewList').innerHTML=(d.review||[]).map((x,i)=>`<div class="review-item ${x.correct?'good':'bad'}">السؤال ${i+1}: ${x.correct?'إجابة صحيحة':'تحتاج مراجعة'}${x.explanation?' — '+esc(x.explanation):''}</div>`).join('')}else{$('reviewNote').textContent='لن تظهر الإجابات الصحيحة الآن. يحدد المعلم وقت إظهارها بعد إغلاق الاختبار.';$('reviewList').innerHTML=''}}
const codeParam=new URLSearchParams(location.search).get('code');if(codeParam){$('code').value=codeParam;preview(codeParam)}