(()=>{
'use strict';
const T=window.NafesTeacher,A=window.NafesAnalytics,$=id=>document.getElementById(id);
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={reading:'القراءة',math:'الرياضيات',science:'العلوم'}, keys=['reading','math','science'];
const SETTINGS_KEY='nafes_school_report_settings_v1';
let lastHtml='';
function ar(v){return v===null||v===undefined||Number.isNaN(Number(v))?'—':new Intl.NumberFormat('ar-SA',{maximumFractionDigits:1}).format(Number(v))}
function pct(v){return v===null||v===undefined||Number.isNaN(Number(v))?'غير مقاس':`${ar(v)}٪`}
function settings(){try{return{schoolName:'',teacherName:'',principalName:'',ministryLogo:'',schoolLogo:'',...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch(_){return{schoolName:'',teacherName:'',principalName:'',ministryLogo:'',schoolLogo:''}}}
function saveSettings(s){localStorage.setItem(SETTINGS_KEY,JSON.stringify(s))}
function logo(src,label){return src?`<img src="${src}" alt="${E(label)}">`:`<span class="wr-logo-empty">${E(label)} غير مرفوع</span>`}
function submitted(a){return A?.isSubmitted?A.isSubmitted(a):!!a.submitted_at}
function scorable(q){return A?.isScorable?A.isScorable(q):(typeof q.correct==='boolean'&&Number(q.correct_index??q.correctIndex)>=0)}
function indKey(q){return A?.indicatorKey?A.indicatorKey(q):(q.indicator_key||null)}
function identity(a){return a.studentIdentity||A?.studentIdentity?.(a)||String(a.student_id||a.student_name||a.id)}
function savedPercent(a){return A?.savedPercent?A.savedPercent(a):(Number(a.total)>0?Number(a.score)/Number(a.total)*100:null)}
function normalize(a){return A?.normalizeAttempt?A.normalizeAttempt(a):a}
function measure(a,subject){if(A?.measure)return A.measure(a,{subject});const qs=(a.questions||[]).filter(q=>q.subject===subject&&scorable(q));const correct=qs.filter(q=>q.correct).length;return{correct,total:qs.length,percent:qs.length?correct/qs.length*100:null}}
function mean(v){const a=v.filter(x=>x!==null&&x!==undefined&&Number.isFinite(Number(x))).map(Number);return a.length?a.reduce((s,x)=>s+x,0)/a.length:null}
function latestForTest(attempts,testId){const map=new Map();for(const a of attempts.filter(x=>submitted(x)&&String(x.test_id)===String(testId))){const k=identity(a),p=map.get(k);const at=Date.parse(a.submitted_at||a.started_at||0)||0,pt=p?(Date.parse(p.submitted_at||p.started_at||0)||0):-1;if(!p||at>pt)map.set(k,a)}return[...map.values()]}
function subjectStats(atts,subject){const ms=atts.map(a=>measure(a,subject)).filter(m=>m.total>0);return{count:ms.length,avg:mean(ms.map(m=>m.percent)),avgCorrect:mean(ms.map(m=>m.correct)),avgTotal:mean(ms.map(m=>m.total)),mastery:ms.length?ms.filter(m=>m.percent>=80).length/ms.length*100:null}}
function indicatorStats(atts,subject){const g=new Map();for(const a of atts){for(const q of a.questions||[]){if(q.subject!==subject||!scorable(q))continue;const k=indKey(q);if(!k)continue;if(!g.has(k))g.set(k,{key:k,text:q.indicator_text||k,correct:0,total:0,students:new Set()});const x=g.get(k);x.total++;if(q.correct)x.correct++;x.students.add(identity(a))}}return[...g.values()].map(x=>({...x,percent:x.total?x.correct/x.total*100:null})).sort((a,b)=>(a.percent??101)-(b.percent??101))}
function weakestSubject(a){const arr=keys.map(s=>({s,m:measure(a,s)})).filter(x=>x.m.total);if(!arr.length)return{label:'غير مقاس',percent:null};arr.sort((x,y)=>x.m.percent-y.m.percent);return{label:names[arr[0].s],percent:arr[0].m.percent}}
function weakIndicatorsForStudent(a){const list=[];for(const s of keys){const by=new Map();for(const q of a.questions||[]){if(q.subject!==s||!scorable(q))continue;const k=indKey(q);if(!k)continue;if(!by.has(k))by.set(k,{text:q.indicator_text||k,c:0,t:0});const g=by.get(k);g.t++;if(q.correct)g.c++}for(const g of by.values()){const p=g.t?g.c/g.t*100:null;if(p!==null&&p<50)list.push(g.text)}}return list.slice(0,3)}
async function readLogo(file){if(!file)return'';if(file.size>4*1024*1024)throw new Error('حجم الصورة كبير جدًا');const url=URL.createObjectURL(file);try{return await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const maxW=700,maxH=260,scale=Math.min(1,maxW/img.width,maxH/img.height),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/png'))};img.onerror=reject;img.src=url})}finally{URL.revokeObjectURL(url)}}
function installSettingsCard(){const view=$('reportView');if(!view||$('weeklyReportSettings'))return;const s=settings();const card=document.createElement('section');card.id='weeklyReportSettings';card.className='weekly-report-settings card';card.innerHTML=`<div class="wr-settings-head"><div><h2>إعدادات التقرير</h2><div class="muted">هذه البيانات فقط تدخلها أنت، أما محتوى التقرير فيُستخرج من الاختبار الحقيقي.</div></div></div><div class="wr-settings-grid"><label><span>اسم المدرسة</span><input id="wrSchool" value="${E(s.schoolName||'')}"></label><label><span>اسم المعلم</span><input id="wrTeacher" value="${E(s.teacherName||'')}"></label><label><span>اسم المدير</span><input id="wrPrincipal" value="${E(s.principalName||'')}"></label><div class="wr-logo-fields"><label><span>رفع شعار وزارة التعليم - يظهر في المنتصف</span><input id="wrMinistry" type="file" accept="image/*"></label><label><span>رفع شعار المدرسة - يظهر في أقصى اليسار</span><input id="wrSchoolLogo" type="file" accept="image/*"></label></div><div class="wr-logo-note">لن يوضع أي شعار افتراضي أو وهمي. يظهر فقط الشعار الذي ترفعه أنت.</div><button type="button" id="wrSave" class="btn wr-save">حفظ إعدادات التقرير</button></div>`;view.insertBefore(card,view.firstChild);
$('wrSave').onclick=async()=>{const cur=settings();try{const mf=$('wrMinistry').files?.[0],sf=$('wrSchoolLogo').files?.[0];const next={...cur,schoolName:$('wrSchool').value.trim(),teacherName:$('wrTeacher').value.trim(),principalName:$('wrPrincipal').value.trim()};if(mf)next.ministryLogo=await readLogo(mf);if(sf)next.schoolLogo=await readLogo(sf);saveSettings(next);$('wrMinistry').value='';$('wrSchoolLogo').value='';if($('reportTest')?.value)await buildReferenceReport();alert('تم حفظ إعدادات التقرير.')}catch(err){alert(err.message||'تعذر حفظ إعدادات التقرير')}}}
async function loadData(){let cursor=0,attempts=[],tests=[];do{const d=await T.api('teacher_data',{cursor,limit:100});attempts.push(...(d.attempts||[]));if(cursor===0)tests=d.tests||[];cursor=d.next_cursor}while(cursor!==null);return{attempts:attempts.map(normalize),tests}}
function bullets(items){return `<ul>${items.map(x=>`<li>${E(x)}</li>`).join('')}</ul>`}
async function buildReferenceReport(){const testId=$('reportTest')?.value;if(!testId){$('reportPreview').innerHTML='<div class="report-preview-empty">اختر الاختبار أولًا.</div>';return}const btn=$('buildReportBtn');if(btn){btn.disabled=true;btn.textContent='جارٍ إنشاء التقرير…'}try{const {attempts,tests}=await loadData(),test=tests.find(t=>String(t.id)===String(testId)),atts=latestForTest(attempts,testId);if(!atts.length){$('reportPreview').innerHTML='<div class="report-preview-empty">لا توجد نتائج حقيقية مسلّمة لهذا الاختبار.</div>';return}const s=settings(),week=$('reportWeek')?.value.trim()||'غير محدد',today=new Date().toLocaleDateString('ar-SA');const sm=Object.fromEntries(keys.map(k=>[k,subjectStats(atts,k)])),overall=atts.map(a=>({a,p:savedPercent(a)})).filter(x=>x.p!==null),low=overall.filter(x=>x.p<50).sort((a,b)=>a.p-b.p);const inds=Object.fromEntries(keys.map(k=>[k,indicatorStats(atts,k)]));const measured=keys.map(k=>({k,...sm[k]})).filter(x=>x.count&&x.avg!==null).sort((a,b)=>b.avg-a.avg);const best=measured[0],worst=measured[measured.length-1];const positives=[];if(best)positives.push(`أعلى نسبة تحصيل في ${names[best.k]} وبلغت ${pct(best.avg)}.`);const highMastery=measured.filter(x=>(x.mastery??0)>=50);if(highMastery.length)positives.push(`ظهرت مستويات إتقان جيدة في ${highMastery.map(x=>names[x.k]).join(' و ')}.`);if(!low.length)positives.push('لا يوجد طلاب أقل من 50٪ في الاختبار المختار.');const follow=[];if(worst)follow.push(`أقل نسبة تحصيل في ${names[worst.k]} وبلغت ${pct(worst.avg)}.`);if(low.length)follow.push(`يوجد ${ar(low.length)} طالبًا أقل من 50٪ ويحتاجون متابعة مباشرة.`);for(const k of keys){if(inds[k][0])follow.push(`المؤشر الأضعف في ${names[k]}: ${inds[k][0].text} (${pct(inds[k][0].percent)}).`)}const target=[];for(const k of keys){const weak=inds[k].slice(0,2);if(weak.length)target.push(`${names[k]}: ${weak.map(x=>x.text).join('، ')}`);else target.push(`${names[k]}: غير مقاس في هذا الاختبار`)}const avgAll=mean(overall.map(x=>x.p));const progress=[`متوسط نتيجة الطلاب في الاختبار ${pct(avgAll)}.`,best?`أفضل أداء ظهر في ${names[best.k]}.`:'لا توجد مواد مقاسة.',low.length?`الطلاب ذوو الدرجات المتدنية: ${ar(low.length)}.`:'لا يوجد طلاب تحت 50٪.'];const targetStudents=[`عدد الطلاب الذين أدوا الاختبار: ${ar(atts.length)} طالبًا.`,low.length?`الطلاب الأقل من 50٪ محصورون في الورقة الثانية.`:'لا يوجد طلاب أقل من 50٪.',`التقرير مبني على آخر محاولة مسلّمة لكل طالب في الاختبار.`];
const top=`<header class="wr-topbar"><div class="wr-admin"><b>المملكة العربية السعودية</b><br>وزارة التعليم<br>الإدارة العامة للتعليم بمنطقة نجران<br><b>${E(s.schoolName||'')}</b></div><div class="wr-ministry">${logo(s.ministryLogo,'شعار وزارة التعليم')}</div><div class="wr-school">${logo(s.schoolLogo,'شعار المدرسة')}</div></header>`;
const achievement=keys.map(k=>`<div>نسبة التحصيل في ${names[k]}: ${pct(sm[k].avg)}</div>`).join('');const scoreAvgs=keys.map(k=>`<div>متوسط الدرجات في ${names[k]}: ${sm[k].count?`${ar(sm[k].avgCorrect)} من ${ar(sm[k].avgTotal)}`:'غير مقاس'}</div>`).join('');
const page1=`<article class="weekly-report report-sheet">${top}<div class="wr-title-pill">تقرير نتائج نافس</div><div class="wr-subtitle">تقرير على المهارات المطلوبة<br><b>${E(week)}</b> · ${E(test?.title||'اختبار نافس')}</div><div class="wr-triple"><section class="wr-info-box"><h3>المهارة المستهدفة</h3>${bullets(target)}</section><section class="wr-info-box"><h3>الطلاب المستهدفون</h3>${bullets(targetStudents)}</section><section class="wr-info-box"><h3>متوسط التقدم</h3>${bullets(progress)}</section></div><div class="wr-two"><section class="wr-callout"><h3>أبرز إيجابيات الاختبار</h3>${bullets(positives.length?positives:['لا توجد بيانات كافية لإبراز نقطة إيجابية.'])}</section><section class="wr-callout"><h3>نقاط تحتاج متابعة عاجلة</h3>${bullets(follow.length?follow:['لا توجد نقاط متابعة آلية من النتائج الحالية.'])}</section></div><section class="wr-band"><h3>نسبة التحصيل في المواد</h3><div class="wr-band-grid">${achievement}</div></section><section class="wr-band"><h3>متوسط الدرجات</h3><div class="wr-band-grid">${scoreAvgs}</div></section><div class="wr-footer-curve"></div></article>`;
const lowRows=low.map((x,i)=>{const w=weakestSubject(x.a),wis=weakIndicatorsForStudent(x.a);return`<tr><td>${ar(i+1)}</td><td><b>${E(x.a.student_name||'اسم غير مسجل')}</b></td><td>${E(x.a.class_name||'—')}</td><td>${ar(x.a.score)} / ${ar(x.a.total)}</td><td>${pct(x.p)}</td><td>${E(w.label)}${w.percent!==null?` (${pct(w.percent)})`:''}</td><td>${E(wis.join('، ')||'لا يوجد مؤشر منخفض محدد')}</td></tr>`}).join('');
const page2=`<article class="weekly-report report-sheet">${top}<div class="wr-low-title">حصر الطلاب ذوي الدرجات المتدنية - ${E(week)}</div><table class="wr-low-table"><thead><tr><th>م</th><th>اسم الطالب</th><th>الفصل</th><th>الدرجة</th><th>النسبة</th><th>أضعف مادة</th><th>أبرز المؤشرات الضعيفة</th></tr></thead><tbody>${lowRows||'<tr><td class="empty" colspan="7">لا يوجد طلاب أقل من 50٪ في هذا الاختبار.</td></tr>'}</tbody></table><div class="wr-signatures"><div class="wr-signature">المدير<span>${E(s.principalName||'—')}</span></div><div class="wr-signature">المعلم<span>${E(s.teacherName||'—')}</span></div></div><div class="wr-footer-curve"></div></article>`;
lastHtml=page1+page2;$('reportPreview').innerHTML=lastHtml;$('printReportBtn').disabled=false;}catch(err){$('reportPreview').innerHTML=`<div class="report-preview-empty">تعذر إنشاء التقرير: ${E(err.message||err)}</div>`}finally{if(btn){btn.disabled=false;btn.textContent='إنشاء التقرير'}}}
function wire(){installSettingsCard();const b=$('buildReportBtn'),p=$('printReportBtn');if(b)b.onclick=buildReferenceReport;if(p)p.onclick=()=>{if(!lastHtml)return;const root=$('printRoot');root.innerHTML=lastHtml;root.setAttribute('aria-hidden','false');window.print()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();