(()=>{
const EDGE='https://udznpifopbnrcgxtpzza.supabase.co/functions/v1/nafes-exam';const $=id=>document.getElementById(id);const letters=['أ','ب','ج','د'];
let config=null,attempt=null,sections=[],answers={},sectionIndex=0,questionIndex=0,timerId=null,breakId=null,saving=false,finishing=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function decode(raw){raw=raw.replaceAll('-','+').replaceAll('_','/');while(raw.length%4)raw+='=';const bin=atob(raw),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
function subjectName(k){return{reading:'القراءة',math:'الرياضيات',science:'العلوم'}[k]||k}
function ready(type,msg){$('readiness').className=`readiness ${type}`;$('readiness').textContent=msg}
async function call(body){const r=await fetch(EDGE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({error:'تعذرت قراءة استجابة الخادم'}));if(!r.ok)throw new Error(d.error||'تعذر تنفيذ الطلب');return d}
function student(){const mode=config.identity_mode;const name=mode==='list'?$('studentList').value:$('studentName').value.trim();return{name,no:$('studentNo').value.trim()}}
function setup(){try{config=decode(new URLSearchParams(location.search).get('c')||'')}catch(_){ready('bad','رابط المحاكاة غير صحيح.');return}$('title').textContent=config.title||'محاكاة نافس الكاملة';$('details').textContent=[config.school_name,config.class_name,config.teacher_name&&`المعلم: ${config.teacher_name}`].filter(Boolean).join(' · ');$('simCode').textContent=`N3-${String(config.id||'').slice(0,8).toUpperCase()}`;$('sectionSummary').innerHTML=(config.sections||[]).map(s=>`<article><b>${subjectName(s.subject)}</b><small>${s.question_count} سؤالًا · ${s.duration_minutes} دقيقة</small></article>`).join('');if(!config.allow_copy){document.body.classList.add('no-copy');document.addEventListener('copy',e=>{if(e.target.closest?.('.question'))e.preventDefault()})}if(config.closes_at&&Date.now()>new Date(config.closes_at).getTime()){ready('bad','انتهى وقت إتاحة هذه المحاكاة.');return}const mode=config.identity_mode||'manual';if(mode==='list'){$('studentNameWrap').classList.add('hidden');$('studentListWrap').classList.remove('hidden');$('studentList').innerHTML='<option value="">اختر اسمك</option>'+(config.roster||[]).map(n=>`<option>${esc(n)}</option>`).join('')}if(mode==='email'){$('studentNoLabel').textContent='بريد مدرستي';$('studentNo').type='email';$('studentNo').placeholder='name@moe.gov.sa'}ready('good','المحاكاة جاهزة. يبدأ توقيت كل قسم عند الوصول إليه، وتظهر الاستراحة بين الأقسام.');$('studentForm').classList.remove('hidden');try{const s=JSON.parse(localStorage.getItem('nafes_student')||'{}');if(mode!=='list')$('studentName').value=s.name||'';$('studentNo').value=s.no||''}catch(_){}}
$('studentForm').addEventListener('submit',async e=>{e.preventDefault();const s=student();if(!s.name||!s.no)return;if(config.identity_mode==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s.no)){ready('bad','اكتب بريدًا مدرسيًا صحيح الصيغة.');return}const btn=e.submitter;btn.disabled=true;btn.textContent='جارٍ تجهيز المحاكاة...';try{localStorage.setItem('nafes_student',JSON.stringify(s));const d=await call({action:'simulation_start',config,student_name:s.name,student_no:s.no});attempt=d.attempt_id;sections=d.sections||[];answers=d.answers||{};sectionIndex=Number(d.current_section||0);questionIndex=0;if(d.submitted){showResult(d);return}$('intro').classList.add('hidden');$('exam').classList.remove('hidden');renderSection();}catch(err){ready('bad',err.message);btn.disabled=false;btn.textContent='ابدأ المحاكاة'}});
function currentSection(){return sections[sectionIndex]}
function renderSection(){const section=currentSection();if(!section)return finish(true);$('sectionMeta').textContent=`القسم ${sectionIndex+1} من ${sections.length}`;$('sectionTitle').textContent=subjectName(section.subject);$('sectionTabs').innerHTML=sections.map((_,i)=>`<span class="${i<sectionIndex?'done':i===sectionIndex?'active':''}"></span>`).join('');$('calculatorBtn').classList.toggle('hidden',!(section.subject==='math'&&section.calculator));questionIndex=Math.min(questionIndex,section.questions.length-1);renderQuestion();startSectionTimer(section.duration_minutes)}
function renderQuestion(){const section=currentSection(),q=section.questions[questionIndex];$('progress').innerHTML=section.questions.map((x,i)=>`<button type="button" data-i="${i}" class="${i===questionIndex?'current ':''}${answers[x.id]!==undefined?'done':''}">${i+1}</button>`).join('');$('progress').querySelectorAll('button').forEach(b=>b.onclick=()=>{questionIndex=Number(b.dataset.i);renderQuestion()});$('question').innerHTML=`${q.context?`<div class="context">${esc(q.context)}</div>`:''}<div class="stem">${esc(q.question)}</div><div class="choices">${q.options.map((x,i)=>`<label class="choice ${Number(answers[q.id])===i?'selected':''}"><input type="radio" name="answer" value="${i}" ${Number(answers[q.id])===i?'checked':''}><span class="letter">${letters[i]}</span><span>${esc(x)}</span></label>`).join('')}</div>`;$('question').querySelectorAll('input').forEach(x=>x.onchange=()=>{answers[q.id]=Number(x.value);renderQuestion();saveSoon()});$('prev').disabled=questionIndex===0;$('next').textContent=questionIndex===section.questions.length-1?(sectionIndex===sections.length-1?'إنهاء المحاكاة':'إنهاء القسم'):'التالي';$('prev').onclick=()=>{if(questionIndex){questionIndex--;renderQuestion()}};$('next').onclick=()=>{if(questionIndex<section.questions.length-1){questionIndex++;renderQuestion()}else endSection()};$('review').onclick=reviewSection}
function reviewSection(){const section=currentSection();$('question').innerHTML=`<div class="review-panel"><b>مراجعة ${subjectName(section.subject)}</b><p>أجبت عن ${section.questions.filter(q=>answers[q.id]!==undefined).length} من ${section.questions.length}.</p><div class="review-grid">${section.questions.map((q,i)=>`<button class="${answers[q.id]!==undefined?'done':''}" data-i="${i}">السؤال ${i+1}</button>`).join('')}</div><div class="review-actions"><button id="back">العودة للأسئلة</button><button id="submitSection">${sectionIndex===sections.length-1?'تسليم المحاكاة':'إنهاء القسم'}</button></div></div>`;$('question').querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{questionIndex=Number(b.dataset.i);renderQuestion()});$('back').onclick=renderQuestion;$('submitSection').onclick=endSection}
function endSection(){clearInterval(timerId);if(sectionIndex===sections.length-1){finish(false);return}const next=sections[sectionIndex+1];$('exam').classList.add('hidden');$('breakPanel').classList.remove('hidden');$('breakTitle').textContent=`انتهى ${subjectName(currentSection().subject)} — التالي ${subjectName(next.subject)}`;let left=Math.max(0,Number(config.break_minutes||0)*60);const tick=()=>{$('breakTimer').textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(left--<=0)startNext()};tick();breakId=setInterval(tick,1000)}
function startNext(){clearInterval(breakId);$('breakPanel').classList.add('hidden');$('exam').classList.remove('hidden');sectionIndex++;questionIndex=0;renderSection()}
$('skipBreak').onclick=startNext;
let saveDelay=null;function saveSoon(){clearTimeout(saveDelay);saveDelay=setTimeout(save,500)}async function save(){if(!attempt||saving||finishing)return;saving=true;const s=student();try{await call({action:'simulation_save',attempt_id:attempt,student_name:s.name,student_no:s.no,answers,current_section:sectionIndex})}catch(_){}finally{saving=false}}
async function finish(auto){if(finishing)return;if(!auto&&!confirm('هل تريد تسليم المحاكاة نهائيًا؟'))return;finishing=true;clearInterval(timerId);clearInterval(breakId);const s=student();try{const d=await call({action:'simulation_finish',attempt_id:attempt,student_name:s.name,student_no:s.no,answers});showResult(d)}catch(e){finishing=false;alert(e.message)}}
function showResult(d){$('intro').classList.add('hidden');$('exam').classList.add('hidden');$('breakPanel').classList.add('hidden');$('result').classList.remove('hidden');if(d.result_hidden){$('result').innerHTML='<h2>تم تسليم المحاكاة</h2><p>حُفظت إجاباتك بنجاح، والنتيجة غير متاحة وفق إعداد المعلم.</p>';return}const review=new Map((d.review||[]).map(x=>[String(x.id),x]));const flat=sections.flatMap(s=>s.questions.map(q=>({...q,subject:s.subject})));const cards=review.size?`<section class="answers-review"><h3>مراجعة الإجابات</h3>${flat.map((q,i)=>{const r=review.get(String(q.id));if(!r)return'';const chosen=answers[q.id],ok=Number(chosen)===Number(r.correct_index);return`<article class="answer-card ${ok?'correct':'wrong'}"><b>${subjectName(q.subject)} · السؤال ${i+1}</b><p>${esc(q.question)}</p><p><strong>إجابتك:</strong> ${chosen===undefined?'لم تُجب':esc(q.options[chosen])}</p><p><strong>الصحيحة:</strong> ${esc(q.options[r.correct_index])}</p>${r.explanation?`<p><strong>السبب:</strong> ${esc(r.explanation)}</p>`:''}</article>`}).join('')}</section>`:'';$('result').innerHTML=`<span class="kicker">النتيجة النهائية</span><div class="result-score">${Math.round(Number(d.percent||0))}%</div><h2>${d.score||0} من ${d.total||flat.length}</h2><div class="scores">${(d.section_scores||[]).map(s=>`<article><b>${subjectName(s.subject)}</b><span>${s.score} من ${s.total}</span><small>${Math.round(s.percent)}%</small></article>`).join('')}</div>${cards}`}
function startSectionTimer(minutes){clearInterval(timerId);const key=`nafes_sim_timer_${attempt}_${sectionIndex}`;let end=Number(localStorage.getItem(key)||0);if(!end||end<Date.now())end=Date.now()+Number(minutes||20)*60000;localStorage.setItem(key,String(end));const tick=()=>{const left=Math.max(0,Math.floor((end-Date.now())/1000));$('timer').textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;$('timer').className=`timer${left<=60?' danger':left<=300?' warn':''}`;if(left<=0){clearInterval(timerId);endSection()}};tick();timerId=setInterval(tick,1000)}
$('calculatorBtn').onclick=()=>$('calculator').classList.remove('hidden');$('closeCalculator').onclick=()=>$('calculator').classList.add('hidden');$('calculator').onclick=e=>{if(e.target===$('calculator'))$('calculator').classList.add('hidden')};$('calculate').onclick=()=>{const a=Number($('calcA').value),b=Number($('calcB').value),op=$('calcOp').value;let v=op==='+'?a+b:op==='−'?a-b:op==='×'?a*b:b===0?'لا يمكن القسمة على صفر':a/b;$('calcResult').textContent=typeof v==='number'&&Number.isFinite(v)?String(Math.round(v*1e8)/1e8):String(v)};
window.addEventListener('beforeunload',()=>{if(attempt&&!finishing){const s=student();try{navigator.sendBeacon(EDGE,new Blob([JSON.stringify({action:'simulation_save',attempt_id:attempt,student_name:s.name,student_no:s.no,answers,current_section:sectionIndex})],{type:'application/json'}))}catch(_){}}});
setup();
})();
