(()=>{
const EDGE='https://udznpifopbnrcgxtpzza.supabase.co/functions/v1/nafes-exam';
const TESTS_PER_INDICATOR=30;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const prefix={reading:'R',math:'M',science:'S'};
const getSubject=k=>(window.NAFES_SUBJECTS||[]).find(s=>s.key===k);
const code=(s,o,i,m)=>`N3-${prefix[s]||'X'}-${String(o).replace(/[^0-9A-Za-z]/g,'')}-I${pad(i)}-M${pad(m)}`;
const url=(s,o,i,m)=>`${location.origin}${location.pathname.replace(/[^/]+$/,'')}exam.html?s=${encodeURIComponent(s)}&o=${encodeURIComponent(o)}&i=${i}&m=${m}`;
async function preview(s,o,i,m=1){try{const r=await fetch(EDGE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'preview',subject:s,outcome:o,indicator:i,model:m})});return await r.json()}catch(e){return{ready:false,approved:0,required:24,error:'تعذر الاتصال بمحرك الاختبارات'}}}
function ensureModal(){let x=document.getElementById('testModal');if(x)return x;x=document.createElement('div');x.id='testModal';x.className='modal-layer hidden';x.innerHTML='<div class="modal-card tests-modal"><button class="modal-close" type="button" aria-label="إغلاق">×</button><div id="testModalBody"></div></div>';document.body.appendChild(x);x.addEventListener('click',e=>{if(e.target===x||e.target.closest('.modal-close'))closeModels()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModels()});return x}
window.closeModels=()=>{const m=document.getElementById('testModal');if(m)m.classList.add('hidden')};
window.copyTestLink=async(s,o,i,m)=>{const u=url(s,o,i,m);try{await navigator.clipboard.writeText(u);toast('تم نسخ رابط الاختبار')}catch(_){prompt('انسخ الرابط:',u)}};
window.openQr=(s,o,i,m)=>{const u=url(s,o,i,m),c=code(s,o,i,m);let q=document.getElementById('qrLayer');if(!q){q=document.createElement('div');q.id='qrLayer';q.className='modal-layer hidden';q.innerHTML='<div class="modal-card qr-card"><button class="modal-close" type="button">×</button><div class="qr-title"></div><div id="qrBox"></div><div class="qr-code"></div><div class="qr-actions"></div></div>';document.body.appendChild(q);q.addEventListener('click',e=>{if(e.target===q||e.target.closest('.modal-close'))q.classList.add('hidden')})}q.querySelector('.qr-title').innerHTML='<b>باركود الاختبار</b><small>يفتح نفس المؤشر، والنظام يختار نموذج أسئلة مختلفًا لكل طالب.</small>';q.querySelector('.qr-code').textContent=c;q.querySelector('.qr-actions').innerHTML=`<button onclick="copyTestLink('${s}','${o}',${i},${m})">نسخ الرابط</button><a href="${u}" target="_blank">فتح الاختبار</a>`;const box=q.querySelector('#qrBox');box.innerHTML='';if(window.QRCode)new QRCode(box,{text:u,width:210,height:210,colorDark:'#17324d',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});else box.innerHTML='<div class="qr-fallback">تعذر إنشاء الباركود بصريًا، استخدم الرابط.</div>';q.classList.remove('hidden')};
function toast(t){let x=document.getElementById('miniToast');if(!x){x=document.createElement('div');x.id='miniToast';x.className='mini-toast';document.body.appendChild(x)}x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
window.openNafesModels=async(s,o,i)=>{const subj=getSubject(s),out=subj?.outcomes?.find(x=>x.code===o),text=out?.indicators?.[i-1]||'';const layer=ensureModal(),body=document.getElementById('testModalBody');layer.classList.remove('hidden');body.innerHTML='<div class="loading-box">جارٍ فحص بنك أسئلة هذا المؤشر...</div>';const p=await preview(s,o,i,1);const ready=!!p.ready;const approved=Number(p.approved||0),required=Number(p.required||24);body.innerHTML=`<header class="tests-head"><span>نافس · ${esc(subj?.title||s)}</span><h3>${TESTS_PER_INDICATOR} اختبارًا على المؤشر</h3><p>${esc(text)}</p><div class="bank-state ${ready?'ready':'building'}"><b>${ready?'البنك جاهز للتشغيل':'البنك يحتاج استكمالًا قبل تشغيل الطلاب'}</b><span>${approved} سؤال معتمد من ${required} سؤالًا كحد أدنى</span></div></header><div class="models-note"><b>كيف تختلف الاختبارات؟</b><span>كل رقم أدناه اختبار مستقل له رابط وباركود. وداخل كل اختبار يحصل كل طالب على مجموعة أسئلة مختلفة من بنك المؤشر مع تغيير ترتيب الأسئلة والاختيارات، بينما يعود الطالب نفسه إلى محاولته نفسها.</span></div><div class="models-grid">${Array.from({length:TESTS_PER_INDICATOR},(_,k)=>{const m=k+1,u=url(s,o,i,m),c=code(s,o,i,m);return `<article class="model-card ${ready?'':'locked'}"><div class="model-no">${pad(m)}</div><div class="model-main"><b>اختبار ${pad(m)}</b><small>${c}</small></div><div class="model-actions"><button onclick="openQr('${s}','${o}',${i},${m})">باركود</button><button onclick="copyTestLink('${s}','${o}',${i},${m})">نسخ الرابط</button><a href="${u}" target="_blank">فتح</a></div>${ready?'':'<span class="lock-note">يفتح تلقائيًا بعد اعتماد البنك</span>'}</article>`}).join('')}</div>`};
})();