(()=>{
const EDGE='https://udznpifopbnrcgxtpzza.supabase.co/functions/v1/nafes-exam';
const TESTS_PER_INDICATOR=4;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const prefix={reading:'R',math:'M',science:'S'};
const getSubject=k=>(window.NAFES_SUBJECTS||[]).find(s=>s.key===k);
function indicatorGuide(subject,text){
 const guides={
  reading:[
   [/معاني|مرادف|ترادف|تضاد|سياق|تعريف|مصطلح|مفردات|دلالات/,'تحديد معنى الكلمة المقصود من السياق، ثم تمييز علاقتها بالكلمات الأخرى أو توظيفها في جملة جديدة.','اقرأ الجملة كاملة، وحدد القرائن المحيطة بالكلمة، ثم جرّب المعنى في موضعها.','لا تعتمد على المعنى المشهور للكلمة إذا كان السياق يدل على معنى آخر.'],
   [/رئيس|الفرعية|موضوع/,'تمييز الفكرة التي تجمع النص من التفاصيل التي تشرحها أو تدعمها.','اسأل: عمّ يتحدث النص كله؟ ثم اجمع التفاصيل تحت الفكرة الأشمل.','لا تختَر تفصيلًا صحيحًا على أنه الفكرة الرئيسة.'],
   [/ضمنية|غير المباشرة|استنتج|يستنتج/,'الوصول إلى معنى لم يذكره الكاتب صراحة، لكنه تدعمه قرائن واضحة في النص.','اربط بين معلومتين أو أكثر، واختر النتيجة التي يؤيدها النص دون مبالغة.','لا تجعل معرفتك الخارجية بديلًا عن دليل النص.'],
   [/تشابه|اختلاف|يقارن|مقارنة|علاقات|روابط|سبب|نتيجة/,'مقارنة الأفكار أو تفسير العلاقة بينها، مثل السبب والنتيجة أو المشكلة والحل.','حدد طرفي العلاقة، ثم ابحث عن العبارة التي توضح كيف يؤثر أحدهما في الآخر.','تشابه الموضوع لا يعني تطابق الفكرة أو الدليل.'],
   [/حقائق|الآراء|مباشرة|غير مباشرة/,'التمييز بين معلومة يمكن التحقق منها ورأي يعبر عن حكم أو موقف، وبين المعنى الصريح والمعنى المستنتج.','ابحث عن الدليل: الحقيقة قابلة للتحقق، والرأي يحتاج إلى حجة تدعمه.','لا تعد كل جملة مؤكدة حقيقة لمجرد أنها مكتوبة بثقة.'],
   [/مشاعر|دوافع|الكاتب|تراكيب|تعابير/,'استنتاج موقف الكاتب ومشاعره ودوافعه من الألفاظ والتراكيب التي اختارها.','تتبع الكلمات ذات الدلالة الإيجابية أو السلبية واربطها بفكرة النص.','لا تنسب إلى الكاتب شعورًا لا تؤيده عبارة محددة.'],
   [/يلخص|تلخيص|يعيد صياغ|ينظم معلومات/,'اختصار النص مع الحفاظ على فكرته المركزية وأهم ما يدعمها، وبعبارات واضحة غير مكررة.','احذف الأمثلة والتكرار، ثم اكتب الفكرة الرئيسة وأهم التفاصيل المساندة.','التلخيص ليس نسخ جملة طويلة من النص ولا حذف فكرته الأساسية.'],
   [/يقوم|يقوّم|ينقد|وجهة|القيم|البدائل|الحجج|البراهين|حل مشكلات|مواقف حياتية/,'تقويم أفكار النص وأدلته، وإبداء رأي معلل، ثم اقتراح بديل أو تطبيق مناسب عند الحاجة.','اربط حكمك بدليل من النص، وقارن قوة البدائل قبل اختيار الأنسب.','الرأي المقبول هنا يحتاج إلى سبب أو دليل، لا إلى موافقة أو رفض فقط.']
  ],
  math:[
   [/معادلة|متباينة|نظام|دالة|عبارات جبرية|تحليل/,'فهم العلاقة الجبرية واختيار القاعدة المناسبة ثم تنفيذ الخطوات والتحقق من الناتج.','حدد المعطيات والمطلوب، ونفّذ العمليات العكسية بترتيب واضح.','لا تغيّر طرفًا من العلاقة دون إجراء التغيير نفسه على الطرف الآخر.'],
   [/هندس|مثلث|مضلع|زاوية|دائرة|محيط|مساحة|حجم|تحويل/,'استخدام خصائص الأشكال والعلاقات الهندسية لحساب قياس أو تفسير تحول.','ارسم شكلًا مبسطًا، ودوّن القياسات، ثم اختر القانون المناسب.','ميّز بين المحيط والمساحة والحجم ووحدات كل منها.'],
   [/احتمال|عينة|بيانات|تمثيل|متوسط|وسيط|منوال|تشتت/,'قراءة البيانات أو تنظيمها واختيار المقياس أو التمثيل الذي يجيب عن السؤال.','حدد نوع البيانات وما المطلوب مقارنته قبل الحساب أو اختيار الرسم.','لا تحكم من قيمة واحدة إذا كان السؤال عن مجموعة البيانات كلها.'],
   [/نسبة|معدل|تناسب|مئوية|أسس|جذر|أعداد/,'اختيار العملية العددية المناسبة وتمثيل العلاقة بصورة صحيحة.','حوّل المعطيات إلى أعداد أو نسب متكافئة، ثم تحقق من معقولية الناتج.','انتبه إلى الإشارة ووحدة القياس وترتيب العمليات.']
  ],
  science:[
   [/تجربة|استقصاء|فرضية|متغير|بيانات|دليل|استنتاج/,'قراءة موقف علمي وتحديد الدليل أو المتغير أو الاستنتاج الذي تدعمه البيانات.','افصل بين الملاحظة والتفسير، ثم اربط النتيجة بالبيانات المعروضة.','لا تعد التوقع دليلًا، ولا تستنتج أكثر مما تسمح به البيانات.'],
   [/قوة|حركة|سرعة|تسارع|طاقة|كهرب|موج|ضوء|صوت|حرارة/,'تطبيق المفهوم الفيزيائي المناسب على موقف أو بيانات، مع الانتباه إلى العلاقة بين الكميات.','حدد الكميات ووحداتها، ثم اختر القانون أو العلاقة التي تربطها.','لا تستخدم قانونًا لمجرد وجود أرقام؛ تحقق أولًا من أنه يقيس المطلوب.'],
   [/خلية|وراث|جهاز|مخلوق|بيئ|تنوع|دورة/,'تفسير بنية أو عملية حيوية وربطها بوظيفتها أو أثرها في النظام الحي.','حدد الجزء أو العملية، ثم تتبع وظيفتها وما ينتج عنها.','لا تخلط بين وصف البنية وشرح وظيفتها.'],
   [/ذرة|عنصر|مركب|تفاعل|حمض|قاعدة|مادة/,'تمييز خصائص المادة أو تفسير تغيرها باستخدام نموذج أو دليل كيميائي مناسب.','حدد المواد قبل التغير وبعده، وابحث عن دليل يميز التغير الفيزيائي من الكيميائي.','تغير الشكل أو الحالة لا يعني دائمًا تكون مادة جديدة.'],
   [/صخر|معدن|زلزال|صفائح|مناخ|فضاء|موارد/,'تفسير ظاهرة في الأرض أو الفضاء وربط أسبابها بنتائجها أو بالأدلة المستخدمة في دراستها.','رتب السبب والعملية والنتيجة، وقارنها بالبيانات أو النموذج المعروض.','لا تخلط بين الطقس القصير المدى والمناخ طويل المدى.']
  ]
 };
 const fallback={reading:['فهم المهارة القرائية المحددة في المؤشر وتطبيقها على نص جديد.','اقرأ النص والسؤال معًا، وحدد الكلمة المفتاحية، ثم استبعد الاختيارات التي لا يدعمها النص.','اختر الإجابة التي يثبتها النص، لا الإجابة الممكنة في الحياة فقط.'],math:['فهم المهارة الرياضية المحددة في المؤشر وتطبيقها على مسألة جديدة.','حدد المعطيات والمطلوب، ثم اختر القاعدة المناسبة وتحقق من الناتج.','لا تبدأ بالحساب قبل فهم المطلوب ووحدة الإجابة.'],science:['فهم المفهوم العلمي المحدد في المؤشر وتطبيقه أو الاستدلال عليه من الأدلة.','حدد الظاهرة والمعطيات، ثم اختر التفسير الذي يوافق المفهوم العلمي.','ميّز بين الدليل العلمي والرأي أو التوقع.']};
 const match=(guides[subject]||[]).find(([pattern])=>pattern.test(text));
 const [meaning,method,warning]=match?match.slice(1):fallback[subject]||fallback.reading;
 return{meaning,method,warning};
}
const code=(s,o,i,m)=>`N3-${prefix[s]||'X'}-${String(o).replace(/[^0-9A-Za-z]/g,'')}-I${pad(i)}-M${pad(m)}`;
const url=(s,o,i,m)=>`${location.origin}${location.pathname.replace(/[^/]+$/,'')}exam.html?s=${encodeURIComponent(s)}&o=${encodeURIComponent(o)}&i=${i}&m=${m}`;
async function preview(s,o,i,m=1){const subj=getSubject(s),out=subj?.outcomes?.find(x=>x.code===o),indicatorText=out?.indicators?.[i-1]||'';try{const r=await fetch(EDGE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'preview',subject:s,outcome:o,indicator:i,model:m,indicator_text:indicatorText,outcome_title:out?.title||''})});return await r.json()}catch(e){return{ready:false,error:'تعذر الاتصال بمحرك الاختبارات'}}}
function ensureModal(){let x=document.getElementById('testModal');if(x)return x;x=document.createElement('div');x.id='testModal';x.className='modal-layer hidden';x.innerHTML='<div class="modal-card tests-modal"><button class="modal-close" type="button" aria-label="إغلاق">×</button><div id="testModalBody"></div></div>';document.body.appendChild(x);x.addEventListener('click',e=>{if(e.target===x||e.target.closest('.modal-close'))closeModels()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModels()});return x}
window.closeModels=()=>{const m=document.getElementById('testModal');if(m)m.classList.add('hidden')};
window.copyTestLink=async(s,o,i,m)=>{const u=url(s,o,i,m);try{await navigator.clipboard.writeText(u);toast('تم نسخ رابط الاختبار')}catch(_){prompt('انسخ الرابط:',u)}};
window.openQr=(s,o,i,m)=>{const u=url(s,o,i,m),c=code(s,o,i,m);let q=document.getElementById('qrLayer');if(!q){q=document.createElement('div');q.id='qrLayer';q.className='modal-layer hidden';q.innerHTML='<div class="modal-card qr-card"><button class="modal-close" type="button">×</button><div class="qr-title"></div><div id="qrBox"></div><div class="qr-code"></div><div class="qr-actions"></div></div>';document.body.appendChild(q);q.addEventListener('click',e=>{if(e.target===q||e.target.closest('.modal-close'))q.classList.add('hidden')})}q.querySelector('.qr-title').innerHTML='<b>باركود الاختبار</b><small>يفتح الاختبار نفسه، ويولّد المحرك نموذج أسئلة مختلفًا لكل طالب على المؤشر المحدد.</small>';q.querySelector('.qr-code').textContent=c;q.querySelector('.qr-actions').innerHTML=`<button onclick="copyTestLink('${s}','${o}',${i},${m})">نسخ الرابط</button><a href="${u}" target="_blank">فتح الاختبار</a>`;const box=q.querySelector('#qrBox');box.innerHTML='';if(window.QRCode)new QRCode(box,{text:u,width:210,height:210,colorDark:'#17324d',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});else box.innerHTML='<div class="qr-fallback">تعذر إنشاء الباركود بصريًا، استخدم الرابط.</div>';q.classList.remove('hidden')};
function toast(t){let x=document.getElementById('miniToast');if(!x){x=document.createElement('div');x.id='miniToast';x.className='mini-toast';document.body.appendChild(x)}x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
window.openNafesModels=async(s,o,i)=>{const subj=getSubject(s),out=subj?.outcomes?.find(x=>x.code===o),indicatorText=out?.indicators?.[i-1]||'',guide=indicatorGuide(s,indicatorText);const layer=ensureModal(),body=document.getElementById('testModalBody');layer.classList.remove('hidden');body.innerHTML='<div class="loading-box">جارٍ فحص محرك الاختبارات لهذا المؤشر...</div>';const p=await preview(s,o,i,1);const ready=!!p.ready;body.innerHTML=`<header class="tests-head"><span>نافس · ${esc(subj?.title||s)}</span><h3>${TESTS_PER_INDICATOR} اختبارات على المؤشر</h3><p>${esc(indicatorText)}</p><div class="bank-state ${ready?'ready':'building'}"><b>${ready?'الاختبارات جاهزة للتشغيل':'تعذر تجهيز الاختبارات لهذا المؤشر'}</b><span>${ready?`${p.settings?.question_count||15} سؤالًا في كل اختبار · ${p.settings?.duration_minutes||20} دقيقة`:(p.error||'راجع محرك الاختبارات')}</span></div></header><section class="indicator-guide"><div class="guide-title"><span>قبل أن تبدأ</span><h4>شرح المؤشر بطريقة مبسطة</h4></div><div class="guide-grid"><article><b>ماذا يعني؟</b><p>${esc(guide.meaning)}</p></article><article><b>كيف أجيب؟</b><p>${esc(guide.method)}</p></article><article class="guide-warning"><b>انتبه</b><p>${esc(guide.warning)}</p></article></div></section><div class="models-note"><b>الاختبارات الأربعة</b><span>كل اختبار يحتوي على ١٥ سؤالًا تقيس المؤشر نفسه، وتُحفظ نتيجة الطالب لقياس مستوى إتقانه وتحسنه بين الاختبارات.</span></div><div class="models-grid">${Array.from({length:TESTS_PER_INDICATOR},(_,k)=>{const m=k+1,u=url(s,o,i,m),c=code(s,o,i,m);return `<article class="model-card ${ready?'':'locked'}"><div class="model-no">${pad(m)}</div><div class="model-main"><b>اختبار ${pad(m)}</b><small>١٥ سؤالًا · ${c}</small></div><div class="model-actions"><button ${ready?'':'disabled'} onclick="openQr('${s}','${o}',${i},${m})">باركود</button><button ${ready?'':'disabled'} onclick="copyTestLink('${s}','${o}',${i},${m})">نسخ الرابط</button><a class="${ready?'':'disabled'}" href="${ready?u:'#'}" target="_blank">فتح</a></div>${ready?'':'<span class="lock-note">غير متاح بسبب خطأ في محرك المؤشر</span>'}</article>`}).join('')}</div>`};
})();
