(()=>{
const EDGE='https://udznpifopbnrcgxtpzza.supabase.co/functions/v1/nafes-exam';
const TESTS_PER_INDICATOR=4;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const prefix={reading:'R',math:'M',science:'S'};
const getSubject=k=>(window.NAFES_SUBJECTS||[]).find(s=>s.key===k);
function indicatorGuide(subject,text){
 const guides={
  reading:[
   [/معاني المفردات|الترادف، والتضاد/,'استنتاج معنى المفردة من قرائن السياق، وربطها بالترادف أو التضاد أو التمثيل المناسب.','اقرأ الجملة وما حولها، ثم اختبر كل معنى في موضع الكلمة واختر الأكثر اتساقًا.','لا تختَر المعنى الأشهر إذا كانت قرائن النص تدل على معنى آخر.'],
   [/التعريفات لمصطلحات/,'بناء تعريف لمصطلح جديد من صفاته ووظيفته والأمثلة التي يوردها النص.','اجمع ما يذكره النص عن المصطلح، ثم اختر تعريفًا يشمل صفاته الأساسية دون زيادة.','المرادف وحده لا يكون تعريفًا كاملًا إذا أغفل وظيفة المصطلح أو قيوده.'],
   [/يصنف المفردات/,'وضع المفردات في مجموعات دلالية وتحديد العلاقة بينها، مثل الترادف والتضاد والمشكلة والحل.','ابحث عن المعنى المشترك أو نوع الصلة بين الكلمات، ثم اختر التصنيف الذي يشملها جميعًا.','تشابه ورود الكلمات في فقرة واحدة لا يعني أنها تنتمي إلى التصنيف نفسه.'],
   [/يميز المفردات المختلفة/,'تمييز الفروق الدقيقة بين الألفاظ المتقاربة، وتحديد معنى اللفظ المتعدد بحسب سياقه.','قارن القيود التي يضيفها السياق إلى كل لفظ، ولاحظ ما يتغير عند استبداله بغيره.','تقارب المعنى لا يعني إمكان استبدال لفظين في كل سياق.'],
   [/يوظف المفردات الجديدة/,'استخدام المفردة الجديدة أو المتعددة المعاني في موقف جديد مع الحفاظ على دلالتها الدقيقة.','حدد معنى المفردة أولًا، ثم اختر الجملة أو الحل الذي يستخدمها في موضع مناسب.','تكرار المفردة في جملة لا يعد توظيفًا صحيحًا إذا تغير معناها أو اختل السياق.'],
   [/الأفكار الرئيسة والفرعية/,'تمييز الفكرة التي تجمع النص من التفاصيل التي تشرحها، وتحليل ترتيب الأفكار والأدلة.','اسأل: عم يتحدث النص كله؟ ثم صنف ما تحته إلى تفاصيل وأمثلة وأدلة بحسب وظيفتها.','لا تختَر مثالًا صحيحًا أو تفصيلًا محدودًا على أنه الفكرة الرئيسة.'],
   [/معلومات النص غير المباشرة/,'استخراج ما يفهم من النص دون أن يذكر حرفيًا، وتكوين أسئلة توضيحية وتعليلية واستنتاجية ونقدية.','اربط بين قرينتين أو أكثر، وحدد نوع السؤال المطلوب قبل اختيار الإجابة.','لا تجعل معرفتك الخارجية بديلًا عن القرائن الموجودة في النص.'],
   [/نقاط التشابه والاختلاف|يقارن بين نصين/,'مقارنة نصين وفق معايير محددة: القضية والأمثلة وقوة الأدلة واللغة والأسلوب.','أنشئ ذهنيًا عمودًا لكل نص، ثم قارن العنصر نفسه في العمودين.','اتفاق النصين في الموضوع لا يعني اتفاقهما في الموقف أو قوة الدليل.'],
   [/الحقائق والآراء/,'التمييز بين الحقيقة القابلة للتحقق والرأي الذي يعبر عن حكم، وبين المباشر والمستنتج.','اسأل هل يمكن فحص مصدر العبارة؟ ثم حدد هل صرح بها النص أم فهمت من قرائنه.','نبرة الكاتب الواثقة لا تحول الرأي إلى حقيقة.'],
   [/العلاقات والروابط/,'تفسير الروابط بين أجزاء النص، مثل السبب والنتيجة والمشكلة والحل والدليل والاستنتاج، ثم نقلها إلى موقف حياتي.','حدد طرفي العلاقة واتجاهها، وابحث عن القرينة التي تبين كيف يقود أحدهما إلى الآخر.','لا تعكس اتجاه العلاقة؛ فالنتيجة ليست سببًا لمجرد أنها وردت قبله في السؤال.'],
   [/مشاعر ودوافع الكاتب/,'استنتاج المشاعر والدوافع من التعابير، وتقويم اختيار التراكيب، وإضافة تعبير مناسب من إنشاء الطالب.','حدد العبارة الدالة، واربط اللفظ أو الحركة بالسياق قبل الحكم على الشعور أو الدافع.','لا تنسب شعورًا أو دافعًا إلى الكاتب أو الشخصية من غير تعبير يؤيده.'],
   [/مصداقيتها واكتمالها/,'تقويم مصداقية أفكار النص واكتمالها، وتفنيد الاتجاهات الضعيفة واقتراح بدائل تطور الحل.','افحص مصدر الدليل وحدود القياس وما ينقص التنفيذ، ثم اختر حكمًا متزنًا وبديلًا قابلًا للفحص.','وجود نقص في تفصيل لا يبرر قبول النص كله أو رفضه كله بلا تعليل.'],
   [/القيم والاتجاهات/,'تحديد القيمة التي يتبناها النص، وتقويم أثرها على الفرد والمجتمع وربطها بسلوك واقعي.','استخرج السلوك الذي يجسد القيمة، ثم تتبع أثره الفردي والاجتماعي.','ذكر اسم القيمة لا يكفي؛ المطلوب بيان سلوكها وأثرها.'],
   [/الحجج والبراهين/,'استخراج الحجة ومقدماتها وبراهينها، وتقويم قوتها ودعمها بدليل مناسب من خارج النص.','اربط كل دليل بالادعاء الذي يسنده، ثم افحص صلته وكفايته وحدود تعميمه.','المثال الفردي أو الأسلوب الواثق لا يكفيان وحدهما برهانًا عامًا.'],
   [/يلخص النص/,'اختصار النص وإعادة صياغته وتنظيم أفكاره مع الحفاظ على المعنى الرئيس والعلاقات المهمة.','احذف التكرار والتفاصيل الثانوية، ثم رتب القضية والمشكلة والدليل والحل والنتيجة بأسلوبك.','التلخيص ليس نسخ أول فقرة ولا اختزال النص في مثال واحد.'],
   [/مشكلة من واقعه|حل مشكلات فردية/,'نقل طريقة معالجة المشكلة في النص إلى موقف واقعي، واختيار حل علمي أو إبداعي قابل للتجربة والتقويم.','عرّف المشكلة، واجمع دليلًا، وقارن بدائل، ثم اختر حلًا بمعيار نجاح واضح.','لا تنسخ تفاصيل حل النص حرفيًا إذا اختلفت ظروف المشكلة الجديدة.']
  ],
  math:[
   [/معادلة|متباينة|نظام|دالة|عبارات جبرية|تحليل/,'فهم العلاقة الجبرية واختيار القاعدة المناسبة ثم تنفيذ الخطوات والتحقق من الناتج.','حدد المعطيات والمطلوب، ونفّذ العمليات العكسية بترتيب واضح.','لا تغيّر طرفًا من العلاقة دون إجراء التغيير نفسه على الطرف الآخر.'],
   [/هندس|مثلث|مضلع|زاوية|دائرة|محيط|مساحة|حجم|تحويل/,'استخدام خصائص الأشكال والعلاقات الهندسية لحساب قياس أو تفسير تحول.','ارسم شكلًا مبسطًا، ودوّن القياسات، ثم اختر القانون المناسب.','ميّز بين المحيط والمساحة والحجم ووحدات كل منها.'],
   [/احتمال|عينة|بيانات|تمثيل|متوسط|وسيط|منوال|تشتت/,'قراءة البيانات أو تنظيمها واختيار المقياس أو التمثيل الذي يجيب عن السؤال.','حدد نوع البيانات وما المطلوب مقارنته قبل الحساب أو اختيار الرسم.','لا تحكم من قيمة واحدة إذا كان السؤال عن مجموعة البيانات كلها.'],
   [/نسبة|معدل|تناسب|مئوية|أسس|جذر|أعداد/,'اختيار العملية العددية المناسبة وتمثيل العلاقة بصورة صحيحة.','حوّل المعطيات إلى أعداد أو نسب متكافئة، ثم تحقق من معقولية الناتج.','انتبه إلى الإشارة ووحدة القياس وترتيب العمليات.']
  ],
  science:[
   [/تجربة|استقصاء|فرضية|متغير|بيانات|دليل|استنتاج/,'قراءة موقف علمي وتحديد الدليل أو المتغير أو الاستنتاج الذي تدعمه البيانات.','افصل بين الملاحظة والتفسير، ثم اربط النتيجة بالبيانات المعروضة.','لا تعد التوقع دليلًا، ولا تستنتج أكثر مما تسمح به البيانات.'],
   [/قوة|حركة|سرعة|تسارع|طاقة|كهرب|موج|ضوء|صوت|حرارة/,'تطبيق المفهوم الفيزيائي المناسب على موقف أو بيانات، مع الانتباه إلى العلاقة بين الكميات.','حدد الكميات ووحداتها، ثم اختر القانون أو العلاقة التي تربطها.','لا تستخدم قانونًا لمجرد وجود أرقام؛ تحقق أولًا من أنه يقيس المطلوب.'],
   [/خلية|وراث|جهاز|مخلوق|بيئ|تنوع|دورة/,'تفسير بنية أو عملية حيوية وربطها بوظيفتها أو أثرها في النظام الحي.','حدد الجزء أو العملية، ثم تتبع وظيفتها وما ينتج عنها.','لا تخلط بين وصف البنية وشرح وظيفتها.'],
   [/ذرة|عنصر|مركب|تفاعل|حمض|قاعدة|مادة/,'تمييز خصائص المادة أو تفسير تغيرها باستخدام نموذج أو دليل كيميائي مناسب.','حدد المواد قبل التغير وبعده، وابحث عن دليل يميز التغير الفيزيائي من الكيميائي.','تغير الشكل أو الحالة لا يعني دائمًا تكون مادة جديدة.'],
   [/صخر|معدن|زلزال|صفائح|مناخ|فضاء|موارد/,'تفسير ظاهرة في الأرض أو الفضاء وربط أسبابها بنتائجها أو بالأدلة المستخدمة في دراستها.','رتب السبب والعملية والنتيجة، وقارنها بالبيانات أو النموذج المعروض.','لا تخلط بين الطقس القصير المدى والمناخ طويل المدى.']
  ]
 };
 const fallback={reading:['فهم المهارة القرائية المحددة في المؤشر وتطبيقها على نص جديد.','اقرأ النص والسؤال معًا، وحدد الكلمة المفتاحية، ثم استبعد الاختيارات التي لا يدعمها النص.','اختر الإجابة التي يثبتها النص، لا الإجابة الممكنة في الحياة فقط.'],math:['فهم المهارة الرياضية المحددة في المؤشر وتطبيقها على مسألة جديدة.','حدد المعطيات والمطلوب، ثم اختر القاعدة المناسبة وتحقق من الناتج.','لا تبدأ بالحساب قبل فهم المطلوب ووحدة الإجابة.'],science:['فهم المفهوم العلمي المحدد في المؤشر وتطبيقه أو الاستدلال عليه من الأدلة.','حدد الظاهرة والمعطيات، ثم اختر التفسير الذي يوافق المفهوم العلمي.','ميّز بين الدليل العلمي والرأي أو التوقع.']};
 const match=(guides[subject]||[]).find(([pattern])=>pattern.test(text));
 const [meaning,method,warning]=match?match.slice(1):fallback[subject]||fallback.reading;
 return{meaning,method,warning};
}
const code=(s,o,i,m)=>`N3-${prefix[s]||'X'}-${String(o).replace(/[^0-9A-Za-z]/g,'')}-I${pad(i)}-M${pad(m)}`;
const url=(s,o,i,m)=>`${location.origin}${location.pathname.replace(/[^/]+$/,'')}exam.html?s=${encodeURIComponent(s)}&o=${encodeURIComponent(o)}&i=${i}&m=${m}`;
async function preview(s,o,i,m=1){const subj=getSubject(s),out=subj?.outcomes?.find(x=>x.code===o),indicatorText=out?.indicators?.[i-1]||'';try{const r=await fetch(EDGE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'preview',subject:s,outcome:o,indicator:i,model:m,indicator_text:indicatorText,outcome_title:out?.title||''})});return await r.json()}catch(e){return{ready:false,error:'تعذر الاتصال بمحرك الاختبارات'}}}
function ensureModal(){let x=document.getElementById('testModal');if(x)return x;x=document.createElement('div');x.id='testModal';x.className='modal-layer hidden';x.innerHTML='<div class="modal-card tests-modal"><button class="modal-close" type="button" aria-label="إغلاق">×</button><div id="testModalBody"></div></div>';document.body.appendChild(x);x.addEventListener('click',e=>{if(e.target===x||e.target.closest('.modal-close'))closeModels()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModels()});return x}
window.closeModels=()=>{const m=document.getElementById('testModal');if(m)m.classList.add('hidden')};
window.copyTestLink=async(s,o,i,m)=>{const u=url(s,o,i,m);try{await navigator.clipboard.writeText(u);toast('تم نسخ رابط الاختبار')}catch(_){prompt('انسخ الرابط:',u)}};
window.openQr=(s,o,i,m)=>{const u=url(s,o,i,m),c=code(s,o,i,m);let q=document.getElementById('qrLayer');if(!q){q=document.createElement('div');q.id='qrLayer';q.className='modal-layer hidden';q.innerHTML='<div class="modal-card qr-card"><button class="modal-close" type="button">×</button><div class="qr-title"></div><div id="qrBox"></div><div class="qr-code"></div><div class="qr-actions"></div></div>';document.body.appendChild(q);q.addEventListener('click',e=>{if(e.target===q||e.target.closest('.modal-close'))q.classList.add('hidden')})}q.querySelector('.qr-title').innerHTML='<b>باركود الاختبار</b><small>يفتح الاختبار نفسه، ويولّد المحرك نموذج أسئلة مختلفًا لكل طالب على المؤشر المحدد.</small>';q.querySelector('.qr-code').textContent=c;q.querySelector('.qr-actions').innerHTML=`<button onclick="copyTestLink('${s}','${o}',${i},${m})">نسخ الرابط</button><a href="${u}" target="_blank">فتح الاختبار</a>`;const box=q.querySelector('#qrBox');box.innerHTML='';if(window.QRCode)new QRCode(box,{text:u,width:210,height:210,colorDark:'#17324d',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});else box.innerHTML='<div class="qr-fallback">تعذر إنشاء الباركود بصريًا، استخدم الرابط.</div>';q.classList.remove('hidden')};
function toast(t){let x=document.getElementById('miniToast');if(!x){x=document.createElement('div');x.id='miniToast';x.className='mini-toast';document.body.appendChild(x)}x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
window.openNafesModels=async(s,o,i)=>{const subj=getSubject(s),out=subj?.outcomes?.find(x=>x.code===o),indicatorText=out?.indicators?.[i-1]||'',guide=indicatorGuide(s,indicatorText);const layer=ensureModal(),body=document.getElementById('testModalBody');layer.classList.remove('hidden');body.innerHTML='<div class="loading-box">جارٍ فحص محرك الاختبارات لهذا المؤشر...</div>';const p=await preview(s,o,i,1);const ready=!!p.ready;body.innerHTML=`<header class="tests-head"><span>نافس · ${esc(subj?.title||s)}</span><h3>${TESTS_PER_INDICATOR} اختبارات على المؤشر</h3><p>${esc(indicatorText)}</p><div class="bank-state ${ready?'ready':'building'}"><b>${ready?'الاختبارات جاهزة للتشغيل':'تعذر تجهيز الاختبارات لهذا المؤشر'}</b><span>${ready?`${p.settings?.question_count||15} سؤالًا في كل اختبار · ${p.settings?.duration_minutes||20} دقيقة`:(p.error||'راجع محرك الاختبارات')}</span></div></header><section class="indicator-guide"><div class="guide-title"><span>قبل أن تبدأ</span><h4>شرح المؤشر بطريقة مبسطة</h4></div><div class="guide-grid"><article><b>ماذا يعني؟</b><p>${esc(guide.meaning)}</p></article><article><b>كيف أجيب؟</b><p>${esc(guide.method)}</p></article><article class="guide-warning"><b>انتبه</b><p>${esc(guide.warning)}</p></article></div></section><div class="models-note"><b>الاختبارات الأربعة</b><span>كل اختبار يحتوي على ١٥ سؤالًا تقيس المؤشر نفسه، وتُحفظ نتيجة الطالب لقياس مستوى إتقانه وتحسنه بين الاختبارات.</span></div><div class="models-grid">${Array.from({length:TESTS_PER_INDICATOR},(_,k)=>{const m=k+1,u=url(s,o,i,m),c=code(s,o,i,m);return `<article class="model-card ${ready?'':'locked'}"><div class="model-no">${pad(m)}</div><div class="model-main"><b>اختبار ${pad(m)}</b><small>١٥ سؤالًا · ${c}</small></div><div class="model-actions"><button ${ready?'':'disabled'} onclick="openQr('${s}','${o}',${i},${m})">باركود</button><button ${ready?'':'disabled'} onclick="copyTestLink('${s}','${o}',${i},${m})">نسخ الرابط</button><a class="${ready?'':'disabled'}" href="${ready?u:'#'}" target="_blank">فتح</a></div>${ready?'':'<span class="lock-note">غير متاح بسبب خطأ في محرك المؤشر</span>'}</article>`}).join('')}</div>`};
})();
