-- 001_course_mastery_schema.sql
-- Additive migration for standalone "لغتي الخالدة" project.
-- Existing tables/data are preserved.

create table if not exists public.course_units (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  unit_order integer not null unique check (unit_order > 0),
  title text not null,
  goal text not null,
  expected_outcome text,
  measurable_objectives jsonb not null default '[]'::jsonb,
  mastery_threshold integer not null default 85 check (mastery_threshold between 0 and 100),
  minimum_core_objective_percent integer not null default 80 check (minimum_core_objective_percent between 0 and 100),
  is_published boolean not null default true,
  content_version text not null default 'curriculum-v1',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lesson_blueprints (
  lesson_id uuid primary key references public.lessons(id) on delete cascade,
  unit_code text not null references public.course_units(code) on update cascade,
  lesson_order integer not null check (lesson_order >= 0),
  summary text not null default '',
  estimated_minutes integer check (estimated_minutes is null or estimated_minutes > 0),
  difficulty text not null default 'متوسط',
  objectives jsonb not null default '[]'::jsonb,
  prerequisites jsonb not null default '[]'::jsonb,
  learning_points jsonb not null default '[]'::jsonb,
  activities jsonb not null default '[]'::jsonb,
  resources jsonb not null default '[]'::jsonb,
  assessment jsonb not null default '{}'::jsonb,
  expected_outcome text,
  is_core boolean not null default true,
  ready_for_publish boolean not null default false,
  version text not null default 'curriculum-v1',
  updated_at timestamptz not null default now(),
  unique(unit_code, lesson_order)
);

create table if not exists public.student_point_mastery (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.app_accounts(id) on delete cascade,
  lesson_id uuid not null references public.lessons(id) on delete cascade,
  point_key text not null,
  status text not null default 'not_started'
    check (status in ('not_started','learning','checking','needs_remediation','retry_ready','mastered')),
  correct_count integer not null default 0 check (correct_count >= 0),
  checked_count integer not null default 0 check (checked_count >= 0),
  wrong_count integer not null default 0 check (wrong_count >= 0),
  last_variant_group text,
  mastered_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(student_id, lesson_id, point_key)
);

create table if not exists public.student_attempts (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.app_accounts(id) on delete cascade,
  lesson_id uuid not null references public.lessons(id) on delete cascade,
  point_key text,
  question_key text not null,
  variant_group text,
  cognitive_level text check (cognitive_level is null or cognitive_level in ('knowledge','application','reasoning','performance')),
  selected_answer jsonb not null default '{}'::jsonb,
  correct boolean,
  answer_revealed boolean not null default false,
  counts_for_mastery boolean not null default true,
  elapsed_ms integer check (elapsed_ms is null or elapsed_ms >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.remediation_events (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.app_accounts(id) on delete cascade,
  lesson_id uuid not null references public.lessons(id) on delete cascade,
  point_key text not null,
  trigger_wrong_count integer not null default 0,
  remediation_type text not null default 'micro_remediation',
  status text not null default 'started' check (status in ('started','completed','abandoned')),
  payload jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.student_unit_mastery (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.app_accounts(id) on delete cascade,
  unit_code text not null references public.course_units(code) on update cascade,
  lesson_mastery_percent numeric(5,2),
  unit_final_percent numeric(5,2),
  core_objectives_ok boolean not null default false,
  performance_passed boolean not null default false,
  status text not null default 'in_progress' check (status in ('locked','available','in_progress','needs_support','mastered')),
  mastered_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(student_id, unit_code)
);

create table if not exists public.performance_rubric_scores (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.app_accounts(id) on delete cascade,
  lesson_id uuid not null references public.lessons(id) on delete cascade,
  rubric_id text not null,
  criterion_key text not null,
  score integer not null check (score between 0 and 4),
  is_core boolean not null default true,
  teacher_id uuid references public.app_accounts(id) on delete set null,
  note text,
  created_at timestamptz not null default now(),
  unique(student_id, lesson_id, rubric_id, criterion_key)
);

create index if not exists idx_lesson_blueprints_unit on public.lesson_blueprints(unit_code, lesson_order);
create index if not exists idx_point_mastery_student on public.student_point_mastery(student_id, lesson_id);
create index if not exists idx_attempts_student_lesson on public.student_attempts(student_id, lesson_id, created_at desc);
create index if not exists idx_attempts_point on public.student_attempts(student_id, lesson_id, point_key, created_at desc);
create index if not exists idx_remediation_student on public.remediation_events(student_id, lesson_id, point_key, started_at desc);
create index if not exists idx_unit_mastery_student on public.student_unit_mastery(student_id, unit_code);
create index if not exists idx_rubric_scores_student_lesson on public.performance_rubric_scores(student_id, lesson_id);

alter table public.course_units enable row level security;
alter table public.lesson_blueprints enable row level security;
alter table public.student_point_mastery enable row level security;
alter table public.student_attempts enable row level security;
alter table public.remediation_events enable row level security;
alter table public.student_unit_mastery enable row level security;
alter table public.performance_rubric_scores enable row level security;

comment on table public.lesson_blueprints is 'Instructional design source for each Lugati Eternal lesson; served through the authenticated Edge Function.';
comment on table public.student_attempts is 'Server-side audit trail for mastery checks. Do not expose correct answers to clients.';
comment on table public.student_point_mastery is 'Per-student mastery state for each micro learning point.';
