import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const db = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const allowedOrigins = new Set(["https://zarie19991-bit.github.io","http://localhost:8000","http://127.0.0.1:8000","http://localhost:5500","http://127.0.0.1:5500","https://skyblue-cheetah-940953.hostingersite.com"]);
function cors(req: Request) { const origin=req.headers.get("origin")||""; const allow=allowedOrigins.has(origin)?origin:"https://zarie19991-bit.github.io"; return {"Access-Control-Allow-Origin":allow,"Access-Control-Allow-Headers":"content-type,authorization,x-teacher-key","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","Vary":"Origin"}; }
const json=(req:Request,body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors(req)});
const tidy=(v:unknown)=>String(v??"").trim();
async function sha256(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes)).map(x=>x.toString(16).padStart(2,"0")).join("");}

type SubjectScope="all"|"reading"|"math"|"science";
type Access={role:"teacher"|"student";student_id?:string;teacher_access_id?:string;subject_scope?:SubjectScope};
const scopeOf=(a:Access):SubjectScope=>a.role==="teacher"?(a.subject_scope||"all"):"all";
const scopeAllows=(a:Access,s:unknown)=>a.role!=="teacher"||scopeOf(a)==="all"||scopeOf(a)===tidy(s);
const scopeRows=(a:Access,rows:any[])=>a.role==="teacher"&&scopeOf(a)!=="all"?rows.filter(r=>tidy(r?.subject_key)===scopeOf(a)):rows;
async function accessFromSession(req:Request):Promise<Access|null>{
 const auth=tidy(req.headers.get("authorization")); const token=auth.toLowerCase().startsWith("bearer ")?auth.slice(7).trim():""; if(!token)return null;
 const {data:s,error}=await db.from("lugati_sessions").select("id,role,student_id,teacher_access_id,expires_at").eq("token_hash",await sha256(token)).gt("expires_at",new Date().toISOString()).maybeSingle();
 if(error)throw error; if(!s)throw Object.assign(new Error("انتهت جلسة الدخول أو أصبحت غير صالحة."),{status:401});
 if(s.role==="student"){const {data:u,error:e}=await db.from("nafes_students").select("id,is_active").eq("id",s.student_id).eq("is_active",true).maybeSingle();if(e)throw e;if(!u)throw Object.assign(new Error("حساب الطالب غير متاح."),{status:401});return{role:"student",student_id:String(u.id)}}
 const {data:t,error:te}=await db.from("nafes_teacher_access").select("id,active,subject_scope").eq("id",s.teacher_access_id).eq("active",true).maybeSingle();if(te)throw te;if(!t)throw Object.assign(new Error("حساب المعلم غير متاح."),{status:401});return{role:"teacher",teacher_access_id:String(t.id),subject_scope:(["reading","math","science"].includes(String(t.subject_scope))?String(t.subject_scope):"all") as SubjectScope};
}
async function accessFromLegacyTeacherKey(req:Request):Promise<Access|null>{const key=tidy(req.headers.get("x-teacher-key"));if(!key)return null;if(!/^[a-f0-9]{48,96}$/i.test(key))throw Object.assign(new Error("مفتاح دخول المعلم غير صحيح."),{status:401});const {data,error}=await db.from("nafes_teacher_access").select("id,subject_scope").eq("key_hash",await sha256(key)).eq("active",true).maybeSingle();if(error)throw error;if(!data)throw Object.assign(new Error("مفتاح دخول المعلم غير صحيح."),{status:401});return{role:"teacher",teacher_access_id:String(data.id),subject_scope:(["reading","math","science"].includes(String(data.subject_scope))?String(data.subject_scope):"all") as SubjectScope}}
async function requireAccess(req:Request){return(await accessFromSession(req))||(await accessFromLegacyTeacherKey(req))||(()=>{throw Object.assign(new Error("تسجيل الدخول مطلوب."),{status:401})})()}
async function studentsMap(ids:string[]){const unique=[...new Set(ids.filter(Boolean))],map=new Map<string,any>();for(let i=0;i<unique.length;i+=200){const {data,error}=await db.from("nafes_students").select("id,full_name,class_name,grade,is_active,is_demo").in("id",unique.slice(i,i+200));if(error)throw error;for(const r of data||[])map.set(String(r.id),r)}return map}
async function roster(req:Request,access:Access){let q=db.from("nafes_students").select("id,full_name,class_name,grade,is_active,is_demo").eq("is_active",true).order("class_name",{ascending:true}).order("full_name",{ascending:true});if(access.role==="student")q=q.eq("id",access.student_id!);else q=q.eq("is_demo",false);const {data,error}=await q;if(error)throw error;return json(req,{ok:true,mode:"read_only",students:(data||[]).map((s:any)=>({id:s.id,full_name:s.full_name,class_name:s.class_name,grade:s.grade}))})}
function normalizedSections(row:any){return(Array.isArray(row?.section_scores)?row.section_scores:[]).map((s:any)=>({subject_key:tidy(s?.subject||s?.subject_key),score:Number(s?.score??0),total:Number(s?.total??0),percent:Number(s?.percent??0)})).filter((s:any)=>["reading","math","science"].includes(s.subject_key)&&Number.isFinite(s.percent))}
async function loadSubmitted(access:Access,limit=1000){let a=db.from("nafes_assessment_attempts").select("id,assessment_id,student_id,score,total,percent,section_scores,submitted_at").not("submitted_at","is",null).order("submitted_at",{ascending:false}).limit(limit),s=db.from("nafes_simulation_attempts").select("id,simulation_key,student_id,score,total,percent,section_scores,submitted_at").not("submitted_at","is",null).order("submitted_at",{ascending:false}).limit(limit),e=db.from("nafes_exam_attempts").select("id,subject_key,outcome_code,indicator_index,model_no,student_id,score,percent,rendered_questions,submitted_at").not("submitted_at","is",null).order("submitted_at",{ascending:false}).limit(limit);if(access.role==="student"){a=a.eq("student_id",access.student_id!);s=s.eq("student_id",access.student_id!);e=e.eq("student_id",access.student_id!)}const [ar,sr,er]=await Promise.all([a,s,e]);if(ar.error)throw ar.error;if(sr.error)throw sr.error;if(er.error)throw er.error;return{assessment:ar.data||[],simulation:sr.data||[],exam:er.data||[]}}
function normalizeRows(raw:any){const rows:any[]=[];for(const r of raw.assessment){const sections=normalizedSections(r);if(sections.length)for(const x of sections)rows.push({source:"assessment",id:r.id,test_id:r.assessment_id,student_id:r.student_id,subject_key:x.subject_key,score:x.score,total:x.total,percent:x.percent,submitted_at:r.submitted_at,indicator_index:null,outcome_code:null});else if(Number.isFinite(Number(r.percent)))rows.push({source:"assessment",id:r.id,test_id:r.assessment_id,student_id:r.student_id,subject_key:null,score:Number(r.score||0),total:Number(r.total||0),percent:Number(r.percent||0),submitted_at:r.submitted_at,indicator_index:null,outcome_code:null})}for(const r of raw.simulation){const sections=normalizedSections(r);if(sections.length)for(const x of sections)rows.push({source:"simulation",id:r.id,test_id:`simulation:${r.simulation_key}`,student_id:r.student_id,subject_key:x.subject_key,score:x.score,total:x.total,percent:x.percent,submitted_at:r.submitted_at,indicator_index:null,outcome_code:null});else if(Number.isFinite(Number(r.percent)))rows.push({source:"simulation",id:r.id,test_id:`simulation:${r.simulation_key}`,student_id:r.student_id,subject_key:null,score:Number(r.score||0),total:Number(r.total||0),percent:Number(r.percent||0),submitted_at:r.submitted_at,indicator_index:null,outcome_code:null})}for(const r of raw.exam)rows.push({source:"exam",id:r.id,test_id:`exam:${r.subject_key}:${r.outcome_code}:i${r.indicator_index}:m${r.model_no}`,student_id:r.student_id,subject_key:r.subject_key,outcome_code:r.outcome_code,indicator_index:r.indicator_index,model_no:r.model_no,score:Number(r.score||0),total:Array.isArray(r.rendered_questions)?r.rendered_questions.length:15,percent:Number(r.percent||0),submitted_at:r.submitted_at});return rows.sort((x,y)=>String(y.submitted_at||"").localeCompare(String(x.submitted_at||"")))}
async function enrichRows(rows:any[]){const sm=await studentsMap(rows.map(r=>String(r.student_id||"")));return rows.map(r=>{const s=sm.get(String(r.student_id||""));return{...r,student_name:s?.full_name||null,class_name:s?.class_name||null,grade:s?.grade||null,is_demo:s?.is_demo===true}})}
function latestPerStudentSubject(rows:any[]){const m=new Map<string,any>();for(const r of rows){if(!r.student_id||!r.subject_key)continue;const k=`${r.student_id}::${r.subject_key}`;if(!m.has(k))m.set(k,r)}return[...m.values()]}
function subjectSummary(rows:any[],subject:string){const relevant=rows.filter(r=>r.subject_key===subject),latest=latestPerStudentSubject(relevant),avg=latest.length?latest.reduce((a,r)=>a+Number(r.percent||0),0)/latest.length:null;return{attempts:relevant.length,students:new Set(relevant.map(r=>r.student_id).filter(Boolean)).size,latest_students:latest.length,average_percent:avg==null?null:Math.round(avg*10)/10,support_students:latest.filter(r=>Number(r.percent)<70).length,strengthening_students:latest.filter(r=>Number(r.percent)>=70&&Number(r.percent)<90).length,enrichment_students:latest.filter(r=>Number(r.percent)>=90).length}}
function performanceFromAssessment(r:any){const answers=(r?.answers&&typeof r.answers==="object")?r.answers:{};const groups=new Map<string,any>();for(const sec of(Array.isArray(r?.rendered_sections)?r.rendered_sections:[])){for(const q of(Array.isArray(sec?.questions)?sec.questions:[])){const subject=tidy(q?.subject||sec?.subject),outcome=tidy(q?.outcome),indicator=Number(q?.indicator||0),key=tidy(q?.indicator_key)||`${subject}:${outcome}:i${indicator}`;if(!subject||!indicator||!q?.id)continue;if(!groups.has(key))groups.set(key,{key,subject_key:subject,outcome_code:outcome,indicator_index:indicator,indicator_text:tidy(q?.indicator_text),correct:0,total:0});const g=groups.get(key);g.total++;if(Number(answers[q.id])===Number(q.correctIndex))g.correct++}}return[...groups.values()].map(g=>({...g,student_id:r.student_id,source:"assessment",attempt_id:r.id,submitted_at:r.submitted_at,percent:g.total?Math.round((g.correct/g.total)*1000)/10:0}))}
function performanceFromExam(r:any){const answers=(r?.answers&&typeof r.answers==="object")?r.answers:{},qs=Array.isArray(r?.rendered_questions)?r.rendered_questions:[],groups=new Map<string,any>();for(const q of qs){const subject=tidy(q?.subject||r.subject_key),outcome=tidy(q?.outcome||r.outcome_code),indicator=Number(q?.indicator||r.indicator_index||0),key=tidy(q?.indicator_key)||`${subject}:${outcome}:i${indicator}`;if(!subject||!indicator||!q?.id)continue;if(!groups.has(key))groups.set(key,{key,subject_key:subject,outcome_code:outcome,indicator_index:indicator,indicator_text:tidy(q?.indicator_text),correct:0,total:0});const g=groups.get(key);g.total++;if(Number(answers[q.id])===Number(q.correctIndex))g.correct++}return[...groups.values()].map(g=>({...g,student_id:r.student_id,source:"exam",attempt_id:r.id,submitted_at:r.submitted_at,percent:g.total?Math.round((g.correct/g.total)*1000)/10:Number(r.percent||0)}))}
async function indicatorSummary(access:Access){
 const {data,error}=await db.rpc("lugati_indicator_plan_rows",{p_student_id:access.role==="student"?access.student_id:null});
 if(error)throw error;
 let latest=scopeRows(access,(data||[]).map((p:any)=>({...p,percent:Number(p.percent||0)})));
 const sm=await studentsMap(latest.map((p:any)=>String(p.student_id||"")));
 if(access.role==="teacher")latest=latest.filter((p:any)=>sm.get(String(p.student_id||""))?.is_demo!==true);
 for(const p of latest){
   const s=sm.get(String(p.student_id||""));
   p.student_name=s?.full_name||null;
   p.class_name=s?.class_name||null;
 }
 let rosterCount=1;
 if(access.role==="teacher"){
   const {count,error:ce}=await db.from("nafes_students").select("id",{count:"exact",head:true}).eq("is_active",true).eq("is_demo",false);
   if(ce)throw ce;rosterCount=Number(count||0);
 }
 const agg=new Map<string,any>();
 for(const p of latest){
   const key=`${p.subject_key}:${p.outcome_code}:i${p.indicator_index}`;
   if(!agg.has(key))agg.set(key,{
     key,subject_key:p.subject_key,outcome_code:p.outcome_code,
     indicator_index:Number(p.indicator_index),indicator_text:p.indicator_text||"",
     tested_students:0,sum:0,tested_support_students:0,strengthening_students:0,enrichment_students:0
   });
   const g=agg.get(key),pc=Number(p.percent||0);
   g.tested_students++;g.sum+=pc;
   if(pc<70)g.tested_support_students++;else if(pc<90)g.strengthening_students++;else g.enrichment_students++;
 }
 const all=[...agg.values()].map(g=>{
   const missing=access.role==="teacher"?Math.max(0,rosterCount-g.tested_students):0;
   return{
     key:g.key,subject_key:g.subject_key,outcome_code:g.outcome_code,
     indicator_index:g.indicator_index,indicator_text:g.indicator_text,
     students:access.role==="teacher"?rosterCount:g.tested_students,
     students_with_result:g.tested_students,
     students_without_result:missing,
     tested_support_students:g.tested_support_students,
     support_students:g.tested_support_students,
     strengthening_students:g.strengthening_students,
     enrichment_students:g.enrichment_students,
     average_percent:g.tested_students?Math.round((g.sum/g.tested_students)*10)/10:null
   };
 });
 const bySubject:any={reading:[],math:[],science:[]};
 for(const g of all)if(bySubject[g.subject_key])bySubject[g.subject_key].push(g);
 for(const k of Object.keys(bySubject))bySubject[k].sort((x:any,y:any)=>Number(x.average_percent??999)-Number(y.average_percent??999));
 const studentRows=access.role==="student"
   ? latest.sort((x:any,y:any)=>x.percent-y.percent)
   : [];
 return {by_subject:bySubject,latest_student_indicators:studentRows};
}
async function summary(req:Request,access:Access){const raw=await loadSubmitted(access,1000),allRows=scopeRows(access,await enrichRows(normalizeRows(raw))),rows=access.role==="teacher"?allRows.filter((r:any)=>r.is_demo!==true):allRows,latest=latestPerStudentSubject(rows),overall=latest.length?latest.reduce((a,r)=>a+Number(r.percent||0),0)/latest.length:null,studentLatest=new Map<string,any>();for(const r of rows)if(r.student_id&&!studentLatest.has(String(r.student_id)))studentLatest.set(String(r.student_id),r);const indicators=await indicatorSummary(access);let rosterCount=studentLatest.size;if(access.role==="teacher"){const {count}=await db.from("nafes_students").select("id",{count:"exact",head:true}).eq("is_active",true).eq("is_demo",false);rosterCount=count||0}else rosterCount=1;return json(req,{ok:true,mode:"read_only",role:access.role,subject_scope:scopeOf(access),totals:{students:rosterCount,students_with_results:studentLatest.size,students_without_results:Math.max(0,rosterCount-studentLatest.size),normalized_results:rows.length,latest_subject_results:latest.length,overall_percent:overall==null?null:Math.round(overall*10)/10,support_results:latest.filter(r=>Number(r.percent)<70).length,enrichment_results:latest.filter(r=>Number(r.percent)>=90).length},subjects:{reading:subjectSummary(rows,"reading"),math:subjectSummary(rows,"math"),science:subjectSummary(rows,"science")},indicators,recent:rows.slice(0,8),needing_support:latest.filter(r=>Number(r.percent)<70).sort((a,b)=>Number(a.percent)-Number(b.percent)).slice(0,10)})}
async function grades(req:Request,body:any,access:Access){const n=Number(body?.limit??500),limit=Number.isFinite(n)?Math.max(1,Math.min(1000,Math.trunc(n))):500,subject=tidy(body?.subject_key),raw=await loadSubmitted(access,limit);let rows=scopeRows(access,await enrichRows(normalizeRows(raw)));if(access.role==="teacher")rows=rows.filter((r:any)=>r.is_demo!==true);if(subject){if(access.role==="teacher"&&scopeOf(access)!=="all"&&subject!==scopeOf(access))return json(req,{error:"هذه المادة خارج صلاحية حسابك."},403);rows=rows.filter(r=>r.subject_key===subject);}if(access.role==="teacher"){const sid=tidy(body?.student_id);if(sid)rows=rows.filter(r=>String(r.student_id)===sid)}return json(req,{ok:true,mode:"read_only",rows})}
async function attempt(req:Request,body:any,access:Access){const source=tidy(body?.source),id=tidy(body?.id);if(!id||!["assessment","simulation","exam"].includes(source))return json(req,{error:"حدد مصدر المحاولة ومعرّفها."},400);const spec:any={assessment:{table:"nafes_assessment_attempts",columns:"id,assessment_id,student_id,student_key,class_name,attempt_no,config,rendered_sections,answers,score,total,percent,section_scores,started_at,submitted_at"},simulation:{table:"nafes_simulation_attempts",columns:"id,simulation_key,student_id,student_key,config,rendered_sections,answers,score,total,percent,section_scores,started_at,submitted_at"},exam:{table:"nafes_exam_attempts",columns:"id,subject_key,outcome_code,indicator_index,model_no,student_id,student_key,question_ids,rendered_questions,answers,score,percent,started_at,submitted_at"}},item=spec[source],{data,error}=await db.from(item.table).select(item.columns).eq("id",id).maybeSingle();if(error)throw error;if(!data||!data.submitted_at)return json(req,{error:"المحاولة غير موجودة أو لم تُسلَّم بعد."},404);if(access.role==="student"&&String(data.student_id||"")!==access.student_id)return json(req,{error:"غير مصرح بعرض هذه المحاولة."},403);if(access.role==="teacher"&&scopeOf(access)!=="all"){const sc=scopeOf(access);if(source==="exam"&&tidy(data.subject_key)!==sc)return json(req,{error:"هذه المحاولة خارج مادة حسابك."},403);if(source!=="exam"){const sections=(Array.isArray(data.rendered_sections)?data.rendered_sections:[]).filter((sec:any)=>tidy(sec?.subject||sec?.subject_key)===sc);const scores=(Array.isArray(data.section_scores)?data.section_scores:[]).filter((sec:any)=>tidy(sec?.subject||sec?.subject_key)===sc);if(!sections.length&&!scores.length)return json(req,{error:"هذه المحاولة خارج مادة حسابك."},403);data.rendered_sections=sections;data.section_scores=scores;}}const sm=await studentsMap([String(data.student_id||"")]),s=sm.get(String(data.student_id||""));return json(req,{ok:true,mode:"read_only",attempt:{source,...data,student_name:s?.full_name||null,class_name:data.class_name||s?.class_name||null,grade:s?.grade||null}})}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return json(req,{error:"method_not_allowed"},405);try{const access=await requireAccess(req),body=await req.json().catch(()=>({})),action=tidy(body?.action||"summary");if(action==="summary")return await summary(req,access);if(action==="students")return await roster(req,access);if(action==="grades")return await grades(req,body,access);if(action==="attempt")return await attempt(req,body,access);return json(req,{error:"action_not_supported"},400)}catch(error){console.error("lugati-moallimi-read",error);const status=error&&typeof error==="object"&&"status" in error?Number((error as any).status):500;return json(req,{error:status===500?"تعذر قراءة نتائج معلّمي.":String((error as Error).message)},status)}});