import { FRAMEWORK } from './framework.ts';
import { hasCurrentReview, reviewedImage, REVIEW_VERSION } from './reviewed-bank.ts';
import { type Row, SUBJECTS, THRESHOLDS, tidy, fail, hash, token, shuffle, randomFrom, normalizeConfig, questionKey, indicatorOf, selectUnique, buildForms, cleanAnswers, gradeSections, publicSections, permuteQuestion } from './assessment-engine.ts';
const BASE='https://zarie19991-bit.github.io/moallimi/';
const BANK_COLUMNS='id,subject_key,outcome_code,indicator_index,indicator_text,model_no,question_no,measurement_focus,alignment_profile,alignment_verified,alignment_evidence,context_text,question_text,options,correct_index,explanation,difficulty,cognitive_level';
const isUUID=(s:unknown)=>/^[a-f0-9-]{36}$/i.test(String(s));
function must(result:Row) {if(result.error)throw result.error;return result.data;}
function rendered(row:Row) {return{id:row.id,subject:row.subject_key,outcome:row.outcome_code,indicator:row.indicator_index,indicator_key:`${row.subject_key}:${row.outcome_code}:i${row.indicator_index}`,indicator_text:row.indicator_text,model_no:row.model_no,question_no:row.question_no,context:row.context_text||null,question:row.question_text,options:row.options,correctIndex:row.correct_index,explanation:row.explanation||null,cognitive_level:row.cognitive_level,difficulty:row.difficulty,image:reviewedImage(row)};}
async function fullPool(db:any,subject:string,keys?:string[],ids?:string[]) {const all:Row[]=[];const scoped=keys?.map(key=>FRAMEWORK.find(i=>i.key===key)).filter(Boolean)||[];for(let start=0;;start+=500){let query=db.from('nafes_question_bank').select(BANK_COLUMNS).eq('grade_key','middle_3').eq('subject_key',subject).eq('is_active',true).eq('review_status','approved').lte('model_no',2).order('id');if(scoped.length)query=query.in('outcome_code',[...new Set(scoped.map(i=>i!.outcome))]).in('indicator_index',[...new Set(scoped.map(i=>i!.indicator))]);if(ids?.length)query=query.in('id',ids);const page=must(await query.range(start,start+499));for(const q of page||[])if(hasCurrentReview(q))all.push(rendered(q));if(!page||page.length<500)break;}return all;}

async function teacher(db:any,req:Request) {const key=tidy(req.headers.get('x-teacher-key'),128);if(!/^[a-f0-9]{48,96}$/i.test(key))fail('أدخل مفتاح دخول المعلم لعرض النتائج وإعداد الاختبارات.',401);const row=must(await db.from('nafes_teacher_access').select('id,label').eq('key_hash',await hash(key)).eq('active',true).maybeSingle());if(!row)fail('مفتاح دخول المعلم غير صحيح.',401);return row;}
function testInfo(t:Row) {const c=t.config||{};return{id:t.kind==='legacy'?legacyTestId(t.legacy_target):t.id,title:t.title,kind:t.kind==='legacy'?'indicator':t.kind,subjects:(c.sections||[]).map((s:Row)=>s.subject),class_name:c.class_name||'',school_name:c.school_name||'',teacher_name:c.teacher_name||'',principal_name:c.principal_name||'',grade_key:'middle_3',created_at:t.published_at||t.created_at,total:(c.sections||[]).reduce((n:number,s:Row)=>n+s.question_count,0),short_code:t.short_code};}
function legacyTestId(t:Row) {return`exam:${t.subject||t.subject_key}:${t.outcome||t.outcome_code}:i${t.indicator||t.indicator_index}:m${t.model||t.model_no}`;}
async function catalog(db:any) {let available=new Map<string,number>();for(let offset=0;;offset+=1000){const page=must(await db.from('nafes_question_bank').select('subject_key,outcome_code,indicator_index').eq('grade_key','middle_3').eq('review_status','approved').eq('is_active',true).eq('alignment_verified',true).eq('alignment_evidence->>validator',REVIEW_VERSION).lte('model_no',2).order('id').range(offset,offset+999));for(const q of page||[]){const k=`${q.subject_key}:${q.outcome_code}:i${q.indicator_index}`;available.set(k,(available.get(k)||0)+1);}if(!page||page.length<1000)break;}const rows=must(await db.from('nafes_simulation_forms').select('subject,model_no,created_at'));const forms=SUBJECTS.flatMap(subject=>Array.from({length:60},(_,i)=>({subject,model_no:i+1,question_count:30,ready:rows.some((r:Row)=>r.subject===subject&&r.model_no===i+1)})));return{indicators:FRAMEWORK.map(i=>({...i,available:available.get(i.key)||0})),forms,thresholds:THRESHOLDS};}
async function findDraft(db:any,id:unknown,owner:Row) {if(!isUUID(id))fail('المسودة غير موجودة.');const t=must(await db.from('nafes_assessments').select('*').eq('id',id).eq('owner_id',owner.id).maybeSingle());if(!t)fail('المسودة غير موجودة.',404);if(t.status!=='draft')fail('نُشر الاختبار بالفعل؛ أنشئ نسخة جديدة لتغيير الأسئلة.',409);return t;}
function preview(t:Row) {return{draft_id:t.id,config:t.config,sections:t.rendered_sections};}
async function draftSections(db:any,c:Row,regenerate=false) {const sections:Row[]=[];const used=new Set<string>();for(const s of c.sections){let pool:Row[]=[];let qs:Row[]=[];if(c.kind!=='simulation'||regenerate||s.question_count>30)pool=await fullPool(db,s.subject,c.kind!=='simulation'?s.indicators.map((i:Row)=>i.key):undefined);
 if(c.kind==='simulation'&&regenerate){qs=selectUnique(pool,s.question_count,token(8));}
 else if(c.kind==='simulation'){const form=must(await db.from('nafes_simulation_forms').select('questions').eq('subject',s.subject).eq('model_no',s.model_no).maybeSingle());if(!form)fail('نموذج المحاكاة المختار لم يُجهز بعد من البنك المراجع.',409);if(!pool.length)pool=await fullPool(db,s.subject,undefined,form.questions.map((q:Row)=>q.id));const current=new Map(pool.map(q=>[q.id,q]));let base=(form.questions||[]).filter((q:Row)=>current.has(q.id)&&questionKey(current.get(q.id)!)===questionKey(q));if(base.length!==30)fail('هذا النموذج يحتاج تحديثًا بعد مراجعة البنك؛ اختر نموذجًا جاهزًا.',409);qs=base.slice(0,s.question_count);if(qs.length<s.question_count)qs.push(...selectUnique(pool,s.question_count-qs.length,token(8),new Map(),new Set(qs.map(questionKey))));}
 else for(const i of s.indicators){let candidates=pool.filter(q=>q.indicator_key===i.key);if(s.fixed_model)candidates=candidates.filter(q=>q.model_no===s.fixed_model);const actual=new Set(candidates.map(questionKey)).size;if(actual<i.count)fail(`المؤشر «${i.text}»: المطلوب ${i.count} سؤالًا، والمتاح ${actual} فقط. لن يتكرر أي سؤال.`);qs.push(...s.fixed_model?candidates.sort((a,b)=>a.question_no-b.question_no):selectUnique(candidates,i.count,token(8),new Map(),used));}
 for(const q of qs){const k=questionKey(q);if(used.has(k))fail('يوجد سؤال مكرر بين المؤشرات المختارة؛ قلل العدد أو بدّل أحد المؤشرات.');used.add(k);}sections.push({...s,questions:qs});}
 return sections;}
async function codeFor(db:any) {for(let n=0;n<6;n++){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const code=[...crypto.getRandomValues(new Uint8Array(8))].map(x=>chars[x%chars.length]).join('');const r=must(await db.from('nafes_assessments').select('id').eq('short_code',code).maybeSingle());if(!r)return code;}fail('تعذر إنشاء رمز الاختبار؛ أعد المحاولة.');}
async function assessment(db:any,code:unknown) {if(!/^[A-Z2-9]{8}$/.test(String(code||'')))fail('رمز الاختبار غير صالح.',404);const t=must(await db.from('nafes_assessments').select('*').eq('short_code',code).eq('status','published').maybeSingle());if(!t)fail('رابط الاختبار غير موجود.',404);return t;}
function studentInfo(t:Row) {const c=t.config;return{id:t.id,code:t.short_code,title:t.title,kind:t.kind,class_name:c.class_name,school_name:c.school_name,teacher_name:c.teacher_name,grade_key:'middle_3',identity_mode:c.identity_mode,settings:c.settings,sections:(c.sections||[]).map((s:Row)=>({subject:s.subject,question_count:s.question_count,duration_minutes:s.duration_minutes,calculator:s.calculator})),ready:true,...(t.kind==='legacy'?{legacy_url:new URL(`exam.html?s=${t.legacy_target.subject}&o=${t.legacy_target.outcome}&i=${t.legacy_target.indicator}&m=${t.legacy_target.model}`,BASE).href}:{})};}
const snapshotKey=(q:Row)=>JSON.stringify([q.id,q.context||null,q.question,q.options,q.correctIndex,q.explanation||null,q.indicator_key,q.indicator_text,q.cognitive_level,q.difficulty,q.model_no,q.question_no,q.image?.url||null,q.image?.alt||null]);
const flat=(a:Row)=>(a.rendered_sections||[]).flatMap((s:Row)=>s.questions||[]);
async function finish(db:any,a:Row,answers=a.answers) {if(a.submitted_at)return a;const result=gradeSections(a.rendered_sections,answers);const end=new Date(Math.min(Date.now(),new Date(a.expires_at).getTime())).toISOString();const r=must(await db.from('nafes_assessment_attempts').update({answers,...result,submitted_at:end,version:a.version+1}).eq('id',a.id).eq('version',a.version).is('submitted_at',null).select().maybeSingle());return r||must(await db.from('nafes_assessment_attempts').select('*').eq('id',a.id).single());}
function attemptResponse(a:Row) {const c=a.config,s=c.settings;const response:Row={attempt_id:a.id,submitted:!!a.submitted_at,expires_at:a.expires_at,started_at:a.started_at,section_started_at:a.section_started_at,current_section:a.section_index,cursor:a.cursor,version:a.version,answers:a.answers,sections:publicSections(a.rendered_sections),settings:s,student_name:a.student_name};if(a.submitted_at){if(s.show_result)Object.assign(response,{score:a.score,total:a.total,percent:a.percent,section_scores:a.section_scores});else response.result_hidden=true;if(s.show_correct_count)response.correct_count=a.score;if(s.show_indicator_result){const groups=new Map<string,Row[]>();for(const q of flat(a)){const key=indicatorOf(q),g=groups.get(key)||[];g.push(q);groups.set(key,g);}response.indicators=[...groups].map(([key,qs])=>({key,text:qs[0].indicator_text,...gradeSections([{subject:qs[0].subject,questions:qs}],a.answers)}));}if(s.show_answers)response.review=flat(a).map(q=>({id:q.id,correct_index:q.correctIndex,explanation:q.explanation,indicator_text:q.indicator_text}));}return response;}
async function saveState(db:any,a:Row,body:Row) {
 if(a.submitted_at)return a;const now=Date.now();if(now>=new Date(a.expires_at).getTime())return await finish(db,a);
 const s=a.config.settings;let index=a.section_index,cursor=a.cursor,sectionStarted=a.section_started_at;const section=a.rendered_sections[index],deadline=new Date(sectionStarted).getTime()+section.duration_minutes*60000;
 const raw=cleanAnswers(flat(a),body.answers),answers={...a.answers};
 if(now>=new Date(sectionStarted).getTime()&&now<=deadline){for(let i=0;i<section.questions.length;i++){const q=section.questions[i];if(s.allow_back||i===cursor){if(Object.hasOwn(raw,q.id))answers[q.id]=raw[q.id];}}
  const requested=Number(body.cursor);if(Number.isInteger(requested)&&requested>=0&&requested<section.questions.length&&(s.allow_back||requested===cursor||requested===cursor+1))cursor=requested;
 }
 const advance=body.action==='assessment_advance'||now>deadline;
 if(advance){if(index===a.rendered_sections.length-1)return await finish(db,a,answers);index++;cursor=0;sectionStarted=new Date(Math.min(now,deadline)+s.break_minutes*60000).toISOString();}
 let events=a.events||[];if(s.log_visibility&&['hidden','visible','page_leave','copy_blocked','print_blocked'].includes(body.event?.type)&&events.length<2000)events=[...events,{type:body.event.type,at:new Date().toISOString(),section:index}];
 if(body.action==='assessment_finish')return await finish(db,a,answers);
 const update={answers,cursor,section_index:index,section_started_at:sectionStarted,events,lease_until:new Date(now+45000).toISOString(),version:a.version+1};
 const row=must(await db.from('nafes_assessment_attempts').update(update).eq('id',a.id).eq('version',a.version).is('submitted_at',null).select().maybeSingle());if(!row)fail('تغيرت المحاولة أثناء الحفظ؛ أعد المحاولة.',409);return row;
}
async function studentAction(db:any,body:Row) {
 if(body.action==='assessment_info')return studentInfo(await assessment(db,body.code));
 if(body.action==='assessment_start'){
  const t=await assessment(db,body.code);if(t.kind==='legacy')return studentInfo(t);const c=t.config,s=c.settings,now=Date.now();
  if(s.opens_at&&now<new Date(s.opens_at).getTime())fail('لم يبدأ وقت إتاحة الاختبار بعد.',403);
  if(s.closes_at&&now>new Date(s.closes_at).getTime())fail('انتهى وقت إتاحة الاختبار.',403);
  const name=tidy(body.student_name,120),no=tidy(body.student_no,160),session=tidy(body.session_id,96);if(name.length<2||!no||!session)fail('اكتب اسم الطالب ورقمه المميز.');
  if(c.identity_mode==='list'&&!c.roster.some((n:string)=>tidy(n).toLowerCase()===name.toLowerCase()))fail('اكتب اسمك كما هو في كشف الفصل.',403);
  if(c.identity_mode==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(no))fail('أدخل البريد المدرسي بصيغة صحيحة.');
  const student_key=await hash(`${name.toLowerCase()}|${no.toLowerCase()}`);
  const previous=must(await db.from('nafes_assessment_attempts').select('*').eq('assessment_id',t.id).eq('student_key',student_key).order('attempt_no',{ascending:false}));
  for(const a of previous)if(!a.submitted_at&&now>=new Date(a.expires_at).getTime())Object.assign(a,await finish(db,a));
  let active=previous.find((a:Row)=>!a.submitted_at);const access=token();
  if(active){if(s.lock_session&&active.session_id!==session&&now<new Date(active.lease_until).getTime())fail('المحاولة مفتوحة في جهاز أو تبويب آخر. أغلقها هناك وانتظر ٤٥ ثانية لإكمالها هنا.',409);
   active=must(await db.from('nafes_assessment_attempts').update({session_id:session,access_hash:await hash(access),lease_until:new Date(now+45000).toISOString(),version:active.version+1}).eq('id',active.id).eq('version',active.version).is('submitted_at',null).select().maybeSingle());if(!active)fail('فُتحت المحاولة في تبويب آخر؛ أعد المحاولة.',409);return{...attemptResponse(active),access_token:access,resumed:true};}
  if(previous.length>=s.attempts){if(previous[0])return{...attemptResponse(previous[0]),attempts_exhausted:true};fail('استُنفد عدد المحاولات المسموح به.',409);}
  const seed=token(12);const rand=randomFrom(seed);const sections=t.rendered_sections.map((section:Row)=>({...section,questions:(s.shuffle_questions?shuffle(section.questions,rand):section.questions).map((q:Row)=>s.shuffle_options?permuteQuestion(q,rand):q)}));
  const duration=c.sections.reduce((n:number,sec:Row)=>n+sec.duration_minutes,0)+s.break_minutes*(sections.length-1);const expires=new Date(Math.min(now+duration*60000,s.closes_at?new Date(s.closes_at).getTime():Infinity)).toISOString();
  const r=await db.from('nafes_assessment_attempts').insert({assessment_id:t.id,student_name:name,student_no:no,student_key,class_name:c.class_name||tidy(body.class_name,80),attempt_no:previous.length+1,config:c,rendered_sections:sections,session_id:session,access_hash:await hash(access),lease_until:new Date(now+45000).toISOString(),expires_at:expires}).select().single();if(r.error?.code==='23505')fail('بدأت محاولة لهذا الطالب؛ أعد فتحها من التبويب الأصلي.',409);const created=must(r);return{...attemptResponse(created),access_token:access,resumed:false};
 }
 if(!isUUID(body.attempt_id)||!body.access_token)fail('تعذر التحقق من المحاولة.',403);let a=must(await db.from('nafes_assessment_attempts').select('*').eq('id',body.attempt_id).eq('access_hash',await hash(String(body.access_token))).maybeSingle());if(!a)fail('تعذر التحقق من المحاولة.',403);
 if(!a.submitted_at&&a.config.settings.lock_session&&a.session_id!==body.session_id)fail('المحاولة قيد الاستخدام في تبويب آخر.',409);
 if(!['assessment_save','assessment_finish','assessment_advance','assessment_resume','assessment_event'].includes(body.action))fail('إجراء غير معروف.');
 if(body.action==='assessment_resume'&&!a.submitted_at&&Date.now()<new Date(a.expires_at).getTime())return attemptResponse(a);
 a=await saveState(db,a,body);return{ok:true,...attemptResponse(a)};
}
const SOURCES:Row={exam:'nafes_exam_attempts',simulation:'nafes_simulation_attempts',assessment:'nafes_assessment_attempts'};
const READING_FOCUS=['vocab_context','vocab_definition','vocab_classify','vocab_distinguish','vocab_use','main_structure','implicit_questions','compare_texts','fact_opinion','relationships','emotion_language','credibility_solutions','values_impact','arguments_evidence','summary_organize','problem_solving'];
async function metadata(db:any,rows:Row[],source:string) {for(const a of rows)for(const q of (source==='exam'?(a.rendered_questions||[]):flat(a)))q.question_fingerprint=await hash(questionKey(q));const ids=[...new Set(rows.flatMap(a=>source==='exam'?(a.rendered_questions||[]):flat(a)).map(q=>q.id).filter(isUUID))];const map=new Map<string,Row>();for(let i=0;i<ids.length;i+=150){const data=must(await db.from('nafes_question_bank').select('id,subject_key,outcome_code,indicator_index,indicator_text').in('id',ids.slice(i,i+150)));for(const q of data||[])map.set(q.id,q);}return map;}
function canonical(a:Row,source:string,map:Map<string,Row>,test?:Row):Row {
 const c=a.config||{};const sections=source==='exam'?[{subject:a.subject_key,questions:a.rendered_questions||[]}]:a.rendered_sections||[];
 let warning='';const qs=sections.flatMap((sec:Row)=>sec.questions.map((q:Row)=>{
  const m=map.get(q.id);let key=q.indicator_key;if(!key&&source==='exam')key=`${a.subject_key}:${a.outcome_code}:i${a.indicator_index}`;
  if(!key&&m)key=`${m.subject_key}:${m.outcome_code}:i${m.indicator_index}`;
  if(!key&&q.measurement_focus){const f=FRAMEWORK.find(i=>i.key===q.measurement_focus);if(f)key=f.key;else if(sec.subject==='reading'){const pos=READING_FOCUS.indexOf(q.measurement_focus);if(pos>=0)key=FRAMEWORK.filter(i=>i.subject==='reading')[pos]?.key;}}
  const indicator=FRAMEWORK.find(i=>i.key===key);const correct_index=Number.isInteger(q.correctIndex)&&q.correctIndex>=0&&q.correctIndex<q.options?.length?q.correctIndex:null;const answer=Number.isInteger(a.answers?.[q.id])&&a.answers[q.id]>=0&&a.answers[q.id]<q.options?.length?a.answers[q.id]:null;
  if(correct_index===null)warning='تحتوي الورقة التاريخية على مفتاح إجابة غير صالح؛ حُفظت الدرجة الأصلية، ولا تدخل هذه المحاولة في تقدير المستوى أو التحسن.';
  return{id:q.id,question:q.question,question_fingerprint:q.question_fingerprint,subject:sec.subject,indicator_key:key||null,indicator_text:q.indicator_text||indicator?.text||m?.indicator_text||'لم يُحفظ ارتباط هذا السؤال بمؤشر',answer,correct:correct_index===null?null:answer===correct_index,scorable:correct_index!==null,correct_index};
 }));
 const id=source==='exam'?legacyTestId(a):source==='simulation'?`simulation:${a.simulation_key}`:a.assessment_id;
 const submitted=!!a.submitted_at;const levelTotal=a.total||qs.length;return{id:a.id,source,test_id:id,title:test?.title||c.title||(source==='exam'?`اختبار مؤشر ${a.indicator_index} — النموذج ${a.model_no}`:'اختبار نافس'),kind:source==='exam'?'indicator':source==='simulation'?'simulation':c.kind,subjects:[...new Set(sections.map((s:Row)=>s.subject))],student_key:a.student_key,student_name:a.student_name,student_no:a.student_no,class_name:a.class_name||c.class_name||'',school_name:c.school_name||'',teacher_name:c.teacher_name||'',principal_name:c.principal_name||'',grade_key:'middle_3',started_at:a.started_at,submitted_at:a.submitted_at,expires_at:a.expires_at,elapsed_seconds:submitted?Math.max(0,Math.round((Math.min(new Date(a.submitted_at).getTime(),new Date(a.expires_at).getTime())-new Date(a.started_at).getTime())/1000)):null,status:submitted?'submitted':Date.now()>new Date(a.expires_at).getTime()?'expired':'in_progress',score:submitted?a.score:null,total:levelTotal,percent:submitted?a.percent:null,questions:qs,events:a.events||[],...(warning?{snapshot_warning:warning}:{})};
}
async function teacherData(db:any,b:Row) {
 const limit=Math.min(100,Math.max(1,Math.trunc(Number(b.limit)||100))),cursor=Math.max(0,Math.trunc(Number(b.cursor)||0));
 const expired=must(await db.from('nafes_assessment_attempts').select('*').is('submitted_at',null).lte('expires_at',new Date().toISOString()).limit(100));for(const a of expired||[])await finish(db,a);
 const counts:Row={};for(const [source,table]of Object.entries(SOURCES)){const r=await db.from(table).select('id',{count:'exact',head:true});if(r.error)throw r.error;counts[source]=r.count||0;}
 const attempts:Row[]=[];let offset=0;for(const [source,table]of Object.entries(SOURCES)){const start=Math.max(0,cursor-offset),end=Math.min(counts[source],cursor+limit-offset);if(end>start){const rows=must(await db.from(table).select('*').order('id').range(start,end-1));const map=await metadata(db,rows,source);attempts.push(...rows.map((a:Row)=>canonical(a,source,map)));}offset+=counts[source];}
 let tests:Row[]=[];if(cursor===0){const published=must(await db.from('nafes_assessments').select('id,title,kind,status,config,short_code,created_at,published_at,legacy_target').eq('status','published'));tests=published.map(testInfo);const known=new Set(tests.map(t=>t.id));for(const i of FRAMEWORK)for(let model=1;model<=2;model++){const id=legacyTestId({...i,model});if(!known.has(id))tests.push({id,title:`${i.subject==='reading'?'القراءة':i.subject==='math'?'الرياضيات':'العلوم'} — ${i.text} — النموذج ${model}`,kind:'indicator',subjects:[i.subject],class_name:'',grade_key:'middle_3',total:15});}
 const sims=must(await db.from('nafes_simulation_attempts').select('simulation_key,config,started_at').order('started_at'));for(const a of sims){const id=`simulation:${a.simulation_key}`;if(known.has(id))continue;known.add(id);tests.push({...testInfo({id,title:a.config.title,kind:'simulation',config:a.config,created_at:a.started_at}),id});}}
 return{attempts,tests,indicators:cursor===0?FRAMEWORK:[],thresholds:THRESHOLDS,next_cursor:cursor+limit<offset?cursor+limit:null};
}
export async function handleAssessments(db:any,req:Request,b:Row):Promise<Row> {
 if(String(b.action).startsWith('assessment_'))return await studentAction(db,b);
 const owner=await teacher(db,req);
 if(b.action==='teacher_data')return await teacherData(db,b);
 if(b.action==='teacher_paper') {if(!SOURCES[b.source]||!isUUID(b.attempt_id))fail('المحاولة غير موجودة.',404);const a=must(await db.from(SOURCES[b.source]).select('*').eq('id',b.attempt_id).maybeSingle());if(!a)fail('المحاولة غير موجودة.',404);const map=await metadata(db,[a],b.source),attempt=canonical(a,b.source,map);const ss=b.source==='exam'?[{subject:a.subject_key,questions:a.rendered_questions||[]}]:a.rendered_sections;let n=0;const sections=ss.map((s:Row)=>({...s,questions:s.questions.map((q:Row)=>{const summary=attempt.questions[n++];return{...q,...summary,correctIndex:summary.correct_index};})}));return{attempt,sections,settings:a.config?.settings||{}};}
 if(b.action==='teacher_catalog')return{...await catalog(db),tests:must(await db.from('nafes_assessments').select('id,title,kind,config,short_code,created_at,published_at,legacy_target').eq('status','published')).map(testInfo)};
 if(b.action==='teacher_preview') {const config=normalizeConfig(b.config),sections=await draftSections(db,config,b.regenerate===true);const draft=must(await db.from('nafes_assessments').insert({owner_id:owner.id,kind:config.kind,title:config.title,config,rendered_sections:sections}).select().single());return preview(draft);}
 if(b.action==='teacher_replace') {const t=await findDraft(db,b.draft_id,owner);const sections=t.rendered_sections;const all=sections.flatMap((s:Row)=>s.questions),old=all.find((q:Row)=>q.id===b.question_id);if(!old)fail('السؤال غير موجود في المسودة.');const pool=(await fullPool(db,old.subject,[old.indicator_key])).filter(q=>q.indicator_key===old.indicator_key);const candidates=pool.filter(q=>!all.some((x:Row)=>questionKey(x)===questionKey(q)));if(!candidates.length)fail('لا يوجد سؤال بديل مستقل متاح لهذا المؤشر.');const replacement=selectUnique(candidates,1,token(8))[0];for(const s of sections)s.questions=s.questions.map((q:Row)=>q.id===old.id?replacement:q);return preview(must(await db.from('nafes_assessments').update({rendered_sections:sections}).eq('id',t.id).eq('status','draft').select().single()));}
 if(b.action==='teacher_publish') {const t=await findDraft(db,b.draft_id,owner);for(const section of t.rendered_sections){const pool=await fullPool(db,section.subject,undefined,section.questions.map((q:Row)=>q.id));const current=new Map(pool.map(q=>[q.id,q]));if(section.questions.some((q:Row)=>!current.has(q.id)||snapshotKey(current.get(q.id)!)!==snapshotKey(q)))fail('تغير البنك بعد المعاينة؛ أعد تكوين المسودة قبل نشرها.',409);}const short_code=await codeFor(db);const saved=must(await db.from('nafes_assessments').update({status:'published',short_code,published_at:new Date().toISOString()}).eq('id',t.id).eq('status','draft').select().single());return{id:saved.id,short_code,url:`${BASE}e.html?t=${short_code}`,title:saved.title};}
 if(b.action==='teacher_shorten_legacy') {const i=FRAMEWORK.find(i=>i.subject===b.subject&&i.outcome===b.outcome&&i.indicator===Number(b.indicator));if(!i||![1,2].includes(Number(b.model)))fail('الاختبار غير موجود.');const target={subject:i.subject,outcome:i.outcome,indicator:i.indicator,model:Number(b.model)};const pool=(await fullPool(db,i.subject,[i.key])).filter(q=>q.indicator_key===i.key&&q.model_no===target.model);if(pool.length!==15)fail('الاختبار لم يكتمل اعتماده؛ لا يمكن إنشاء باركود له.',409);const previous=must(await db.from('nafes_assessments').select('*').eq('kind','legacy').eq('status','published').contains('legacy_target',target).limit(1));let t=previous?.[0];if(!t){const code=await codeFor(db);t=must(await db.from('nafes_assessments').insert({owner_id:owner.id,short_code:code,status:'published',kind:'legacy',title:`${i.text} — النموذج ${target.model}`,config:{sections:[{subject:i.subject,question_count:15,duration_minutes:20}],settings:{},identity_mode:'manual'},legacy_target:target,published_at:new Date().toISOString()}).select().single());}return{id:t.id,short_code:t.short_code,url:`${BASE}e.html?t=${t.short_code}`,title:t.title};}
 if(b.action==='teacher_build_forms') {if(!SUBJECTS.includes(b.subject))fail('المادة غير صحيحة.');const pool=await fullPool(db,b.subject),expected=FRAMEWORK.filter(i=>i.subject===b.subject).length*30;if(pool.length!==expected)fail(`لم يكتمل البنك المراجع للمادة: ${pool.length} من ${expected}.`,409);const bank_hash=await hash(JSON.stringify(pool));const forms=buildForms(pool,b.subject);for(const f of forms){f.signature=await hash(f.signature);f.bank_hash=bank_hash;}const result=must(await db.rpc('replace_nafes_simulation_forms',{payload:forms}));return{ok:true,subject:b.subject,forms:60,question_slots:1800,unique_questions:new Set(forms.flatMap(f=>f.questions.map((q:Row)=>q.id))).size,result};}
 fail('إجراء غير معروف.');
}
