import fs from 'node:fs';
import { performance } from 'node:perf_hooks';
const PROJECT='https://udznpifopbnrcgxtpzza.supabase.co/functions/v1';
const EXAM=`${PROJECT}/nafes-exam`,CATALOG=`${PROJECT}/nafes-catalog`,GRADES=`${PROJECT}/nafes-analysis-grades`,RESULTS=`${PROJECT}/nafes-results-admin`;
const SITE='https://zarie19991-bit.github.io/moallimi/';
const KEY=process.env.QA_TEACHER_KEY||'';
const run=Date.now().toString(36).slice(-7),checks=[],failures=[];
const state={run,createdStudents:[],createdTests:[],loadMetrics:null};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function rec(name,ok,detail=''){checks.push({name,ok,detail});if(!ok)failures.push({name,detail});console.log(`${ok?'PASS':'FAIL'} ${name}${detail?` :: ${detail}`:''}`)}
async function check(name,fn){try{const d=await fn();rec(name,true,typeof d==='string'?d:d?JSON.stringify(d):'');return d}catch(e){rec(name,false,e?.message||String(e));return null}}
async function post(url,body,key=KEY,retries=2){let last;for(let i=0;i<=retries;i++){const t=performance.now();try{const res=await fetch(url,{method:'POST',headers:{'content-type':'application/json',...(key?{'x-teacher-key':key}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(45000)});const text=await res.text();let data={};try{data=JSON.parse(text)}catch{data={raw:text}};last={status:res.status,data,ms:performance.now()-t};if(![502,503,504].includes(res.status))return last}catch(e){last={status:0,data:{error:e.message},ms:performance.now()-t}}if(i<retries)await sleep(i?900:400)}return last}
function must(r,label){if(!r||r.status!==200||r.data?.error)throw new Error(`${label}: HTTP ${r?.status} ${r?.data?.error||JSON.stringify(r?.data||{})}`);return r.data}
const teacher=(action,body={})=>post(EXAM,{action,...body});
const student=(action,body={})=>post(EXAM,{action,...body},'',2);
function settings(){return{show_result:true,show_answers:true,show_indicator_result:true,show_correct_count:true,shuffle_questions:true,shuffle_options:true,allow_copy:false,disable_right_click:true,disable_print:true,disable_shortcuts:true,allow_back:true,one_per_page:false,lock_session:true,log_visibility:true,watermark:true,attempts:3,break_minutes:0,opens_at:null,closes_at:null}}
function indicatorConfig(ind,title,className){return{kind:'multi_indicator',bank_source:'indicator_bank',grade_key:'middle_3',title,class_name:className,term:'QA',academic_term:'QA',school_name:'مدرسة ابن سينا المتوسطة',teacher_name:'QA',principal_name:'QA',identity_mode:'manual',roster:[],count_mode:'per_indicator',sections:[{subject:ind.subject,question_count:15,duration_minutes:20,calculator:false,model_no:1,indicators:[{key:ind.key,count:15}]}],settings:settings()}}
function simCustomConfig(ind,title,className){return{kind:'simulation',simulation_mode:'custom',bank_source:'simulation_bank',grade_key:'middle_3',title,class_name:className,term:'QA',academic_term:'QA',school_name:'مدرسة ابن سينا المتوسطة',teacher_name:'QA',principal_name:'QA',identity_mode:'manual',roster:[],count_mode:'per_indicator',sections:[{subject:ind.subject,question_count:10,duration_minutes:20,calculator:false,model_no:1,indicators:[{key:ind.key,count:10}]}],settings:settings()}}
function fullConfig(title,className){return{kind:'simulation',simulation_mode:'standard',bank_source:'simulation_bank',grade_key:'middle_3',title,class_name:className,term:'QA',academic_term:'QA',school_name:'مدرسة ابن سينا المتوسطة',teacher_name:'QA',principal_name:'QA',identity_mode:'manual',roster:[],count_mode:'total',sections:[{subject:'reading',question_count:20,duration_minutes:30,calculator:false,model_no:1,indicators:[]},{subject:'math',question_count:25,duration_minutes:35,calculator:true,model_no:1,indicators:[]},{subject:'science',question_count:20,duration_minutes:30,calculator:false,model_no:1,indicators:[]}],settings:settings()}}
async function publish(config){const p=must(await teacher('teacher_preview',{config}),'preview');if(!p.draft_id)throw new Error('draft missing');const pub=must(await teacher('teacher_publish',{draft_id:p.draft_id}),'publish');state.createdTests.push({id:pub.id,code:pub.short_code,title:pub.title});return{preview:p,pub}}
async function addStudent(name,last3,cls){const d=must(await teacher('teacher_student_add',{full_name:name,national_id_last3:last3,class_name:cls,grade:'الصف الثالث المتوسط'}),'student_add');state.createdStudents.push(d.student.id);return d.student}
function flat(x){return (x.sections||[]).flatMap(s=>s.questions||[])}
async function finishFlow(code,st,label){const wrong=await student('assessment_start',{code,session_id:`bad-${run}-${label}`,student_name:'اسم غير مطابق',student_no:st.national_id_last3,class_name:st.class_name});if(wrong.status===200&&!wrong.data?.error)throw new Error('wrong identity accepted');const session=`v2-${run}-${label}`;const start=must(await student('assessment_start',{code,session_id:session,student_name:st.full_name,student_no:st.national_id_last3,class_name:st.class_name}),'start');const qs=flat(start);if(!qs.length)throw new Error('no questions');if(qs.some(q=>'correctIndex'in q||'correct_index'in q||'explanation'in q))throw new Error('answer key leaked');const answers=Object.fromEntries(qs.map(q=>[q.id,0]));const common={code,session_id:session,attempt_id:start.attempt_id,access_token:start.access_token,answers,cursor:0};must(await student('assessment_save',{...common,event:{type:'qa_save'}}),'save');const done=must(await student('assessment_finish',common),'finish');if(!done.submitted)throw new Error('not submitted');return{start,done}}
function percentile(xs,p){const a=[...xs].sort((x,y)=>x-y);return a[Math.min(a.length-1,Math.floor((a.length-1)*p))]||0}
await check('public_live_assets',async()=>{for(const p of ['','create.html','e.html','exam.html','analysis.html','student-papers.html','analysis-participation.js']){const r=await fetch(SITE+p,{signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`${p||'index'} ${r.status}`)}const a=await(await fetch(SITE+'analysis.html')).text();if(!a.includes('analysis-participation.js?v=20260912-2'))throw new Error('latest participation script not linked');return'current live assets OK'});
let catalog,readingInd,scienceInd,simReadingInd;
await check('catalog_and_indicator_framework',async()=>{catalog=must(await post(CATALOG,{action:'teacher_catalog'}),'catalog');if(catalog.indicators?.length!==270||catalog.simulation_indicators?.length!==270)throw new Error(`framework ${catalog.indicators?.length}/${catalog.simulation_indicators?.length}`);readingInd=catalog.indicators.find(x=>x.subject==='reading');scienceInd=catalog.indicators.find(x=>x.subject==='science');simReadingInd=catalog.simulation_indicators.find(x=>x.subject==='reading');if(!readingInd||!scienceInd||!simReadingInd)throw new Error('subject indicators missing');return{summary:catalog.simulation_summary,reading:readingInd.key,science:scienceInd.key}});
await check('baseline_roster_140',async()=>{const d=must(await teacher('teacher_students_list',{include_archived:false}),'roster');const c=Object.fromEntries(['أ','ب','ج','د'].map(x=>[x,d.students.filter(s=>s.class_name===x).length]));if(d.students.length!==140||Object.values(c).some(n=>n!==35))throw new Error(JSON.stringify({total:d.students.length,c}));state.baselineRoster=140;return c});
const p1Name=`طالب QA مشاركة ${run}`,p2Name=`طالب QA متعدد ${run}`,p3Name=`طالب QA أرشفة ${run}`;
let p1,p2,p3;
await check('student_add_update_archive_restore',async()=>{p1=await addStudent(p1Name,'981','أ');p2=await addStudent(p2Name,'982','QATEST');p3=await addStudent(p3Name,'983','QATEST');const newName=`طالب QA أرشفة محدث ${run}`;p3=must(await teacher('teacher_student_update',{id:p3.id,full_name:newName,national_id_last3:'983',class_name:'QATEST',grade:'الصف الثالث المتوسط'}),'update').student;must(await teacher('teacher_student_delete',{id:p3.id}),'archive');const all=must(await teacher('teacher_students_list',{include_archived:true}),'list archived').students;const archived=all.find(s=>s.id===p3.id);if(!archived||archived.is_active!==false)throw new Error('archive not reflected');p3=must(await teacher('teacher_student_restore',{id:p3.id}),'restore').student;if(p3.is_active!==true)throw new Error('restore not reflected');return'add/update/archive/restore OK'});
let reading,sciencePreview,simCustom,full;
await check('regular_reading_builder',async()=>{reading=await publish(indicatorConfig(readingInd,`QA قراءة ${run}`,'أ'));if(reading.preview.sections?.[0]?.questions?.length!==15)throw new Error('reading count !=15');state.main={id:reading.pub.id,code:reading.pub.short_code,title:reading.pub.title};return state.main});
await check('regular_science_builder',async()=>{sciencePreview=must(await teacher('teacher_preview',{config:indicatorConfig(scienceInd,`QA علوم ${run}`,'QATEST')}),'science preview');if(sciencePreview.sections?.[0]?.questions?.length!==15)throw new Error(`science count ${sciencePreview.sections?.[0]?.questions?.length}`);return'15 science questions'});
await check('custom_simulation_builder',async()=>{simCustom=await publish(simCustomConfig(simReadingInd,`QA محاكاة مؤشرات ${run}`,'QATEST'));if(simCustom.preview.sections?.[0]?.questions?.length!==10)throw new Error('custom sim count !=10');return simCustom.pub.short_code});
await check('full_simulation_builder',async()=>{full=await publish(fullConfig(`QA محاكاة شاملة ${run}`,'QATEST'));const counts=(full.preview.sections||[]).map(s=>s.questions.length);if(counts.join(',')!=='20,25,20')throw new Error(`counts ${counts}`);state.full={id:full.pub.id,code:full.pub.short_code,title:full.pub.title};return counts});
let flow1,flow2;
await check('student_reading_login_save_finish',async()=>{flow1=await finishFlow(reading.pub.short_code,p1,'reading');if(Number(flow1.done.total)!==15)throw new Error(`total ${flow1.done.total}`);state.mainAttempt=flow1.start.attempt_id;state.mainStudent={full_name:p1.full_name,national_id_last3:p1.national_id_last3,class_name:p1.class_name,id:p1.id};return{score:flow1.done.score,total:flow1.done.total}});
await check('teacher_data_and_student_paper_api',async()=>{let cursor=0,attempts=[];do{const d=must(await teacher('teacher_data',{cursor,limit:100}),'teacher_data');attempts.push(...(d.attempts||[]));cursor=d.next_cursor}while(cursor!==null);if(!attempts.find(a=>a.id===state.mainAttempt))throw new Error('attempt missing');const paper=must(await teacher('teacher_paper',{source:'assessment',attempt_id:state.mainAttempt}),'paper');const qs=flat(paper);if(qs.length!==15||!qs.every(q=>'correctIndex'in q))throw new Error(`paper questions ${qs.length}`);return{attempts:attempts.length,paper:qs.length}});
await check('analysis_saved_grade',async()=>{const d=must(await post(GRADES,{}),'grades');const g=(d.grades||[]).find(x=>x.id===state.mainAttempt);if(!g||Number(g.total)!==15||g.class_name!=='أ')throw new Error(JSON.stringify(g));return{score:g.score,total:g.total,class_name:g.class_name}});
await check('multi_subject_section_scores',async()=>{flow2=await finishFlow(full.pub.short_code,p2,'multi');if(Number(flow2.done.total)!==65)throw new Error(`total ${flow2.done.total}`);if(!Array.isArray(flow2.done.section_scores)||flow2.done.section_scores.length!==3)throw new Error('section_scores missing');state.fullAttempt=flow2.start.attempt_id;return flow2.done.section_scores});
await check('individual_result_delete',async()=>{if(!state.fullAttempt)throw new Error('no multi attempt to delete');const d=must(await post(RESULTS,{action:'teacher_attempt_delete',source:'assessment',attempt_id:state.fullAttempt,student_id:p2.id,test_id:full.pub.id,confirm_word:'حذف النتيجة'}),'delete');if(Number(d.deleted)!==1)throw new Error(JSON.stringify(d));return d});
await check('randomization_5_students',async()=>{const names=[];for(let i=0;i<5;i++)names.push(await addStudent(`طالب QA عشوائية ${run} ${i}`,String(970+i).padStart(3,'0'),'أ'));const orders=[];for(let i=0;i<names.length;i++){const s=names[i],d=must(await student('assessment_start',{code:reading.pub.short_code,session_id:`rand-${run}-${i}`,student_name:s.full_name,student_no:s.national_id_last3,class_name:s.class_name}),'rand start');orders.push({q:flat(d).map(q=>q.id).join('|'),o:flat(d).map(q=>q.options?.join('¦')).join('|')})}const qn=new Set(orders.map(x=>x.q)).size,on=new Set(orders.map(x=>x.o)).size;if(qn<2||on<2)throw new Error(`questionOrders=${qn},optionOrders=${on}`);return{questionOrders:qn,optionOrders:on}});
let loadTest;
await check('load_test_setup_140',async()=>{loadTest=await publish(indicatorConfig(readingInd,`QA ضغط ${run}`,'QALOAD'));const students=Array.from({length:140},(_,i)=>{const n=String(i).padStart(3,'0');return{full_name:`طالب QA ضغط ${run} ${n}`,national_id_last3:n,class_name:'QALOAD',grade:'الصف الثالث المتوسط'}});state.loadStudents=students;const d=must(await teacher('teacher_students_bulk_import',{students}),'bulk import');if(Number(d.added)!==140)throw new Error(JSON.stringify({added:d.added,updated:d.updated,restored:d.restored,ignored:d.ignored,failed:d.failed}));return{added:d.added,code:loadTest.pub.short_code}});
await check('load_140_start_save_finish',async()=>{const list=state.loadStudents;async function req(body){let first,last,t0=performance.now();for(let a=1;a<=3;a++){last=await post(EXAM,body,'',0);if(a===1)first=last.status;if(![502,503,504].includes(last.status))return{...last,first,attempts:a,totalMs:performance.now()-t0};if(a<3)await sleep(a===1?450:900)}return{...last,first,attempts:3,totalMs:performance.now()-t0}}
const starts=await Promise.all(list.map((s,i)=>req({action:'assessment_start',code:loadTest.pub.short_code,session_id:`load-${run}-${i}`,student_name:s.full_name,student_no:s.national_id_last3,class_name:s.class_name})));const good=starts.map((r,i)=>({r,i,s:list[i]})).filter(x=>x.r.status===200&&!x.r.data?.error&&x.r.data?.attempt_id);const saves=await Promise.all(good.map(async x=>{const answers=Object.fromEntries(flat(x.r.data).map(q=>[q.id,0]));const r=await req({action:'assessment_save',code:loadTest.pub.short_code,session_id:`load-${run}-${x.i}`,attempt_id:x.r.data.attempt_id,access_token:x.r.data.access_token,answers,cursor:0});return{r,x,answers}}));const saveGood=saves.filter(x=>x.r.status===200&&!x.r.data?.error);const finishes=await Promise.all(saveGood.map(async x=>req({action:'assessment_finish',code:loadTest.pub.short_code,session_id:`load-${run}-${x.x.i}`,attempt_id:x.x.r.data.attempt_id,access_token:x.x.r.data.access_token,answers:x.answers,cursor:0})));const fg=finishes.filter(r=>r.status===200&&!r.data?.error&&r.data?.submitted);const metrics={start_success:good.length,save_success:saveGood.length,finish_success:fg.length,start_retries:starts.filter(r=>r.attempts>1).length,first_503:starts.filter(r=>r.first===503).length,start_p95_ms:Math.round(percentile(starts.map(r=>r.totalMs),.95)),save_p95_ms:Math.round(percentile(saves.map(x=>x.r.totalMs),.95)),finish_p95_ms:Math.round(percentile(finishes.map(r=>r.totalMs),.95))};state.loadMetrics=metrics;if(good.length!==140||saveGood.length!==140||fg.length!==140)throw new Error(JSON.stringify(metrics));return metrics});
await check('bulk_clear_load_test_results',async()=>{const d=must(await post(RESULTS,{action:'teacher_tests_bulk_clear',test_ids:[loadTest.pub.id],confirm_word:'حذف النتائج'}),'bulk clear');if(Number(d.total_cleared)!==140)throw new Error(JSON.stringify(d));return d});
await check('participation_source_during_qa',async()=>{const d=must(await teacher('teacher_students_list',{include_archived:false}),'roster');const classA=d.students.filter(s=>s.class_name==='أ').length;if(classA!==41)throw new Error(`classA=${classA}, expected 41`);state.classACount=classA;state.totalRosterDuringQA=d.students.length;return{total:d.students.length,classA}});
fs.writeFileSync('/tmp/qa-v2-state.json',JSON.stringify(state,null,2));
fs.writeFileSync('/tmp/qa-v2-api.json',JSON.stringify({checks,failures,state},null,2));
console.log('QA_V2_API_SUMMARY',JSON.stringify({passed:checks.filter(x=>x.ok).length,failed:failures.length,failures,load:state.loadMetrics}));
