import fs from 'node:fs';
import { chromium } from 'playwright-core';
const KEY=process.env.QA_TEACHER_KEY||'';
const SITE='https://zarie19991-bit.github.io/moallimi/';
const CHROME=process.env.CHROME_PATH||'/usr/bin/google-chrome';
const state=JSON.parse(fs.readFileSync('/tmp/qa-v2-state.json','utf8'));
const checks=[],failures=[];
function rec(name,ok,detail=''){checks.push({name,ok,detail});if(!ok)failures.push({name,detail});console.log(`${ok?'PASS':'FAIL'} ${name}${detail?` :: ${detail}`:''}`)}
async function check(name,fn){try{const d=await fn();rec(name,true,typeof d==='string'?d:d?JSON.stringify(d):'')}catch(e){rec(name,false,e?.message||String(e))}}
const browser=await chromium.launch({headless:true,executablePath:CHROME,args:['--no-sandbox']});
const context=await browser.newContext({locale:'ar-SA'});
const page=await context.newPage();
page.on('dialog',d=>d.accept().catch(()=>{}));
await check('browser_student_login_and_render',async()=>{await page.goto(`${SITE}e.html?t=${state.main.code}`,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForSelector('#identity:not([hidden])',{timeout:30000});await page.fill('#studentName',state.mainStudent.full_name);await page.fill('#studentNo',state.mainStudent.national_id_last3);await page.selectOption('#className',state.mainStudent.class_name);await page.click('#startBtn');await page.waitForSelector('#player:not([hidden])',{timeout:30000});const text=(await page.locator('#questions').innerText()).trim();if(text.length<20)throw new Error('questions not rendered');const wm=(await page.locator('#watermark').innerText()).trim();if(!wm.includes('طالب'))throw new Error('watermark missing');return{question_chars:text.length,watermark:true}});
await check('browser_create_catalog',async()=>{await page.goto(`${SITE}create.html#key=${KEY}`,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForFunction(()=>window.NafesTeacher?.getKey?.(),null,{timeout:30000});const d=await page.evaluate(async()=>await window.NafesTeacher.api('teacher_catalog'));if(d.indicators?.length!==270||d.simulation_indicators?.length!==270)throw new Error(`catalog ${d.indicators?.length}/${d.simulation_indicators?.length}`);if(Number(d.simulation_summary?.science)<1590)throw new Error('science catalog incomplete');return d.simulation_summary});
await check('browser_analysis_total_tested_absent',async()=>{await page.goto(`${SITE}analysis.html#key=${KEY}`,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForSelector('#dashboard:not([hidden])',{timeout:30000});await page.click('button[data-view="subject"]');await page.selectOption('#subjectSelect','reading');await page.waitForFunction(id=>[...document.querySelectorAll('#analysisSubjectTest option')].some(o=>o.value===id),state.main.id,{timeout:30000});await page.selectOption('#analysisSubjectTest',state.main.id);await page.selectOption('#subjectClass','أ');await page.click('#buildSubjectOfficialBtn');await page.waitForSelector('#subjectOfficialPreview .subject-analysis-sheet',{timeout:30000});await page.waitForFunction(()=>['إجمالي الطلاب','اختبر','لم يختبر'].every(label=>[...document.querySelectorAll('#subjectOfficialPreview .sar-stat-list span')].some(x=>x.textContent.trim()===label)),null,{timeout:30000});const data=await page.evaluate(()=>Object.fromEntries([...document.querySelectorAll('#subjectOfficialPreview .sar-stat-list>div')].map(r=>[r.querySelector('span')?.textContent.trim(),r.querySelector('b')?.innerText.trim()])));const nf=new Intl.NumberFormat('ar-SA');if(data['إجمالي الطلاب']!==nf.format(state.classACount))throw new Error(`total=${data['إجمالي الطلاب']} expected ${nf.format(state.classACount)}`);if(!data['اختبر']?.startsWith(nf.format(1)))throw new Error(`tested=${data['اختبر']}`);if(data['لم يختبر']!==nf.format(state.classACount-1))throw new Error(`absent=${data['لم يختبر']}`);const sig=await page.evaluate(()=>{const s=document.querySelector('#subjectOfficialPreview .sar-signatures span');return{before:getComputedStyle(s,'::before').content,after:getComputedStyle(s,'::after').content}});if(!['none','normal','""',''].includes(sig.before)||!['none','normal','""',''].includes(sig.after))throw new Error(`signature pseudo ${JSON.stringify(sig)}`);return data});
await check('browser_subject_report_total_tested_absent',async()=>{await page.click('button[data-view="subjectReport"]');await page.selectOption('#reportSubjectSelect','reading');await page.waitForFunction(id=>[...document.querySelectorAll('#reportSubjectTest option')].some(o=>o.value===id),state.main.id,{timeout:30000});await page.selectOption('#reportSubjectTest',state.main.id);await page.selectOption('#reportSubjectClass','أ');await page.click('#buildSubjectReportBtn');await page.waitForSelector('#subjectOfficialReport .subject-analysis-sheet',{timeout:30000});await page.waitForFunction(()=>['إجمالي الطلاب','اختبر','لم يختبر'].every(label=>[...document.querySelectorAll('#subjectOfficialReport .sar-stat-list span')].some(x=>x.textContent.trim()===label)),null,{timeout:30000});const t=await page.locator('#subjectOfficialReport .sar-stat-list').innerText();if(!t.includes('إجمالي الطلاب')||!t.includes('لم يختبر'))throw new Error(t);return t.slice(0,180)});
await check('browser_general_report_participation',async()=>{await page.click('button[data-view="report"]');await page.waitForSelector('#reportTest option',{timeout:30000});const options=await page.locator('#reportTest option').all();let val='';for(const o of options){const tx=await o.innerText();if(tx.includes(state.main.title)){val=await o.getAttribute('value');break}}if(!val)throw new Error('QA test missing from general report selector');await page.selectOption('#reportTest',val);await page.click('#buildReportBtn');await page.waitForSelector('#reportPreview .weekly-report.report-sheet',{timeout:30000});await page.waitForFunction(()=>{const t=document.querySelector('#reportPreview')?.innerText||'';return t.includes('إجمالي الطلاب')&&t.includes('اختبر:')&&t.includes('لم يختبر:')},null,{timeout:30000});const text=await page.locator('#reportPreview').innerText();return text.match(/إجمالي الطلاب[^\n]*|اختبر:[^\n]*|لم يختبر:[^\n]*/g)?.slice(0,3)});
await check('browser_student_papers_list_and_open',async()=>{await page.goto(`${SITE}student-papers.html#key=${KEY}`,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForSelector('#papersDashboard:not([hidden])',{timeout:30000});await page.selectOption('#classSelect','أ');await page.selectOption('#paperSubject','reading');await page.waitForFunction(id=>[...document.querySelectorAll('#paperTest option')].some(o=>o.value===id),state.main.id,{timeout:30000});await page.selectOption('#paperTest',state.main.id);await page.dispatchEvent('#paperTest','change');await page.waitForFunction(name=>document.querySelector('#studentsList')?.innerText.includes(name),state.mainStudent.full_name,{timeout:30000});const row=page.locator('#studentsList tr').filter({hasText:state.mainStudent.full_name});if(await row.count()!==1)throw new Error('QA student row missing');const btn=row.locator('.btn-paper');if(await btn.count()!==1)throw new Error('paper button missing');await btn.click();await page.waitForSelector('#paperPanel:not([hidden]) .paper-question',{timeout:30000});const qs=await page.locator('#paperPanel .paper-question').count();if(qs!==15)throw new Error(`paper questions ${qs}`);return{questions:qs}});
await browser.close();
fs.writeFileSync('/tmp/qa-v2-browser.json',JSON.stringify({checks,failures},null,2));
console.log('QA_V2_BROWSER_SUMMARY',JSON.stringify({passed:checks.filter(x=>x.ok).length,failed:failures.length,failures}));
