const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const {stripTypeScriptTypes}=require('node:module');
const root=path.resolve(__dirname,'..');
const els=new Map(),calls=[];
let options=[];
const mount={_html:'',get innerHTML(){return this._html},set innerHTML(value){this._html=value;els.clear();options=[];for(const m of value.matchAll(/<(?:input|select|button|div)[^>]*id="([^"]+)"[^>]*>/g)){const tag=m[0];els.set(m[1],{value:tag.match(/value="([^"]*)"/)?.[1]||'',addEventListener(type,fn){this[type]=fn},textContent:''})}for(const m of value.matchAll(/data-comp-answer="(\d)"/g))options.push({dataset:{compAnswer:m[1]},disabled:false})}};
const context={console,Date,window:{},setInterval:()=>1,clearInterval:()=>{},alert:()=>{},document:{getElementById:id=>id==='lugatiCompetitionMount'?mount:els.get(id),querySelectorAll:selector=>selector==='[data-comp-answer]'?options:[]},fetch:async(url,opts)=>{const body=JSON.parse(opts.body);calls.push(body);return {ok:true,json:async()=>({correct:true,question_completed:true,finished:false,message:'إجابة صحيحة.'})}}};
vm.createContext(context);
const text=fs.readFileSync(path.join(root,'lugati-competition.js'),'utf8');
vm.runInContext(text.replace('window.LugatiCompetition={mount};','window.LugatiCompetition={S,render,renderPreview,renderTeacherResults,teacherCreate,captureDraft,answer,questionImage,questionCount,studentHistory};'),context);
const x=context.window.LugatiCompetition;
(async()=>{
 x.S.catalog=[];x.S.draft={title:'محفوظ',open:'2026-10-01T08:00',close:'2026-10-01T09:00',count:6};mount.innerHTML=x.teacherCreate();
 assert.equal(els.get('compTitle').value,'محفوظ');assert.equal(els.get('compClose').value,'2026-10-01T09:00');
 els.get('compTitle').value='جديد';x.captureDraft();mount.innerHTML=x.teacherCreate();assert.equal(els.get('compTitle').value,'جديد');
 x.S.selected.set('a',{});assert.ok(!/id="createCompRound" disabled/.test(x.teacherCreate()));
 x.S.role='student';x.S.screen='attempt';x.S.round={id:'r',question_count:3};x.S.attempt={question:{id:'q1',position:1,question_text:'سؤال',options:['أ','ب','ج','د']},attempt:{started_at:new Date().toISOString()}};x.render();
 assert.equal(x.questionCount(),3);await x.answer(1);assert.equal(calls[0].question_id,'q1');assert.ok(mount.innerHTML.includes('إجابة صحيحة.'));assert.ok(mount.innerHTML.includes('id="compNext"'));assert.ok(options.every(o=>o.disabled));await x.answer(2);assert.equal(calls.length,1);
 x.S.preview={questions:[{position:1,context_text:'نص القراءة كامل',question_text:'سؤال',options:[],correct_index:0}]};x.renderPreview(mount);assert.ok(mount.innerHTML.includes('نص القراءة كامل'));
 x.S.screen='teacher-results';x.S.teacherResult={round:{question_count:6},students:[],classes:[],indicator_report:[{indicator_text:'فهم النص',students:[{full_name:'اختبار محلي',class_name:'ج',correct:1,total:3,unanswered:1,percent:33}],needs_support:[{}]}]};x.renderTeacherResults(mount);assert.ok(mount.innerHTML.includes('اختبار محلي'));assert.ok(mount.innerHTML.includes('يحتاج دعمًا'));assert.equal(x.questionCount(),6);
 x.S.data={history:[{id:'old',title:'الجولة القديمة'}]};assert.ok(x.studentHistory().includes('الجولة القديمة'));
 assert.equal(x.questionImage({image:{url:'javascript:alert(1)'}}),'');
 const source=fs.readFileSync(path.join(root,'supabase/functions/lugati-competition/index.ts'),'utf8');
 const js=stripTypeScriptTypes(source,{mode:'strip'}).replace(/^import .*;\s*$/gm,'');
 const backend={createClient:()=>({}),Deno:{env:{get:()=>''},serve:()=>{}},console};vm.createContext(backend);vm.runInContext(js+';globalThis.check={safeCompetitionQuestion,validateIndicators};',backend);
 const q={question_text:'اختر الإجابة الصحيحة',options:['a','b','c','d'],correct_index:2};assert.equal(backend.check.safeCompetitionQuestion(q),true);
 assert.equal(backend.check.safeCompetitionQuestion({...q,options:['a','a','c','d']}),false);
 assert.equal(backend.check.safeCompetitionQuestion({...q,question_text:'انظر إلى الشكل ثم أجب'}),false);
 const cat=[{outcome_code:'a',indicator_index:1,indicator_text:'مؤشر'}];assert.equal(backend.check.validateIndicators({},cat,cat).length,1);
 assert.equal(backend.check.safeCompetitionQuestion({...q,question_text:'انظر إلى الشكل ثم أجب',image:{url:'https://zarie19991-bit.github.io/moallimi/question-bank/assets/'+ 'a'.repeat(64)+'.png'}}),true);
 console.log('PASS: 18 frontend/backend regression assertions (mock DOM, no live student records).');
})().catch(e=>{console.error(e);process.exit(1)});
